// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/grpc/proto/buildreport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildReport mirrors internal/buildreport.Report 1:1. Timestamps are unix
// millis; a zero timestamp means unknown (not the 1970 epoch).
type BuildReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`                                      // "go" | "rust"
	Compiler        string                 `protobuf:"bytes,2,opt,name=compiler,proto3" json:"compiler,omitempty"`                                      // "go" | "rust/cargo"
	CompilerVersion string                 `protobuf:"bytes,3,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"` // normalized "major.minor" (e.g. "1.27"); empty = undetermined
	StartedAt       int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                  // unix millis; 0 = unknown
	EndedAt         int64                  `protobuf:"varint,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`                        // unix millis; 0 = unknown
	DurationMs      int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`               // wall-clock build duration
	BuildArgs       []string               `protobuf:"bytes,7,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty"`
	// cache_status is the compiler-cache classification: "cold" | "hit" |
	// "unknown". cache_source names the mechanism when known
	// ("go-build-cache" | "cargo-incremental" | "docker-layer"); empty otherwise.
	CacheStatus string `protobuf:"bytes,8,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"`
	CacheSource string `protobuf:"bytes,9,opt,name=cache_source,json=cacheSource,proto3" json:"cache_source,omitempty"`
	// artifact_type: "binary" | "docker-image". size in bytes (0 for images /
	// unknown). platform is "os/arch" (e.g. "linux/amd64") when applicable.
	ArtifactType      string `protobuf:"bytes,10,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ArtifactSizeBytes int64  `protobuf:"varint,11,opt,name=artifact_size_bytes,json=artifactSizeBytes,proto3" json:"artifact_size_bytes,omitempty"`
	ArtifactPlatform  string `protobuf:"bytes,12,opt,name=artifact_platform,json=artifactPlatform,proto3" json:"artifact_platform,omitempty"`
	// Failure info. Successful builds leave failed=false; a failed build is
	// reported with the stage ("compile") and a redacted error summary. Failed
	// single builds never become versions, but the shape stays future-proof.
	Failed bool   `protobuf:"varint,13,opt,name=failed,proto3" json:"failed,omitempty"`
	Stage  string `protobuf:"bytes,14,opt,name=stage,proto3" json:"stage,omitempty"`
	Error  string `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	// regression is the comparison against this app's recent comparable builds,
	// when one could be computed. Absent means no baseline / not comparable.
	Regression    *BuildRegression `protobuf:"bytes,16,opt,name=regression,proto3" json:"regression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildReport) Reset() {
	*x = BuildReport{}
	mi := &file_internal_grpc_proto_buildreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReport) ProtoMessage() {}

func (x *BuildReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_buildreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReport.ProtoReflect.Descriptor instead.
func (*BuildReport) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_buildreport_proto_rawDescGZIP(), []int{0}
}

func (x *BuildReport) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BuildReport) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *BuildReport) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *BuildReport) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BuildReport) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *BuildReport) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BuildReport) GetBuildArgs() []string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *BuildReport) GetCacheStatus() string {
	if x != nil {
		return x.CacheStatus
	}
	return ""
}

func (x *BuildReport) GetCacheSource() string {
	if x != nil {
		return x.CacheSource
	}
	return ""
}

func (x *BuildReport) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *BuildReport) GetArtifactSizeBytes() int64 {
	if x != nil {
		return x.ArtifactSizeBytes
	}
	return 0
}

func (x *BuildReport) GetArtifactPlatform() string {
	if x != nil {
		return x.ArtifactPlatform
	}
	return ""
}

func (x *BuildReport) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *BuildReport) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *BuildReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildReport) GetRegression() *BuildRegression {
	if x != nil {
		return x.Regression
	}
	return nil
}

// BuildRegression mirrors internal/buildreport.Analyze output (Analysis +
// MetricComparison). A metric that is not comparable degrades to
// comparable=false + a skip_reason, never a misleading percentage. The regression
// booleans reflect the CLI-side thresholds (binary size >=1MB OR >=5%; duration
// >=25% AND >=2s) — persist them, do not recompute.
type BuildRegression struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SizeComparable       bool                   `protobuf:"varint,1,opt,name=size_comparable,json=sizeComparable,proto3" json:"size_comparable,omitempty"`
	SizePreviousBytes    int64                  `protobuf:"varint,2,opt,name=size_previous_bytes,json=sizePreviousBytes,proto3" json:"size_previous_bytes,omitempty"`
	SizeCurrentBytes     int64                  `protobuf:"varint,3,opt,name=size_current_bytes,json=sizeCurrentBytes,proto3" json:"size_current_bytes,omitempty"`
	SizeDeltaBytes       int64                  `protobuf:"varint,4,opt,name=size_delta_bytes,json=sizeDeltaBytes,proto3" json:"size_delta_bytes,omitempty"`        // signed
	SizePercentDelta     float64                `protobuf:"fixed64,5,opt,name=size_percent_delta,json=sizePercentDelta,proto3" json:"size_percent_delta,omitempty"` // NaN when undefined (render "-")
	SizeRegression       bool                   `protobuf:"varint,6,opt,name=size_regression,json=sizeRegression,proto3" json:"size_regression,omitempty"`
	DurationComparable   bool                   `protobuf:"varint,7,opt,name=duration_comparable,json=durationComparable,proto3" json:"duration_comparable,omitempty"`
	DurationPreviousMs   int64                  `protobuf:"varint,8,opt,name=duration_previous_ms,json=durationPreviousMs,proto3" json:"duration_previous_ms,omitempty"`
	DurationCurrentMs    int64                  `protobuf:"varint,9,opt,name=duration_current_ms,json=durationCurrentMs,proto3" json:"duration_current_ms,omitempty"`
	DurationDeltaMs      int64                  `protobuf:"varint,10,opt,name=duration_delta_ms,json=durationDeltaMs,proto3" json:"duration_delta_ms,omitempty"` // signed
	DurationPercentDelta float64                `protobuf:"fixed64,11,opt,name=duration_percent_delta,json=durationPercentDelta,proto3" json:"duration_percent_delta,omitempty"`
	DurationRegression   bool                   `protobuf:"varint,12,opt,name=duration_regression,json=durationRegression,proto3" json:"duration_regression,omitempty"`
	HistoryUsed          int32                  `protobuf:"varint,13,opt,name=history_used,json=historyUsed,proto3" json:"history_used,omitempty"`                        // comparable builds in the window (<= 5)
	BaselineSizeBytes    int64                  `protobuf:"varint,14,opt,name=baseline_size_bytes,json=baselineSizeBytes,proto3" json:"baseline_size_bytes,omitempty"`    // window average
	BaselineDurationMs   int64                  `protobuf:"varint,15,opt,name=baseline_duration_ms,json=baselineDurationMs,proto3" json:"baseline_duration_ms,omitempty"` // window average
	SkipReason           string                 `protobuf:"bytes,16,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`                            // why a metric was not comparable; empty when both compared
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BuildRegression) Reset() {
	*x = BuildRegression{}
	mi := &file_internal_grpc_proto_buildreport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRegression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRegression) ProtoMessage() {}

func (x *BuildRegression) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_buildreport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRegression.ProtoReflect.Descriptor instead.
func (*BuildRegression) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_buildreport_proto_rawDescGZIP(), []int{1}
}

func (x *BuildRegression) GetSizeComparable() bool {
	if x != nil {
		return x.SizeComparable
	}
	return false
}

func (x *BuildRegression) GetSizePreviousBytes() int64 {
	if x != nil {
		return x.SizePreviousBytes
	}
	return 0
}

func (x *BuildRegression) GetSizeCurrentBytes() int64 {
	if x != nil {
		return x.SizeCurrentBytes
	}
	return 0
}

func (x *BuildRegression) GetSizeDeltaBytes() int64 {
	if x != nil {
		return x.SizeDeltaBytes
	}
	return 0
}

func (x *BuildRegression) GetSizePercentDelta() float64 {
	if x != nil {
		return x.SizePercentDelta
	}
	return 0
}

func (x *BuildRegression) GetSizeRegression() bool {
	if x != nil {
		return x.SizeRegression
	}
	return false
}

func (x *BuildRegression) GetDurationComparable() bool {
	if x != nil {
		return x.DurationComparable
	}
	return false
}

func (x *BuildRegression) GetDurationPreviousMs() int64 {
	if x != nil {
		return x.DurationPreviousMs
	}
	return 0
}

func (x *BuildRegression) GetDurationCurrentMs() int64 {
	if x != nil {
		return x.DurationCurrentMs
	}
	return 0
}

func (x *BuildRegression) GetDurationDeltaMs() int64 {
	if x != nil {
		return x.DurationDeltaMs
	}
	return 0
}

func (x *BuildRegression) GetDurationPercentDelta() float64 {
	if x != nil {
		return x.DurationPercentDelta
	}
	return 0
}

func (x *BuildRegression) GetDurationRegression() bool {
	if x != nil {
		return x.DurationRegression
	}
	return false
}

func (x *BuildRegression) GetHistoryUsed() int32 {
	if x != nil {
		return x.HistoryUsed
	}
	return 0
}

func (x *BuildRegression) GetBaselineSizeBytes() int64 {
	if x != nil {
		return x.BaselineSizeBytes
	}
	return 0
}

func (x *BuildRegression) GetBaselineDurationMs() int64 {
	if x != nil {
		return x.BaselineDurationMs
	}
	return 0
}

func (x *BuildRegression) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

var File_internal_grpc_proto_buildreport_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_buildreport_proto_rawDesc = "" +
	"\n" +
	"%internal/grpc/proto/buildreport.proto\x12\x06phelix\"\xaf\x04\n" +
	"\vBuildReport\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcompiler\x18\x02 \x01(\tR\bcompiler\x12)\n" +
	"\x10compiler_version\x18\x03 \x01(\tR\x0fcompilerVersion\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\x03R\aendedAt\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"build_args\x18\a \x03(\tR\tbuildArgs\x12!\n" +
	"\fcache_status\x18\b \x01(\tR\vcacheStatus\x12!\n" +
	"\fcache_source\x18\t \x01(\tR\vcacheSource\x12#\n" +
	"\rartifact_type\x18\n" +
	" \x01(\tR\fartifactType\x12.\n" +
	"\x13artifact_size_bytes\x18\v \x01(\x03R\x11artifactSizeBytes\x12+\n" +
	"\x11artifact_platform\x18\f \x01(\tR\x10artifactPlatform\x12\x16\n" +
	"\x06failed\x18\r \x01(\bR\x06failed\x12\x14\n" +
	"\x05stage\x18\x0e \x01(\tR\x05stage\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x127\n" +
	"\n" +
	"regression\x18\x10 \x01(\v2\x17.phelix.BuildRegressionR\n" +
	"regression\"\xe5\x05\n" +
	"\x0fBuildRegression\x12'\n" +
	"\x0fsize_comparable\x18\x01 \x01(\bR\x0esizeComparable\x12.\n" +
	"\x13size_previous_bytes\x18\x02 \x01(\x03R\x11sizePreviousBytes\x12,\n" +
	"\x12size_current_bytes\x18\x03 \x01(\x03R\x10sizeCurrentBytes\x12(\n" +
	"\x10size_delta_bytes\x18\x04 \x01(\x03R\x0esizeDeltaBytes\x12,\n" +
	"\x12size_percent_delta\x18\x05 \x01(\x01R\x10sizePercentDelta\x12'\n" +
	"\x0fsize_regression\x18\x06 \x01(\bR\x0esizeRegression\x12/\n" +
	"\x13duration_comparable\x18\a \x01(\bR\x12durationComparable\x120\n" +
	"\x14duration_previous_ms\x18\b \x01(\x03R\x12durationPreviousMs\x12.\n" +
	"\x13duration_current_ms\x18\t \x01(\x03R\x11durationCurrentMs\x12*\n" +
	"\x11duration_delta_ms\x18\n" +
	" \x01(\x03R\x0fdurationDeltaMs\x124\n" +
	"\x16duration_percent_delta\x18\v \x01(\x01R\x14durationPercentDelta\x12/\n" +
	"\x13duration_regression\x18\f \x01(\bR\x12durationRegression\x12!\n" +
	"\fhistory_used\x18\r \x01(\x05R\vhistoryUsed\x12.\n" +
	"\x13baseline_size_bytes\x18\x0e \x01(\x03R\x11baselineSizeBytes\x120\n" +
	"\x14baseline_duration_ms\x18\x0f \x01(\x03R\x12baselineDurationMs\x12\x1f\n" +
	"\vskip_reason\x18\x10 \x01(\tR\n" +
	"skipReasonB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_buildreport_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_buildreport_proto_rawDescData []byte
)

func file_internal_grpc_proto_buildreport_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_buildreport_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_buildreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_buildreport_proto_rawDesc), len(file_internal_grpc_proto_buildreport_proto_rawDesc)))
	})
	return file_internal_grpc_proto_buildreport_proto_rawDescData
}

var file_internal_grpc_proto_buildreport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_buildreport_proto_goTypes = []any{
	(*BuildReport)(nil),     // 0: phelix.BuildReport
	(*BuildRegression)(nil), // 1: phelix.BuildRegression
}
var file_internal_grpc_proto_buildreport_proto_depIdxs = []int32{
	1, // 0: phelix.BuildReport.regression:type_name -> phelix.BuildRegression
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_buildreport_proto_init() }
func file_internal_grpc_proto_buildreport_proto_init() {
	if File_internal_grpc_proto_buildreport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_buildreport_proto_rawDesc), len(file_internal_grpc_proto_buildreport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_buildreport_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_buildreport_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_buildreport_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_buildreport_proto = out.File
	file_internal_grpc_proto_buildreport_proto_goTypes = nil
	file_internal_grpc_proto_buildreport_proto_depIdxs = nil
}
