// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/grpc/proto/build.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildEvent reports one terminal build outcome (phelix build / rebuild, native,
// docker or matrix) to the backend via ReportBuildEvent. It is best-effort
// telemetry gated by the "build_report" capability: a backend that does not
// implement ReportBuildEvent answers UNIMPLEMENTED and the agent disables build
// reporting for the rest of the process, exactly like ReportDeploymentEvent.
//
// A build is not a deployment and not a rollback — it has its own RPC so a plain
// `phelix build` (no deploy) and `--no-upload` builds are not forced through the
// deployment or rollback paths. The session token is never in the body (gRPC
// metadata only); user_id is the session id. error / stage inside the report are
// redacted.
type BuildEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServerId  string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // agent_id of the reporting runtime
	AppId     string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`          // CLI application id
	AppName   string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Version   string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // "vN"; empty when the build recorded no version
	Tag       string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	GitCommit string                 `protobuf:"bytes,6,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	// build_mode: "classic" (single native build) | "docker" (dockerize) |
	// "matrix" (build/dockerize --matrix). Unknown values degrade to "unknown".
	BuildMode string `protobuf:"bytes,7,opt,name=build_mode,json=buildMode,proto3" json:"build_mode,omitempty"`
	Success   bool   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	// report is the single-artifact build report (classic/docker). Empty for a
	// matrix build — see combinations.
	Report *BuildReport `protobuf:"bytes,9,opt,name=report,proto3" json:"report,omitempty"`
	// combinations carries one entry per matrix cell (matrix builds only), each
	// with its own report. Empty for single builds.
	Combinations []*MatrixCombinationState `protobuf:"bytes,10,rep,name=combinations,proto3" json:"combinations,omitempty"`
	Timestamp    int64                     `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	// user_id is the operator's session id (never the raw token — that is in
	// gRPC metadata). Empty when the build ran without a resolvable session.
	UserId string `protobuf:"bytes,12,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// request_id correlates a remote-triggered build with the originating command.
	RequestId string `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// error_code is the structured phelix code on failure (e.g. BUILD_FAILED).
	// Empty on success and for unclassified failures.
	ErrorCode     string `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_internal_grpc_proto_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_build_proto_rawDescGZIP(), []int{0}
}

func (x *BuildEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *BuildEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BuildEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *BuildEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildEvent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BuildEvent) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *BuildEvent) GetBuildMode() string {
	if x != nil {
		return x.BuildMode
	}
	return ""
}

func (x *BuildEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildEvent) GetReport() *BuildReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *BuildEvent) GetCombinations() []*MatrixCombinationState {
	if x != nil {
		return x.Combinations
	}
	return nil
}

func (x *BuildEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BuildEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BuildEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BuildEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_internal_grpc_proto_build_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_build_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/proto/build.proto\x12\x06phelix\x1a%internal/grpc/proto/buildreport.proto\x1a internal/grpc/proto/matrix.proto\"\xc5\x03\n" +
	"\n" +
	"BuildEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x06 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_mode\x18\a \x01(\tR\tbuildMode\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12+\n" +
	"\x06report\x18\t \x01(\v2\x13.phelix.BuildReportR\x06report\x12B\n" +
	"\fcombinations\x18\n" +
	" \x03(\v2\x1e.phelix.MatrixCombinationStateR\fcombinations\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\f \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCodeB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_build_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_build_proto_rawDescData []byte
)

func file_internal_grpc_proto_build_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_build_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_build_proto_rawDesc), len(file_internal_grpc_proto_build_proto_rawDesc)))
	})
	return file_internal_grpc_proto_build_proto_rawDescData
}

var file_internal_grpc_proto_build_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_grpc_proto_build_proto_goTypes = []any{
	(*BuildEvent)(nil),             // 0: phelix.BuildEvent
	(*BuildReport)(nil),            // 1: phelix.BuildReport
	(*MatrixCombinationState)(nil), // 2: phelix.MatrixCombinationState
}
var file_internal_grpc_proto_build_proto_depIdxs = []int32{
	1, // 0: phelix.BuildEvent.report:type_name -> phelix.BuildReport
	2, // 1: phelix.BuildEvent.combinations:type_name -> phelix.MatrixCombinationState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_build_proto_init() }
func file_internal_grpc_proto_build_proto_init() {
	if File_internal_grpc_proto_build_proto != nil {
		return
	}
	file_internal_grpc_proto_buildreport_proto_init()
	file_internal_grpc_proto_matrix_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_build_proto_rawDesc), len(file_internal_grpc_proto_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_build_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_build_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_build_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_build_proto = out.File
	file_internal_grpc_proto_build_proto_goTypes = nil
	file_internal_grpc_proto_build_proto_depIdxs = nil
}
