// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/deployment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeploymentFailure explains why a deployment stopped. code is a Phelix
// structured error code (internal/errors/codes.go) such as BUILD_FAILED,
// INSTANCE_START_FAILED, HEALTH_CHECK_FAILED, PROXY_ERROR or DEPLOY_FAILED.
// message is redacted before it leaves the CLI.
type DeploymentFailure struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// retryable is the CLI's judgement on whether repeating the same deployment
	// could plausibly succeed (health/proxy/port/timeout conditions) as opposed
	// to needing a code or configuration change (build/validation conditions).
	Retryable     bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentFailure) Reset() {
	*x = DeploymentFailure{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentFailure) ProtoMessage() {}

func (x *DeploymentFailure) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentFailure.ProtoReflect.Descriptor instead.
func (*DeploymentFailure) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentFailure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeploymentFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// DeploymentSlot is one blue-green slot. Both slots are reported whenever the
// app has blue-green state, including the one that is stopped.
type DeploymentSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`                                      // "blue" or "green"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                // "vN"; empty when unknown
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                  // running | starting | replacing | failed | stopped
	Health        string                 `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`                                  // healthy | unhealthy | pending | unknown
	InternalPort  int32                  `protobuf:"varint,5,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"` // 0 when the slot has no live listener
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`                                       // 0 when stopped
	Active        bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`                                 // true for the slot the proxy points at
	StartedAt     int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`          // unix millis; 0 when unknown
	HealthyAt     int64                  `protobuf:"varint,9,opt,name=healthy_at,json=healthyAt,proto3" json:"healthy_at,omitempty"`          // unix millis of the last passed health window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentSlot) Reset() {
	*x = DeploymentSlot{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSlot) ProtoMessage() {}

func (x *DeploymentSlot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSlot.ProtoReflect.Descriptor instead.
func (*DeploymentSlot) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentSlot) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *DeploymentSlot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeploymentSlot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentSlot) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *DeploymentSlot) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *DeploymentSlot) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DeploymentSlot) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DeploymentSlot) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *DeploymentSlot) GetHealthyAt() int64 {
	if x != nil {
		return x.HealthyAt
	}
	return 0
}

// DeploymentReplica is one rolling replica. Replicas are reported in index
// order.
type DeploymentReplica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`        // "replica-0"
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 0-based
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // running | starting | replacing | failed | stopped
	Health        string                 `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"` // healthy | unhealthy | pending | unknown
	InternalPort  int32                  `protobuf:"varint,6,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	Pid           int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	HealthyAt     int64                  `protobuf:"varint,9,opt,name=healthy_at,json=healthyAt,proto3" json:"healthy_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentReplica) Reset() {
	*x = DeploymentReplica{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentReplica) ProtoMessage() {}

func (x *DeploymentReplica) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentReplica.ProtoReflect.Descriptor instead.
func (*DeploymentReplica) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentReplica) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeploymentReplica) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeploymentReplica) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeploymentReplica) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentReplica) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *DeploymentReplica) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *DeploymentReplica) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DeploymentReplica) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *DeploymentReplica) GetHealthyAt() int64 {
	if x != nil {
		return x.HealthyAt
	}
	return 0
}

// DeploymentProxy is the routing state of the Phelix proxy daemon for this
// app. It is only populated from facts the CLI actually has: a successful
// enrol/switch during a deployment, or a live query of the daemon's control
// socket. An absent proxy message means "unknown", NOT "disabled" — the
// backend must not infer routing from application status.
type DeploymentProxy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PublicPort         int32                  `protobuf:"varint,2,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	TargetSlot         string                 `protobuf:"bytes,3,opt,name=target_slot,json=targetSlot,proto3" json:"target_slot,omitempty"` // proxy primary label: slot or "replica-N"
	TargetInternalPort int32                  `protobuf:"varint,4,opt,name=target_internal_port,json=targetInternalPort,proto3" json:"target_internal_port,omitempty"`
	Upstreams          []string               `protobuf:"bytes,5,rep,name=upstreams,proto3" json:"upstreams,omitempty"`                // every active upstream as host:port
	InFlight           int64                  `protobuf:"varint,6,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"` // in-flight requests, when the daemon reports it
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeploymentProxy) Reset() {
	*x = DeploymentProxy{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentProxy) ProtoMessage() {}

func (x *DeploymentProxy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentProxy.ProtoReflect.Descriptor instead.
func (*DeploymentProxy) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *DeploymentProxy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DeploymentProxy) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *DeploymentProxy) GetTargetSlot() string {
	if x != nil {
		return x.TargetSlot
	}
	return ""
}

func (x *DeploymentProxy) GetTargetInternalPort() int32 {
	if x != nil {
		return x.TargetInternalPort
	}
	return 0
}

func (x *DeploymentProxy) GetUpstreams() []string {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

func (x *DeploymentProxy) GetInFlight() int64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

// DeploymentHealth is the deploy-time health-check configuration and outcome,
// taken from the app's persisted health config and the tier actually selected.
// No new metrics are computed for telemetry.
type DeploymentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                                           // auto | http | tcp-only | none
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                           // configured Tier 1 path; empty when none
	Retries       int32                  `protobuf:"varint,3,opt,name=retries,proto3" json:"retries,omitempty"`                                    // consecutive successes required
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`                                   // probe interval, Go duration string
	Timeout       string                 `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`                                     // overall health deadline, Go duration string
	Tier          int32                  `protobuf:"varint,6,opt,name=tier,proto3" json:"tier,omitempty"`                                          // 1..4, the tier selected for this deployment
	TierLabel     string                 `protobuf:"bytes,7,opt,name=tier_label,json=tierLabel,proto3" json:"tier_label,omitempty"`                // human label for tier
	LastHealthyAt int64                  `protobuf:"varint,8,opt,name=last_healthy_at,json=lastHealthyAt,proto3" json:"last_healthy_at,omitempty"` // unix millis the app last passed its window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentHealth) Reset() {
	*x = DeploymentHealth{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentHealth) ProtoMessage() {}

func (x *DeploymentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentHealth.ProtoReflect.Descriptor instead.
func (*DeploymentHealth) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *DeploymentHealth) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DeploymentHealth) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeploymentHealth) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *DeploymentHealth) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *DeploymentHealth) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *DeploymentHealth) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *DeploymentHealth) GetTierLabel() string {
	if x != nil {
		return x.TierLabel
	}
	return ""
}

func (x *DeploymentHealth) GetLastHealthyAt() int64 {
	if x != nil {
		return x.LastHealthyAt
	}
	return 0
}

// DeploymentSnapshot is the complete deployment topology of one app at one
// instant: enough for the backend to reconstruct current state without
// replaying events.
type DeploymentSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // agent_id of the reporting Phelix runtime
	AppId          string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`          // CLI application id
	AppName        string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	DeploymentId   string                 `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`       // last/current deployment operation id
	Strategy       string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`                                   // classic | blue-green | rolling
	Phase          string                 `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`                                         // see DeploymentEvent.phase
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                       // idle | in_progress | succeeded | failed | cancelled
	CurrentVersion string                 `protobuf:"bytes,8,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // version actually serving traffic
	TargetVersion  string                 `protobuf:"bytes,9,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`    // version this deployment is moving to
	ActiveSlot     string                 `protobuf:"bytes,10,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`            // blue-green only
	Slots          []*DeploymentSlot      `protobuf:"bytes,11,rep,name=slots,proto3" json:"slots,omitempty"`
	Replicas       []*DeploymentReplica   `protobuf:"bytes,12,rep,name=replicas,proto3" json:"replicas,omitempty"`
	// Replica counters. desired is what was asked for; current/ready/healthy are
	// observed. They are never derived from desired.
	ReplicasDesired int32              `protobuf:"varint,13,opt,name=replicas_desired,json=replicasDesired,proto3" json:"replicas_desired,omitempty"`
	ReplicasCurrent int32              `protobuf:"varint,14,opt,name=replicas_current,json=replicasCurrent,proto3" json:"replicas_current,omitempty"` // recorded replicas with a live process
	ReplicasReady   int32              `protobuf:"varint,15,opt,name=replicas_ready,json=replicasReady,proto3" json:"replicas_ready,omitempty"`       // live, status=running (in rotation)
	ReplicasHealthy int32              `protobuf:"varint,16,opt,name=replicas_healthy,json=replicasHealthy,proto3" json:"replicas_healthy,omitempty"` // ready AND passed their health window
	Proxy           *DeploymentProxy   `protobuf:"bytes,17,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Health          *DeploymentHealth  `protobuf:"bytes,18,opt,name=health,proto3" json:"health,omitempty"`
	Failure         *DeploymentFailure `protobuf:"bytes,19,opt,name=failure,proto3" json:"failure,omitempty"`                       // last failure of this deployment, if any
	StartedAt       int64              `protobuf:"varint,20,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // unix millis the deployment started
	UpdatedAt       int64              `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix millis this snapshot was produced
	// Backend command correlation id that initiated the topology change.
	RequestId     string `protobuf:"bytes,22,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentSnapshot) Reset() {
	*x = DeploymentSnapshot{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSnapshot) ProtoMessage() {}

func (x *DeploymentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSnapshot.ProtoReflect.Descriptor instead.
func (*DeploymentSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *DeploymentSnapshot) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeploymentSnapshot) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeploymentSnapshot) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DeploymentSnapshot) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentSnapshot) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *DeploymentSnapshot) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DeploymentSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentSnapshot) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *DeploymentSnapshot) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *DeploymentSnapshot) GetActiveSlot() string {
	if x != nil {
		return x.ActiveSlot
	}
	return ""
}

func (x *DeploymentSnapshot) GetSlots() []*DeploymentSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *DeploymentSnapshot) GetReplicas() []*DeploymentReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *DeploymentSnapshot) GetReplicasDesired() int32 {
	if x != nil {
		return x.ReplicasDesired
	}
	return 0
}

func (x *DeploymentSnapshot) GetReplicasCurrent() int32 {
	if x != nil {
		return x.ReplicasCurrent
	}
	return 0
}

func (x *DeploymentSnapshot) GetReplicasReady() int32 {
	if x != nil {
		return x.ReplicasReady
	}
	return 0
}

func (x *DeploymentSnapshot) GetReplicasHealthy() int32 {
	if x != nil {
		return x.ReplicasHealthy
	}
	return 0
}

func (x *DeploymentSnapshot) GetProxy() *DeploymentProxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *DeploymentSnapshot) GetHealth() *DeploymentHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *DeploymentSnapshot) GetFailure() *DeploymentFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *DeploymentSnapshot) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *DeploymentSnapshot) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *DeploymentSnapshot) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// DeploymentEvent is one lifecycle transition of a deployment. All events of
// one deployment share deployment_id; ordering is the order of emission
// (timestamp is monotonic within a deployment).
type DeploymentEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ServerId     string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AppId        string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName      string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	DeploymentId string                 `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// event is the transition name, e.g. deployment.started,
	// deployment.instance_started, deployment.health_check_started,
	// deployment.instance_healthy, deployment.proxy_switching,
	// deployment.proxy_switched, deployment.instance_draining,
	// deployment.instance_stopped, deployment.replica_started,
	// deployment.replica_health_check_started, deployment.replica_healthy,
	// deployment.replica_replaced, deployment.replica_draining,
	// deployment.replica_stopped, deployment.completed, deployment.failed,
	// deployment.cancelled.
	Event    string `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Strategy string `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// phase is the lifecycle phase the deployment is in at emission time:
	// idle | building | starting | health_check | switching | promoting |
	// draining | completed | failed | cancelled.
	Phase          string `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`
	Status         string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CurrentVersion string `protobuf:"bytes,9,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TargetVersion  string `protobuf:"bytes,10,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	// slot / replica identify which instance the event is about. Empty for
	// deployment-wide events.
	Slot            string             `protobuf:"bytes,11,opt,name=slot,proto3" json:"slot,omitempty"`
	ReplicaId       string             `protobuf:"bytes,12,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ReplicaIndex    int32              `protobuf:"varint,13,opt,name=replica_index,json=replicaIndex,proto3" json:"replica_index,omitempty"`
	InternalPort    int32              `protobuf:"varint,14,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	Pid             int32              `protobuf:"varint,15,opt,name=pid,proto3" json:"pid,omitempty"`
	ReplicasDesired int32              `protobuf:"varint,16,opt,name=replicas_desired,json=replicasDesired,proto3" json:"replicas_desired,omitempty"`
	Message         string             `protobuf:"bytes,17,opt,name=message,proto3" json:"message,omitempty"`
	Failure         *DeploymentFailure `protobuf:"bytes,18,opt,name=failure,proto3" json:"failure,omitempty"`
	// snapshot is the full state at emission time, so a backend that missed
	// earlier events can still reconstruct the topology from any single event.
	Snapshot  *DeploymentSnapshot `protobuf:"bytes,19,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Timestamp int64               `protobuf:"varint,20,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// user_id is the session id of the operator that triggered the deployment.
	// The raw session token is never carried in the body — the RPC is
	// authenticated via gRPC metadata.
	UserId string `protobuf:"bytes,21,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Backend command correlation id that initiated this deployment.
	RequestId     string `protobuf:"bytes,22,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentEvent) Reset() {
	*x = DeploymentEvent{}
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentEvent) ProtoMessage() {}

func (x *DeploymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentEvent.ProtoReflect.Descriptor instead.
func (*DeploymentEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_deployment_proto_rawDescGZIP(), []int{6}
}

func (x *DeploymentEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeploymentEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeploymentEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DeploymentEvent) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeploymentEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *DeploymentEvent) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *DeploymentEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DeploymentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeploymentEvent) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *DeploymentEvent) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *DeploymentEvent) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *DeploymentEvent) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *DeploymentEvent) GetReplicaIndex() int32 {
	if x != nil {
		return x.ReplicaIndex
	}
	return 0
}

func (x *DeploymentEvent) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *DeploymentEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DeploymentEvent) GetReplicasDesired() int32 {
	if x != nil {
		return x.ReplicasDesired
	}
	return 0
}

func (x *DeploymentEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentEvent) GetFailure() *DeploymentFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *DeploymentEvent) GetSnapshot() *DeploymentSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *DeploymentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeploymentEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeploymentEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_internal_grpc_proto_deployment_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_deployment_proto_rawDesc = "" +
	"\n" +
	"$internal/grpc/proto/deployment.proto\x12\x06phelix\"_\n" +
	"\x11DeploymentFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xfb\x01\n" +
	"\x0eDeploymentSlot\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\x04 \x01(\tR\x06health\x12#\n" +
	"\rinternal_port\x18\x05 \x01(\x05R\finternalPort\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"healthy_at\x18\t \x01(\x03R\thealthyAt\"\xf8\x01\n" +
	"\x11DeploymentReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\x05 \x01(\tR\x06health\x12#\n" +
	"\rinternal_port\x18\x06 \x01(\x05R\finternalPort\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"healthy_at\x18\t \x01(\x03R\thealthyAt\"\xda\x01\n" +
	"\x0fDeploymentProxy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vpublic_port\x18\x02 \x01(\x05R\n" +
	"publicPort\x12\x1f\n" +
	"\vtarget_slot\x18\x03 \x01(\tR\n" +
	"targetSlot\x120\n" +
	"\x14target_internal_port\x18\x04 \x01(\x05R\x12targetInternalPort\x12\x1c\n" +
	"\tupstreams\x18\x05 \x03(\tR\tupstreams\x12\x1b\n" +
	"\tin_flight\x18\x06 \x01(\x03R\binFlight\"\xe5\x01\n" +
	"\x10DeploymentHealth\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aretries\x18\x03 \x01(\x05R\aretries\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\tR\atimeout\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\x05R\x04tier\x12\x1d\n" +
	"\n" +
	"tier_label\x18\a \x01(\tR\ttierLabel\x12&\n" +
	"\x0flast_healthy_at\x18\b \x01(\x03R\rlastHealthyAt\"\xc3\x06\n" +
	"\x12DeploymentSnapshot\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_version\x18\b \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\t \x01(\tR\rtargetVersion\x12\x1f\n" +
	"\vactive_slot\x18\n" +
	" \x01(\tR\n" +
	"activeSlot\x12,\n" +
	"\x05slots\x18\v \x03(\v2\x16.phelix.DeploymentSlotR\x05slots\x125\n" +
	"\breplicas\x18\f \x03(\v2\x19.phelix.DeploymentReplicaR\breplicas\x12)\n" +
	"\x10replicas_desired\x18\r \x01(\x05R\x0freplicasDesired\x12)\n" +
	"\x10replicas_current\x18\x0e \x01(\x05R\x0freplicasCurrent\x12%\n" +
	"\x0ereplicas_ready\x18\x0f \x01(\x05R\rreplicasReady\x12)\n" +
	"\x10replicas_healthy\x18\x10 \x01(\x05R\x0freplicasHealthy\x12-\n" +
	"\x05proxy\x18\x11 \x01(\v2\x17.phelix.DeploymentProxyR\x05proxy\x120\n" +
	"\x06health\x18\x12 \x01(\v2\x18.phelix.DeploymentHealthR\x06health\x123\n" +
	"\afailure\x18\x13 \x01(\v2\x19.phelix.DeploymentFailureR\afailure\x12\x1d\n" +
	"\n" +
	"started_at\x18\x14 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x16 \x01(\tR\trequestId\"\xcc\x05\n" +
	"\x0fDeploymentEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x1a\n" +
	"\bstrategy\x18\x06 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05phase\x18\a \x01(\tR\x05phase\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_version\x18\t \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\n" +
	" \x01(\tR\rtargetVersion\x12\x12\n" +
	"\x04slot\x18\v \x01(\tR\x04slot\x12\x1d\n" +
	"\n" +
	"replica_id\x18\f \x01(\tR\treplicaId\x12#\n" +
	"\rreplica_index\x18\r \x01(\x05R\freplicaIndex\x12#\n" +
	"\rinternal_port\x18\x0e \x01(\x05R\finternalPort\x12\x10\n" +
	"\x03pid\x18\x0f \x01(\x05R\x03pid\x12)\n" +
	"\x10replicas_desired\x18\x10 \x01(\x05R\x0freplicasDesired\x12\x18\n" +
	"\amessage\x18\x11 \x01(\tR\amessage\x123\n" +
	"\afailure\x18\x12 \x01(\v2\x19.phelix.DeploymentFailureR\afailure\x126\n" +
	"\bsnapshot\x18\x13 \x01(\v2\x1a.phelix.DeploymentSnapshotR\bsnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x14 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x15 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x16 \x01(\tR\trequestIdB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_deployment_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_deployment_proto_rawDescData []byte
)

func file_internal_grpc_proto_deployment_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_deployment_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_deployment_proto_rawDesc), len(file_internal_grpc_proto_deployment_proto_rawDesc)))
	})
	return file_internal_grpc_proto_deployment_proto_rawDescData
}

var file_internal_grpc_proto_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_grpc_proto_deployment_proto_goTypes = []any{
	(*DeploymentFailure)(nil),  // 0: phelix.DeploymentFailure
	(*DeploymentSlot)(nil),     // 1: phelix.DeploymentSlot
	(*DeploymentReplica)(nil),  // 2: phelix.DeploymentReplica
	(*DeploymentProxy)(nil),    // 3: phelix.DeploymentProxy
	(*DeploymentHealth)(nil),   // 4: phelix.DeploymentHealth
	(*DeploymentSnapshot)(nil), // 5: phelix.DeploymentSnapshot
	(*DeploymentEvent)(nil),    // 6: phelix.DeploymentEvent
}
var file_internal_grpc_proto_deployment_proto_depIdxs = []int32{
	1, // 0: phelix.DeploymentSnapshot.slots:type_name -> phelix.DeploymentSlot
	2, // 1: phelix.DeploymentSnapshot.replicas:type_name -> phelix.DeploymentReplica
	3, // 2: phelix.DeploymentSnapshot.proxy:type_name -> phelix.DeploymentProxy
	4, // 3: phelix.DeploymentSnapshot.health:type_name -> phelix.DeploymentHealth
	0, // 4: phelix.DeploymentSnapshot.failure:type_name -> phelix.DeploymentFailure
	0, // 5: phelix.DeploymentEvent.failure:type_name -> phelix.DeploymentFailure
	5, // 6: phelix.DeploymentEvent.snapshot:type_name -> phelix.DeploymentSnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_deployment_proto_init() }
func file_internal_grpc_proto_deployment_proto_init() {
	if File_internal_grpc_proto_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_deployment_proto_rawDesc), len(file_internal_grpc_proto_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_deployment_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_deployment_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_deployment_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_deployment_proto = out.File
	file_internal_grpc_proto_deployment_proto_goTypes = nil
	file_internal_grpc_proto_deployment_proto_depIdxs = nil
}
