// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerToClient is the envelope for messages from backend to CLI.
type ServerToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToClient_HealthCommand
	//	*ServerToClient_Cancel
	//	*ServerToClient_Ping
	Payload       isServerToClient_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToClient) Reset() {
	*x = ServerToClient{}
	mi := &file_internal_grpc_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClient) ProtoMessage() {}

func (x *ServerToClient) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClient.ProtoReflect.Descriptor instead.
func (*ServerToClient) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *ServerToClient) GetPayload() isServerToClient_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToClient) GetHealthCommand() *HealthCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClient_HealthCommand); ok {
			return x.HealthCommand
		}
	}
	return nil
}

func (x *ServerToClient) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClient_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerToClient) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ServerToClient_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerToClient_Payload interface {
	isServerToClient_Payload()
}

type ServerToClient_HealthCommand struct {
	HealthCommand *HealthCommand `protobuf:"bytes,1,opt,name=health_command,json=healthCommand,proto3,oneof"`
}

type ServerToClient_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type ServerToClient_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ServerToClient_HealthCommand) isServerToClient_Payload() {}

func (*ServerToClient_Cancel) isServerToClient_Payload() {}

func (*ServerToClient_Ping) isServerToClient_Payload() {}

// ClientToServer is the envelope for messages from CLI to backend.
type ClientToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientToServer_HealthResult
	//	*ClientToServer_HealthUpdate
	//	*ClientToServer_Pong
	Payload       isClientToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToServer) Reset() {
	*x = ClientToServer{}
	mi := &file_internal_grpc_proto_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServer) ProtoMessage() {}

func (x *ClientToServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServer.ProtoReflect.Descriptor instead.
func (*ClientToServer) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *ClientToServer) GetPayload() isClientToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientToServer) GetHealthResult() *HealthResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServer_HealthResult); ok {
			return x.HealthResult
		}
	}
	return nil
}

func (x *ClientToServer) GetHealthUpdate() *HealthStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServer_HealthUpdate); ok {
			return x.HealthUpdate
		}
	}
	return nil
}

func (x *ClientToServer) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ClientToServer_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isClientToServer_Payload interface {
	isClientToServer_Payload()
}

type ClientToServer_HealthResult struct {
	HealthResult *HealthResult `protobuf:"bytes,1,opt,name=health_result,json=healthResult,proto3,oneof"`
}

type ClientToServer_HealthUpdate struct {
	HealthUpdate *HealthStatusUpdate `protobuf:"bytes,2,opt,name=health_update,json=healthUpdate,proto3,oneof"`
}

type ClientToServer_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*ClientToServer_HealthResult) isClientToServer_Payload() {}

func (*ClientToServer_HealthUpdate) isClientToServer_Payload() {}

func (*ClientToServer_Pong) isClientToServer_Payload() {}

var File_internal_grpc_proto_envelope_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"\"internal/grpc/proto/envelope.proto\x12\x06phelix\x1a internal/grpc/proto/health.proto\x1a\x1einternal/grpc/proto/ping.proto\"\xb0\x01\n" +
	"\x0eServerToClient\x12>\n" +
	"\x0ehealth_command\x18\x01 \x01(\v2\x15.phelix.HealthCommandH\x00R\rhealthCommand\x12/\n" +
	"\x06cancel\x18\x02 \x01(\v2\x15.phelix.CancelRequestH\x00R\x06cancel\x12\"\n" +
	"\x04ping\x18\x03 \x01(\v2\f.phelix.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xbf\x01\n" +
	"\x0eClientToServer\x12;\n" +
	"\rhealth_result\x18\x01 \x01(\v2\x14.phelix.HealthResultH\x00R\fhealthResult\x12A\n" +
	"\rhealth_update\x18\x02 \x01(\v2\x1a.phelix.HealthStatusUpdateH\x00R\fhealthUpdate\x12\"\n" +
	"\x04pong\x18\x03 \x01(\v2\f.phelix.PongH\x00R\x04pongB\t\n" +
	"\apayloadB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_envelope_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_envelope_proto_rawDescData []byte
)

func file_internal_grpc_proto_envelope_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_envelope_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_envelope_proto_rawDesc), len(file_internal_grpc_proto_envelope_proto_rawDesc)))
	})
	return file_internal_grpc_proto_envelope_proto_rawDescData
}

var file_internal_grpc_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_envelope_proto_goTypes = []any{
	(*ServerToClient)(nil),     // 0: phelix.ServerToClient
	(*ClientToServer)(nil),     // 1: phelix.ClientToServer
	(*HealthCommand)(nil),      // 2: phelix.HealthCommand
	(*CancelRequest)(nil),      // 3: phelix.CancelRequest
	(*Ping)(nil),               // 4: phelix.Ping
	(*HealthResult)(nil),       // 5: phelix.HealthResult
	(*HealthStatusUpdate)(nil), // 6: phelix.HealthStatusUpdate
	(*Pong)(nil),               // 7: phelix.Pong
}
var file_internal_grpc_proto_envelope_proto_depIdxs = []int32{
	2, // 0: phelix.ServerToClient.health_command:type_name -> phelix.HealthCommand
	3, // 1: phelix.ServerToClient.cancel:type_name -> phelix.CancelRequest
	4, // 2: phelix.ServerToClient.ping:type_name -> phelix.Ping
	5, // 3: phelix.ClientToServer.health_result:type_name -> phelix.HealthResult
	6, // 4: phelix.ClientToServer.health_update:type_name -> phelix.HealthStatusUpdate
	7, // 5: phelix.ClientToServer.pong:type_name -> phelix.Pong
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_envelope_proto_init() }
func file_internal_grpc_proto_envelope_proto_init() {
	if File_internal_grpc_proto_envelope_proto != nil {
		return
	}
	file_internal_grpc_proto_health_proto_init()
	file_internal_grpc_proto_ping_proto_init()
	file_internal_grpc_proto_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerToClient_HealthCommand)(nil),
		(*ServerToClient_Cancel)(nil),
		(*ServerToClient_Ping)(nil),
	}
	file_internal_grpc_proto_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientToServer_HealthResult)(nil),
		(*ClientToServer_HealthUpdate)(nil),
		(*ClientToServer_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_envelope_proto_rawDesc), len(file_internal_grpc_proto_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_envelope_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_envelope_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_envelope_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_envelope_proto = out.File
	file_internal_grpc_proto_envelope_proto_goTypes = nil
	file_internal_grpc_proto_envelope_proto_depIdxs = nil
}
