// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplicationEvent represents a single application lifecycle event.
type ApplicationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken   string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	AppId          string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName        string                 `protobuf:"bytes,5,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Action         string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp      int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success        bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Pid            int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	DeploymentMode string                 `protobuf:"bytes,11,opt,name=deployment_mode,json=deploymentMode,proto3" json:"deployment_mode,omitempty"`
	Version        string                 `protobuf:"bytes,12,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationEvent) Reset() {
	*x = ApplicationEvent{}
	mi := &file_internal_grpc_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationEvent) ProtoMessage() {}

func (x *ApplicationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationEvent.ProtoReflect.Descriptor instead.
func (*ApplicationEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ApplicationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApplicationEvent) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ApplicationEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ApplicationEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApplicationEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApplicationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ApplicationEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplicationEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ApplicationEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ApplicationEvent) GetDeploymentMode() string {
	if x != nil {
		return x.DeploymentMode
	}
	return ""
}

func (x *ApplicationEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// EventResponse is the backend's response to a reported event.
type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_internal_grpc_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EventAck is a lightweight acknowledgement for streamed events.
type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_internal_grpc_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *EventAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_internal_grpc_proto_events_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_events_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/events.proto\x12\x06phelix\"\xe9\x02\n" +
	"\x10ApplicationEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x05 \x01(\tR\aappName\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12'\n" +
	"\x0fdeployment_mode\x18\v \x01(\tR\x0edeploymentMode\x12\x18\n" +
	"\aversion\x18\f \x01(\tR\aversion\"E\n" +
	"\rEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\bEventAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventIdB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_events_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_events_proto_rawDescData []byte
)

func file_internal_grpc_proto_events_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_events_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_events_proto_rawDesc), len(file_internal_grpc_proto_events_proto_rawDesc)))
	})
	return file_internal_grpc_proto_events_proto_rawDescData
}

var file_internal_grpc_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_proto_events_proto_goTypes = []any{
	(*ApplicationEvent)(nil), // 0: phelix.ApplicationEvent
	(*EventResponse)(nil),    // 1: phelix.EventResponse
	(*EventAck)(nil),         // 2: phelix.EventAck
}
var file_internal_grpc_proto_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_events_proto_init() }
func file_internal_grpc_proto_events_proto_init() {
	if File_internal_grpc_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_events_proto_rawDesc), len(file_internal_grpc_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_events_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_events_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_events_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_events_proto = out.File
	file_internal_grpc_proto_events_proto_goTypes = nil
	file_internal_grpc_proto_events_proto_depIdxs = nil
}
