// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/health.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCommand wraps all health operations into a single command message.
type HealthCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerId  string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*HealthCommand_Set
	//	*HealthCommand_Add
	//	*HealthCommand_Remove
	//	*HealthCommand_List
	//	*HealthCommand_Status
	//	*HealthCommand_Watch
	//	*HealthCommand_DaemonStatus
	//	*HealthCommand_Check
	Command       isHealthCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCommand) Reset() {
	*x = HealthCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCommand) ProtoMessage() {}

func (x *HealthCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCommand.ProtoReflect.Descriptor instead.
func (*HealthCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HealthCommand) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HealthCommand) GetCommand() isHealthCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *HealthCommand) GetSet() *HealthSetCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *HealthCommand) GetAdd() *HealthAddCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Add); ok {
			return x.Add
		}
	}
	return nil
}

func (x *HealthCommand) GetRemove() *HealthRemoveCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *HealthCommand) GetList() *HealthListCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *HealthCommand) GetStatus() *HealthStatusCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *HealthCommand) GetWatch() *HealthWatchCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Watch); ok {
			return x.Watch
		}
	}
	return nil
}

func (x *HealthCommand) GetDaemonStatus() *HealthDaemonStatusCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_DaemonStatus); ok {
			return x.DaemonStatus
		}
	}
	return nil
}

func (x *HealthCommand) GetCheck() *HealthCheckCommand {
	if x != nil {
		if x, ok := x.Command.(*HealthCommand_Check); ok {
			return x.Check
		}
	}
	return nil
}

type isHealthCommand_Command interface {
	isHealthCommand_Command()
}

type HealthCommand_Set struct {
	Set *HealthSetCommand `protobuf:"bytes,10,opt,name=set,proto3,oneof"`
}

type HealthCommand_Add struct {
	Add *HealthAddCommand `protobuf:"bytes,11,opt,name=add,proto3,oneof"`
}

type HealthCommand_Remove struct {
	Remove *HealthRemoveCommand `protobuf:"bytes,12,opt,name=remove,proto3,oneof"`
}

type HealthCommand_List struct {
	List *HealthListCommand `protobuf:"bytes,13,opt,name=list,proto3,oneof"`
}

type HealthCommand_Status struct {
	Status *HealthStatusCommand `protobuf:"bytes,14,opt,name=status,proto3,oneof"`
}

type HealthCommand_Watch struct {
	Watch *HealthWatchCommand `protobuf:"bytes,15,opt,name=watch,proto3,oneof"`
}

type HealthCommand_DaemonStatus struct {
	DaemonStatus *HealthDaemonStatusCommand `protobuf:"bytes,16,opt,name=daemon_status,json=daemonStatus,proto3,oneof"`
}

type HealthCommand_Check struct {
	Check *HealthCheckCommand `protobuf:"bytes,17,opt,name=check,proto3,oneof"`
}

func (*HealthCommand_Set) isHealthCommand_Command() {}

func (*HealthCommand_Add) isHealthCommand_Command() {}

func (*HealthCommand_Remove) isHealthCommand_Command() {}

func (*HealthCommand_List) isHealthCommand_Command() {}

func (*HealthCommand_Status) isHealthCommand_Command() {}

func (*HealthCommand_Watch) isHealthCommand_Command() {}

func (*HealthCommand_DaemonStatus) isHealthCommand_Command() {}

func (*HealthCommand_Check) isHealthCommand_Command() {}

// HealthSetCommand initializes health checks for an application.
type HealthSetCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,6,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	Timeout       string                 `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthSetCommand) Reset() {
	*x = HealthSetCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthSetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthSetCommand) ProtoMessage() {}

func (x *HealthSetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthSetCommand.ProtoReflect.Descriptor instead.
func (*HealthSetCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthSetCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthSetCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthSetCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthSetCommand) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *HealthSetCommand) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthSetCommand) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

func (x *HealthSetCommand) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HealthSetCommand) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// HealthAddCommand adds a named health check endpoint.
type HealthAddCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,7,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	Timeout       string                 `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAddCommand) Reset() {
	*x = HealthAddCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAddCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAddCommand) ProtoMessage() {}

func (x *HealthAddCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAddCommand.ProtoReflect.Descriptor instead.
func (*HealthAddCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{2}
}

func (x *HealthAddCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthAddCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthAddCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthAddCommand) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthAddCommand) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *HealthAddCommand) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthAddCommand) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

func (x *HealthAddCommand) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// HealthRemoveCommand removes a health check endpoint by name.
type HealthRemoveCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRemoveCommand) Reset() {
	*x = HealthRemoveCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRemoveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRemoveCommand) ProtoMessage() {}

func (x *HealthRemoveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRemoveCommand.ProtoReflect.Descriptor instead.
func (*HealthRemoveCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{3}
}

func (x *HealthRemoveCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthRemoveCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthRemoveCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HealthListCommand lists all configured endpoints for an application.
type HealthListCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthListCommand) Reset() {
	*x = HealthListCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthListCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthListCommand) ProtoMessage() {}

func (x *HealthListCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthListCommand.ProtoReflect.Descriptor instead.
func (*HealthListCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{4}
}

func (x *HealthListCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthListCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// HealthStatusCommand returns the current health status of an application.
type HealthStatusCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusCommand) Reset() {
	*x = HealthStatusCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusCommand) ProtoMessage() {}

func (x *HealthStatusCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusCommand.ProtoReflect.Descriptor instead.
func (*HealthStatusCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatusCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthStatusCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// HealthWatchCommand starts streaming continuous health updates.
type HealthWatchCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthWatchCommand) Reset() {
	*x = HealthWatchCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthWatchCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthWatchCommand) ProtoMessage() {}

func (x *HealthWatchCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthWatchCommand.ProtoReflect.Descriptor instead.
func (*HealthWatchCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{6}
}

func (x *HealthWatchCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthWatchCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// HealthDaemonStatusCommand returns the daemon status.
type HealthDaemonStatusCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthDaemonStatusCommand) Reset() {
	*x = HealthDaemonStatusCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDaemonStatusCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDaemonStatusCommand) ProtoMessage() {}

func (x *HealthDaemonStatusCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDaemonStatusCommand.ProtoReflect.Descriptor instead.
func (*HealthDaemonStatusCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{7}
}

// HealthCheckCommand performs a one-shot health check on a specific endpoint.
type HealthCheckCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Timeout       string                 `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,5,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckCommand) Reset() {
	*x = HealthCheckCommand{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckCommand) ProtoMessage() {}

func (x *HealthCheckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckCommand.ProtoReflect.Descriptor instead.
func (*HealthCheckCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckCommand) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthCheckCommand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthCheckCommand) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthCheckCommand) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HealthCheckCommand) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

// HealthSetConfigRequest is sent by the CLI to initialize health checks for an app.
type HealthSetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,6,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	Timeout       string                 `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthSetConfigRequest) Reset() {
	*x = HealthSetConfigRequest{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthSetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthSetConfigRequest) ProtoMessage() {}

func (x *HealthSetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthSetConfigRequest.ProtoReflect.Descriptor instead.
func (*HealthSetConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{9}
}

func (x *HealthSetConfigRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthSetConfigRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthSetConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthSetConfigRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *HealthSetConfigRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthSetConfigRequest) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

func (x *HealthSetConfigRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HealthSetConfigRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

// HealthAddEndpointRequest is sent by the CLI to add a health check endpoint.
type HealthAddEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,7,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	Timeout       string                 `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAddEndpointRequest) Reset() {
	*x = HealthAddEndpointRequest{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAddEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAddEndpointRequest) ProtoMessage() {}

func (x *HealthAddEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAddEndpointRequest.ProtoReflect.Descriptor instead.
func (*HealthAddEndpointRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{10}
}

func (x *HealthAddEndpointRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthAddEndpointRequest) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

func (x *HealthAddEndpointRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// HealthRemoveEndpointRequest is sent by the CLI to remove a health check endpoint.
type HealthRemoveEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRemoveEndpointRequest) Reset() {
	*x = HealthRemoveEndpointRequest{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRemoveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRemoveEndpointRequest) ProtoMessage() {}

func (x *HealthRemoveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRemoveEndpointRequest.ProtoReflect.Descriptor instead.
func (*HealthRemoveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{11}
}

func (x *HealthRemoveEndpointRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthRemoveEndpointRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthRemoveEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HealthConfigResponse is the response to a CLI-initiated health config RPC.
type HealthConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthConfigResponse) Reset() {
	*x = HealthConfigResponse{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthConfigResponse) ProtoMessage() {}

func (x *HealthConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthConfigResponse.ProtoReflect.Descriptor instead.
func (*HealthConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{12}
}

func (x *HealthConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReportHealthResultRequest is sent by the daemon to report a health check result.
type ReportHealthResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	EndpointName  string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,8,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthResultRequest) Reset() {
	*x = ReportHealthResultRequest{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthResultRequest) ProtoMessage() {}

func (x *ReportHealthResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthResultRequest.ProtoReflect.Descriptor instead.
func (*ReportHealthResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{13}
}

func (x *ReportHealthResultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReportHealthResultRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ReportHealthResultRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *ReportHealthResultRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReportHealthResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportHealthResultRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ReportHealthResultRequest) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ReportHealthResultRequest) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *ReportHealthResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReportHealthResultResponse is the response to a health result report.
type ReportHealthResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthResultResponse) Reset() {
	*x = ReportHealthResultResponse{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthResultResponse) ProtoMessage() {}

func (x *ReportHealthResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthResultResponse.ProtoReflect.Descriptor instead.
func (*ReportHealthResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{14}
}

func (x *ReportHealthResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportHealthResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReportAutoRestartRequest is sent by the daemon to report an auto-restart event.
type ReportAutoRestartRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName            string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ExitCode           int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	BackoffNextSeconds int32                  `protobuf:"varint,5,opt,name=backoff_next_seconds,json=backoffNextSeconds,proto3" json:"backoff_next_seconds,omitempty"`
	RestartedAt        int64                  `protobuf:"varint,6,opt,name=restarted_at,json=restartedAt,proto3" json:"restarted_at,omitempty"`
	CrashCount_24H     int32                  `protobuf:"varint,7,opt,name=crash_count_24h,json=crashCount24h,proto3" json:"crash_count_24h,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportAutoRestartRequest) Reset() {
	*x = ReportAutoRestartRequest{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAutoRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAutoRestartRequest) ProtoMessage() {}

func (x *ReportAutoRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAutoRestartRequest.ProtoReflect.Descriptor instead.
func (*ReportAutoRestartRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{15}
}

func (x *ReportAutoRestartRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReportAutoRestartRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ReportAutoRestartRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportAutoRestartRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportAutoRestartRequest) GetBackoffNextSeconds() int32 {
	if x != nil {
		return x.BackoffNextSeconds
	}
	return 0
}

func (x *ReportAutoRestartRequest) GetRestartedAt() int64 {
	if x != nil {
		return x.RestartedAt
	}
	return 0
}

func (x *ReportAutoRestartRequest) GetCrashCount_24H() int32 {
	if x != nil {
		return x.CrashCount_24H
	}
	return 0
}

// ReportAutoRestartResponse is the response to an auto-restart report.
type ReportAutoRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAutoRestartResponse) Reset() {
	*x = ReportAutoRestartResponse{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAutoRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAutoRestartResponse) ProtoMessage() {}

func (x *ReportAutoRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAutoRestartResponse.ProtoReflect.Descriptor instead.
func (*ReportAutoRestartResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{16}
}

func (x *ReportAutoRestartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportAutoRestartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthResult is the result of a health command execution.
type HealthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	ExecutionTime int64                  `protobuf:"varint,7,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Diagnostics   string                 `protobuf:"bytes,11,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// Result payload varies by command type
	//
	// Types that are valid to be assigned to Result:
	//
	//	*HealthResult_SetResult
	//	*HealthResult_ListResult
	//	*HealthResult_StatusResult
	//	*HealthResult_DaemonStatusResult
	//	*HealthResult_CheckResult
	Result        isHealthResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResult) Reset() {
	*x = HealthResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResult) ProtoMessage() {}

func (x *HealthResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResult.ProtoReflect.Descriptor instead.
func (*HealthResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{17}
}

func (x *HealthResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HealthResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HealthResult) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthResult) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HealthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthResult) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

func (x *HealthResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthResult) GetDiagnostics() string {
	if x != nil {
		return x.Diagnostics
	}
	return ""
}

func (x *HealthResult) GetResult() isHealthResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HealthResult) GetSetResult() *HealthResultSetResult {
	if x != nil {
		if x, ok := x.Result.(*HealthResult_SetResult); ok {
			return x.SetResult
		}
	}
	return nil
}

func (x *HealthResult) GetListResult() *HealthResultListResult {
	if x != nil {
		if x, ok := x.Result.(*HealthResult_ListResult); ok {
			return x.ListResult
		}
	}
	return nil
}

func (x *HealthResult) GetStatusResult() *HealthResultStatusResult {
	if x != nil {
		if x, ok := x.Result.(*HealthResult_StatusResult); ok {
			return x.StatusResult
		}
	}
	return nil
}

func (x *HealthResult) GetDaemonStatusResult() *HealthResultDaemonStatusResult {
	if x != nil {
		if x, ok := x.Result.(*HealthResult_DaemonStatusResult); ok {
			return x.DaemonStatusResult
		}
	}
	return nil
}

func (x *HealthResult) GetCheckResult() *HealthResultCheckResult {
	if x != nil {
		if x, ok := x.Result.(*HealthResult_CheckResult); ok {
			return x.CheckResult
		}
	}
	return nil
}

type isHealthResult_Result interface {
	isHealthResult_Result()
}

type HealthResult_SetResult struct {
	SetResult *HealthResultSetResult `protobuf:"bytes,20,opt,name=set_result,json=setResult,proto3,oneof"`
}

type HealthResult_ListResult struct {
	ListResult *HealthResultListResult `protobuf:"bytes,21,opt,name=list_result,json=listResult,proto3,oneof"`
}

type HealthResult_StatusResult struct {
	StatusResult *HealthResultStatusResult `protobuf:"bytes,22,opt,name=status_result,json=statusResult,proto3,oneof"`
}

type HealthResult_DaemonStatusResult struct {
	DaemonStatusResult *HealthResultDaemonStatusResult `protobuf:"bytes,23,opt,name=daemon_status_result,json=daemonStatusResult,proto3,oneof"`
}

type HealthResult_CheckResult struct {
	CheckResult *HealthResultCheckResult `protobuf:"bytes,24,opt,name=check_result,json=checkResult,proto3,oneof"`
}

func (*HealthResult_SetResult) isHealthResult_Result() {}

func (*HealthResult_ListResult) isHealthResult_Result() {}

func (*HealthResult_StatusResult) isHealthResult_Result() {}

func (*HealthResult_DaemonStatusResult) isHealthResult_Result() {}

func (*HealthResult_CheckResult) isHealthResult_Result() {}

// HealthResultSetResult contains the result of a set operation.
type HealthResultSetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResultSetResult) Reset() {
	*x = HealthResultSetResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResultSetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResultSetResult) ProtoMessage() {}

func (x *HealthResultSetResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResultSetResult.ProtoReflect.Descriptor instead.
func (*HealthResultSetResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{18}
}

// HealthResultListResult contains endpoint configurations.
type HealthResultListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointConfig      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	DeployTier    *DeployTierConfigProto `protobuf:"bytes,2,opt,name=deploy_tier,json=deployTier,proto3" json:"deploy_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResultListResult) Reset() {
	*x = HealthResultListResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResultListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResultListResult) ProtoMessage() {}

func (x *HealthResultListResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResultListResult.ProtoReflect.Descriptor instead.
func (*HealthResultListResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{19}
}

func (x *HealthResultListResult) GetEndpoints() []*EndpointConfig {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *HealthResultListResult) GetDeployTier() *DeployTierConfigProto {
	if x != nil {
		return x.DeployTier
	}
	return nil
}

// HealthResultStatusResult contains endpoint health statuses.
type HealthResultStatusResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Endpoints     []*EndpointHealthStatus `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResultStatusResult) Reset() {
	*x = HealthResultStatusResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResultStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResultStatusResult) ProtoMessage() {}

func (x *HealthResultStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResultStatusResult.ProtoReflect.Descriptor instead.
func (*HealthResultStatusResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResultStatusResult) GetEndpoints() []*EndpointHealthStatus {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// HealthResultDaemonStatusResult contains daemon status information.
type HealthResultDaemonStatusResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DaemonRunning      bool                   `protobuf:"varint,1,opt,name=daemon_running,json=daemonRunning,proto3" json:"daemon_running,omitempty"`
	TotalApps          int32                  `protobuf:"varint,2,opt,name=total_apps,json=totalApps,proto3" json:"total_apps,omitempty"`
	TotalEndpoints     int32                  `protobuf:"varint,3,opt,name=total_endpoints,json=totalEndpoints,proto3" json:"total_endpoints,omitempty"`
	HealthyEndpoints   int32                  `protobuf:"varint,4,opt,name=healthy_endpoints,json=healthyEndpoints,proto3" json:"healthy_endpoints,omitempty"`
	UnhealthyEndpoints int32                  `protobuf:"varint,5,opt,name=unhealthy_endpoints,json=unhealthyEndpoints,proto3" json:"unhealthy_endpoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthResultDaemonStatusResult) Reset() {
	*x = HealthResultDaemonStatusResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResultDaemonStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResultDaemonStatusResult) ProtoMessage() {}

func (x *HealthResultDaemonStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResultDaemonStatusResult.ProtoReflect.Descriptor instead.
func (*HealthResultDaemonStatusResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResultDaemonStatusResult) GetDaemonRunning() bool {
	if x != nil {
		return x.DaemonRunning
	}
	return false
}

func (x *HealthResultDaemonStatusResult) GetTotalApps() int32 {
	if x != nil {
		return x.TotalApps
	}
	return 0
}

func (x *HealthResultDaemonStatusResult) GetTotalEndpoints() int32 {
	if x != nil {
		return x.TotalEndpoints
	}
	return 0
}

func (x *HealthResultDaemonStatusResult) GetHealthyEndpoints() int32 {
	if x != nil {
		return x.HealthyEndpoints
	}
	return 0
}

func (x *HealthResultDaemonStatusResult) GetUnhealthyEndpoints() int32 {
	if x != nil {
		return x.UnhealthyEndpoints
	}
	return 0
}

// HealthResultCheckResult contains a one-shot health check result.
type HealthResultCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	RawOutput     string                 `protobuf:"bytes,6,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResultCheckResult) Reset() {
	*x = HealthResultCheckResult{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResultCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResultCheckResult) ProtoMessage() {}

func (x *HealthResultCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResultCheckResult.ProtoReflect.Descriptor instead.
func (*HealthResultCheckResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{22}
}

func (x *HealthResultCheckResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthResultCheckResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResultCheckResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HealthResultCheckResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthResultCheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthResultCheckResult) GetRawOutput() string {
	if x != nil {
		return x.RawOutput
	}
	return ""
}

// EndpointConfig represents a single health check endpoint configuration.
type EndpointConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	ExpectedCodes string                 `protobuf:"bytes,5,opt,name=expected_codes,json=expectedCodes,proto3" json:"expected_codes,omitempty"`
	Timeout       string                 `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig) Reset() {
	*x = EndpointConfig{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig) ProtoMessage() {}

func (x *EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig.ProtoReflect.Descriptor instead.
func (*EndpointConfig) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{23}
}

func (x *EndpointConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EndpointConfig) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *EndpointConfig) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *EndpointConfig) GetExpectedCodes() string {
	if x != nil {
		return x.ExpectedCodes
	}
	return ""
}

func (x *EndpointConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// DeployTierConfigProto represents deploy-tier health configuration.
type DeployTierConfigProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Retries       int32                  `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	Timeout       string                 `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployTierConfigProto) Reset() {
	*x = DeployTierConfigProto{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployTierConfigProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployTierConfigProto) ProtoMessage() {}

func (x *DeployTierConfigProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployTierConfigProto.ProtoReflect.Descriptor instead.
func (*DeployTierConfigProto) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{24}
}

func (x *DeployTierConfigProto) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DeployTierConfigProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeployTierConfigProto) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *DeployTierConfigProto) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *DeployTierConfigProto) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// EndpointHealthStatus represents the health status of a single endpoint.
type EndpointHealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,6,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointHealthStatus) Reset() {
	*x = EndpointHealthStatus{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointHealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointHealthStatus) ProtoMessage() {}

func (x *EndpointHealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointHealthStatus.ProtoReflect.Descriptor instead.
func (*EndpointHealthStatus) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{25}
}

func (x *EndpointHealthStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointHealthStatus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EndpointHealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EndpointHealthStatus) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EndpointHealthStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EndpointHealthStatus) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *EndpointHealthStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthStatusUpdate is streamed during HealthWatch operations.
type HealthStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	EndpointName  string                 `protobuf:"bytes,5,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,10,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,12,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusUpdate) Reset() {
	*x = HealthStatusUpdate{}
	mi := &file_internal_grpc_proto_health_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusUpdate) ProtoMessage() {}

func (x *HealthStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_health_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusUpdate.ProtoReflect.Descriptor instead.
func (*HealthStatusUpdate) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_health_proto_rawDescGZIP(), []int{26}
}

func (x *HealthStatusUpdate) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HealthStatusUpdate) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HealthStatusUpdate) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HealthStatusUpdate) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthStatusUpdate) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *HealthStatusUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatusUpdate) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HealthStatusUpdate) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthStatusUpdate) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *HealthStatusUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthStatusUpdate) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

var File_internal_grpc_proto_health_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_health_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/health.proto\x12\x06phelix\"\x83\x04\n" +
	"\rHealthCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12,\n" +
	"\x03set\x18\n" +
	" \x01(\v2\x18.phelix.HealthSetCommandH\x00R\x03set\x12,\n" +
	"\x03add\x18\v \x01(\v2\x18.phelix.HealthAddCommandH\x00R\x03add\x125\n" +
	"\x06remove\x18\f \x01(\v2\x1b.phelix.HealthRemoveCommandH\x00R\x06remove\x12/\n" +
	"\x04list\x18\r \x01(\v2\x19.phelix.HealthListCommandH\x00R\x04list\x125\n" +
	"\x06status\x18\x0e \x01(\v2\x1b.phelix.HealthStatusCommandH\x00R\x06status\x122\n" +
	"\x05watch\x18\x0f \x01(\v2\x1a.phelix.HealthWatchCommandH\x00R\x05watch\x12H\n" +
	"\rdaemon_status\x18\x10 \x01(\v2!.phelix.HealthDaemonStatusCommandH\x00R\fdaemonStatus\x122\n" +
	"\x05check\x18\x11 \x01(\v2\x1a.phelix.HealthCheckCommandH\x00R\x05checkB\t\n" +
	"\acommand\"\xe3\x01\n" +
	"\x10HealthSetCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12%\n" +
	"\x0eexpected_codes\x18\x06 \x01(\tR\rexpectedCodes\x12\x18\n" +
	"\atimeout\x18\a \x01(\tR\atimeout\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\"\xe1\x01\n" +
	"\x10HealthAddCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries\x12%\n" +
	"\x0eexpected_codes\x18\a \x01(\tR\rexpectedCodes\x12\x18\n" +
	"\atimeout\x18\b \x01(\tR\atimeout\"[\n" +
	"\x13HealthRemoveCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"E\n" +
	"\x11HealthListCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"G\n" +
	"\x13HealthStatusCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"F\n" +
	"\x12HealthWatchCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"\x1b\n" +
	"\x19HealthDaemonStatusCommand\"\x99\x01\n" +
	"\x12HealthCheckCommand\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\tR\atimeout\x12%\n" +
	"\x0eexpected_codes\x18\x05 \x01(\tR\rexpectedCodes\"\xe9\x01\n" +
	"\x16HealthSetConfigRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12%\n" +
	"\x0eexpected_codes\x18\x06 \x01(\tR\rexpectedCodes\x12\x18\n" +
	"\atimeout\x18\a \x01(\tR\atimeout\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\"\xe9\x01\n" +
	"\x18HealthAddEndpointRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries\x12%\n" +
	"\x0eexpected_codes\x18\a \x01(\tR\rexpectedCodes\x12\x18\n" +
	"\atimeout\x18\b \x01(\tR\atimeout\"c\n" +
	"\x1bHealthRemoveEndpointRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"`\n" +
	"\x14HealthConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x02\n" +
	"\x19ReportHealthResultRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"checked_at\x18\b \x01(\x03R\tcheckedAt\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"L\n" +
	"\x1aReportHealthResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xfe\x01\n" +
	"\x18ReportAutoRestartRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x120\n" +
	"\x14backoff_next_seconds\x18\x05 \x01(\x05R\x12backoffNextSeconds\x12!\n" +
	"\frestarted_at\x18\x06 \x01(\x03R\vrestartedAt\x12&\n" +
	"\x0fcrash_count_24h\x18\a \x01(\x05R\rcrashCount24h\"K\n" +
	"\x19ReportAutoRestartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xbf\x05\n" +
	"\fHealthResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12%\n" +
	"\x0eexecution_time\x18\a \x01(\x03R\rexecutionTime\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12 \n" +
	"\vdiagnostics\x18\v \x01(\tR\vdiagnostics\x12>\n" +
	"\n" +
	"set_result\x18\x14 \x01(\v2\x1d.phelix.HealthResultSetResultH\x00R\tsetResult\x12A\n" +
	"\vlist_result\x18\x15 \x01(\v2\x1e.phelix.HealthResultListResultH\x00R\n" +
	"listResult\x12G\n" +
	"\rstatus_result\x18\x16 \x01(\v2 .phelix.HealthResultStatusResultH\x00R\fstatusResult\x12Z\n" +
	"\x14daemon_status_result\x18\x17 \x01(\v2&.phelix.HealthResultDaemonStatusResultH\x00R\x12daemonStatusResult\x12D\n" +
	"\fcheck_result\x18\x18 \x01(\v2\x1f.phelix.HealthResultCheckResultH\x00R\vcheckResultB\b\n" +
	"\x06result\"\x17\n" +
	"\x15HealthResultSetResult\"\x8e\x01\n" +
	"\x16HealthResultListResult\x124\n" +
	"\tendpoints\x18\x01 \x03(\v2\x16.phelix.EndpointConfigR\tendpoints\x12>\n" +
	"\vdeploy_tier\x18\x02 \x01(\v2\x1d.phelix.DeployTierConfigProtoR\n" +
	"deployTier\"V\n" +
	"\x18HealthResultStatusResult\x12:\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1c.phelix.EndpointHealthStatusR\tendpoints\"\xed\x01\n" +
	"\x1eHealthResultDaemonStatusResult\x12%\n" +
	"\x0edaemon_running\x18\x01 \x01(\bR\rdaemonRunning\x12\x1d\n" +
	"\n" +
	"total_apps\x18\x02 \x01(\x05R\ttotalApps\x12'\n" +
	"\x0ftotal_endpoints\x18\x03 \x01(\x05R\x0etotalEndpoints\x12+\n" +
	"\x11healthy_endpoints\x18\x04 \x01(\x05R\x10healthyEndpoints\x12/\n" +
	"\x13unhealthy_endpoints\x18\x05 \x01(\x05R\x12unhealthyEndpoints\"\xb8\x01\n" +
	"\x17HealthResultCheckResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"raw_output\x18\x06 \x01(\tR\trawOutput\"\xad\x01\n" +
	"\x0eEndpointConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x04 \x01(\x05R\aretries\x12%\n" +
	"\x0eexpected_codes\x18\x05 \x01(\tR\rexpectedCodes\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\tR\atimeout\"\x8f\x01\n" +
	"\x15DeployTierConfigProto\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x12\x18\n" +
	"\aretries\x18\x04 \x01(\x05R\aretries\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\tR\atimeout\"\xc9\x01\n" +
	"\x14EndpointHealthStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x06 \x01(\x03R\tcheckedAt\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xe5\x02\n" +
	"\x12HealthStatusUpdate\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12#\n" +
	"\rendpoint_name\x18\x05 \x01(\tR\fendpointName\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"checked_at\x18\n" +
	" \x01(\x03R\tcheckedAt\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\f \x01(\bR\tisHealthyB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_health_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_health_proto_rawDescData []byte
)

func file_internal_grpc_proto_health_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_health_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_health_proto_rawDesc), len(file_internal_grpc_proto_health_proto_rawDesc)))
	})
	return file_internal_grpc_proto_health_proto_rawDescData
}

var file_internal_grpc_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_internal_grpc_proto_health_proto_goTypes = []any{
	(*HealthCommand)(nil),                  // 0: phelix.HealthCommand
	(*HealthSetCommand)(nil),               // 1: phelix.HealthSetCommand
	(*HealthAddCommand)(nil),               // 2: phelix.HealthAddCommand
	(*HealthRemoveCommand)(nil),            // 3: phelix.HealthRemoveCommand
	(*HealthListCommand)(nil),              // 4: phelix.HealthListCommand
	(*HealthStatusCommand)(nil),            // 5: phelix.HealthStatusCommand
	(*HealthWatchCommand)(nil),             // 6: phelix.HealthWatchCommand
	(*HealthDaemonStatusCommand)(nil),      // 7: phelix.HealthDaemonStatusCommand
	(*HealthCheckCommand)(nil),             // 8: phelix.HealthCheckCommand
	(*HealthSetConfigRequest)(nil),         // 9: phelix.HealthSetConfigRequest
	(*HealthAddEndpointRequest)(nil),       // 10: phelix.HealthAddEndpointRequest
	(*HealthRemoveEndpointRequest)(nil),    // 11: phelix.HealthRemoveEndpointRequest
	(*HealthConfigResponse)(nil),           // 12: phelix.HealthConfigResponse
	(*ReportHealthResultRequest)(nil),      // 13: phelix.ReportHealthResultRequest
	(*ReportHealthResultResponse)(nil),     // 14: phelix.ReportHealthResultResponse
	(*ReportAutoRestartRequest)(nil),       // 15: phelix.ReportAutoRestartRequest
	(*ReportAutoRestartResponse)(nil),      // 16: phelix.ReportAutoRestartResponse
	(*HealthResult)(nil),                   // 17: phelix.HealthResult
	(*HealthResultSetResult)(nil),          // 18: phelix.HealthResultSetResult
	(*HealthResultListResult)(nil),         // 19: phelix.HealthResultListResult
	(*HealthResultStatusResult)(nil),       // 20: phelix.HealthResultStatusResult
	(*HealthResultDaemonStatusResult)(nil), // 21: phelix.HealthResultDaemonStatusResult
	(*HealthResultCheckResult)(nil),        // 22: phelix.HealthResultCheckResult
	(*EndpointConfig)(nil),                 // 23: phelix.EndpointConfig
	(*DeployTierConfigProto)(nil),          // 24: phelix.DeployTierConfigProto
	(*EndpointHealthStatus)(nil),           // 25: phelix.EndpointHealthStatus
	(*HealthStatusUpdate)(nil),             // 26: phelix.HealthStatusUpdate
}
var file_internal_grpc_proto_health_proto_depIdxs = []int32{
	1,  // 0: phelix.HealthCommand.set:type_name -> phelix.HealthSetCommand
	2,  // 1: phelix.HealthCommand.add:type_name -> phelix.HealthAddCommand
	3,  // 2: phelix.HealthCommand.remove:type_name -> phelix.HealthRemoveCommand
	4,  // 3: phelix.HealthCommand.list:type_name -> phelix.HealthListCommand
	5,  // 4: phelix.HealthCommand.status:type_name -> phelix.HealthStatusCommand
	6,  // 5: phelix.HealthCommand.watch:type_name -> phelix.HealthWatchCommand
	7,  // 6: phelix.HealthCommand.daemon_status:type_name -> phelix.HealthDaemonStatusCommand
	8,  // 7: phelix.HealthCommand.check:type_name -> phelix.HealthCheckCommand
	18, // 8: phelix.HealthResult.set_result:type_name -> phelix.HealthResultSetResult
	19, // 9: phelix.HealthResult.list_result:type_name -> phelix.HealthResultListResult
	20, // 10: phelix.HealthResult.status_result:type_name -> phelix.HealthResultStatusResult
	21, // 11: phelix.HealthResult.daemon_status_result:type_name -> phelix.HealthResultDaemonStatusResult
	22, // 12: phelix.HealthResult.check_result:type_name -> phelix.HealthResultCheckResult
	23, // 13: phelix.HealthResultListResult.endpoints:type_name -> phelix.EndpointConfig
	24, // 14: phelix.HealthResultListResult.deploy_tier:type_name -> phelix.DeployTierConfigProto
	25, // 15: phelix.HealthResultStatusResult.endpoints:type_name -> phelix.EndpointHealthStatus
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_health_proto_init() }
func file_internal_grpc_proto_health_proto_init() {
	if File_internal_grpc_proto_health_proto != nil {
		return
	}
	file_internal_grpc_proto_health_proto_msgTypes[0].OneofWrappers = []any{
		(*HealthCommand_Set)(nil),
		(*HealthCommand_Add)(nil),
		(*HealthCommand_Remove)(nil),
		(*HealthCommand_List)(nil),
		(*HealthCommand_Status)(nil),
		(*HealthCommand_Watch)(nil),
		(*HealthCommand_DaemonStatus)(nil),
		(*HealthCommand_Check)(nil),
	}
	file_internal_grpc_proto_health_proto_msgTypes[17].OneofWrappers = []any{
		(*HealthResult_SetResult)(nil),
		(*HealthResult_ListResult)(nil),
		(*HealthResult_StatusResult)(nil),
		(*HealthResult_DaemonStatusResult)(nil),
		(*HealthResult_CheckResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_health_proto_rawDesc), len(file_internal_grpc_proto_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_health_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_health_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_health_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_health_proto = out.File
	file_internal_grpc_proto_health_proto_goTypes = nil
	file_internal_grpc_proto_health_proto_depIdxs = nil
}
