// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/matrix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MatrixOptions carries the matrix build options of a matrix_* command. It
// mirrors the local CLI flags: every field is optional, and empty/zero means
// "not specified" so the agent's own convergence applies (payload > the
// project's phelix.yaml matrix profile > engine default; lists replace, never
// merge — identical to matrix.Resolve). Include/exclude rules have no payload
// representation: like the CLI, they come from the phelix.yaml profile on the
// agent and are reported back in the run's configuration snapshot.
type MatrixOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimension flags. go_versions and rust_versions are mutually exclusive.
	GoVersions   []string `protobuf:"bytes,1,rep,name=go_versions,json=goVersions,proto3" json:"go_versions,omitempty"`
	RustVersions []string `protobuf:"bytes,2,rep,name=rust_versions,json=rustVersions,proto3" json:"rust_versions,omitempty"`
	Platforms    []string `protobuf:"bytes,3,rep,name=platforms,proto3" json:"platforms,omitempty"`
	// Execution policy. concurrency 0 = engine default (3); retries 0 = no
	// automatic retries. Negative values are rejected.
	Concurrency int32 `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Retries     int32 `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	// build_args are passed to the underlying build tool, exactly like the
	// local --build-arg flag. For matrix_dockerize they must be KEY=VALUE
	// pairs (docker build --build-arg semantics); for native builds they are
	// passed through verbatim.
	BuildArgs []string `protobuf:"bytes,6,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty"`
	// tag is the optional version tag: the local --tag for matrix_build (stored
	// with the recorded version), the image tag for matrix_dockerize.
	Tag string `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	// Docker-matrix options (matrix_dockerize only; ignored otherwise).
	Registry     string `protobuf:"bytes,8,opt,name=registry,proto3" json:"registry,omitempty"`                                 // image registry prefix for tags/pushes
	Push         bool   `protobuf:"varint,9,opt,name=push,proto3" json:"push,omitempty"`                                        // push images after building (fail-closed)
	PushPartial  bool   `protobuf:"varint,10,opt,name=push_partial,json=pushPartial,proto3" json:"push_partial,omitempty"`      // push even when some combinations failed
	MultiArchTag bool   `protobuf:"varint,11,opt,name=multi_arch_tag,json=multiArchTag,proto3" json:"multi_arch_tag,omitempty"` // assemble per-version multi-arch manifest lists
	// matrix_list only: maximum number of run summaries to return
	// (0 = default 20, negative rejected, hard cap 100).
	ListLimit     int32 `protobuf:"varint,12,opt,name=list_limit,json=listLimit,proto3" json:"list_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixOptions) Reset() {
	*x = MatrixOptions{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixOptions) ProtoMessage() {}

func (x *MatrixOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixOptions.ProtoReflect.Descriptor instead.
func (*MatrixOptions) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{0}
}

func (x *MatrixOptions) GetGoVersions() []string {
	if x != nil {
		return x.GoVersions
	}
	return nil
}

func (x *MatrixOptions) GetRustVersions() []string {
	if x != nil {
		return x.RustVersions
	}
	return nil
}

func (x *MatrixOptions) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *MatrixOptions) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *MatrixOptions) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *MatrixOptions) GetBuildArgs() []string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *MatrixOptions) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MatrixOptions) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *MatrixOptions) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

func (x *MatrixOptions) GetPushPartial() bool {
	if x != nil {
		return x.PushPartial
	}
	return false
}

func (x *MatrixOptions) GetMultiArchTag() bool {
	if x != nil {
		return x.MultiArchTag
	}
	return false
}

func (x *MatrixOptions) GetListLimit() int32 {
	if x != nil {
		return x.ListLimit
	}
	return 0
}

// MatrixRule is one include/exclude rule of a run's configuration snapshot —
// the agent-side matrix.Rule. dimensions is a partial constraint set over the
// dimension names lang/version/os/arch/variant; metadata (include rules only)
// carries attributes merged into matched combinations.
type MatrixRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dimensions    map[string]string      `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixRule) Reset() {
	*x = MatrixRule{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRule) ProtoMessage() {}

func (x *MatrixRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRule.ProtoReflect.Descriptor instead.
func (*MatrixRule) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{1}
}

func (x *MatrixRule) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *MatrixRule) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MatrixRunConfig is the configuration snapshot a run executed with — captured
// at run start, never re-read from phelix.yaml (the agent's matrix.RunConfig).
type MatrixRunConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Language      string                  `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`   // "go" | "rust"
	Versions      []string                `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`   // toolchain versions
	Platforms     []string                `protobuf:"bytes,3,rep,name=platforms,proto3" json:"platforms,omitempty"` // "os/arch[/variant]" entries
	Concurrency   int32                   `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Include       []*MatrixRule           `protobuf:"bytes,5,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []*MatrixRule           `protobuf:"bytes,6,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Retries       int32                   `protobuf:"varint,7,opt,name=retries,proto3" json:"retries,omitempty"`
	BuildArgs     []string                `protobuf:"bytes,8,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty"`
	Sources       *MatrixRunConfigSources `protobuf:"bytes,9,opt,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixRunConfig) Reset() {
	*x = MatrixRunConfig{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixRunConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRunConfig) ProtoMessage() {}

func (x *MatrixRunConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRunConfig.ProtoReflect.Descriptor instead.
func (*MatrixRunConfig) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{2}
}

func (x *MatrixRunConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MatrixRunConfig) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *MatrixRunConfig) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *MatrixRunConfig) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *MatrixRunConfig) GetInclude() []*MatrixRule {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *MatrixRunConfig) GetExclude() []*MatrixRule {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *MatrixRunConfig) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *MatrixRunConfig) GetBuildArgs() []string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *MatrixRunConfig) GetSources() *MatrixRunConfigSources {
	if x != nil {
		return x.Sources
	}
	return nil
}

// MatrixRunConfigSources records where each dimension came from when the run
// started: "cli", "phelix.yaml", "default", or "detected". For remote runs the
// payload counts as "cli".
type MatrixRunConfigSources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Versions      string                 `protobuf:"bytes,2,opt,name=versions,proto3" json:"versions,omitempty"`
	Platforms     string                 `protobuf:"bytes,3,opt,name=platforms,proto3" json:"platforms,omitempty"`
	Concurrency   string                 `protobuf:"bytes,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Retries       string                 `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Include       string                 `protobuf:"bytes,6,opt,name=include,proto3" json:"include,omitempty"`
	Exclude       string                 `protobuf:"bytes,7,opt,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixRunConfigSources) Reset() {
	*x = MatrixRunConfigSources{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixRunConfigSources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRunConfigSources) ProtoMessage() {}

func (x *MatrixRunConfigSources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRunConfigSources.ProtoReflect.Descriptor instead.
func (*MatrixRunConfigSources) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{3}
}

func (x *MatrixRunConfigSources) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MatrixRunConfigSources) GetVersions() string {
	if x != nil {
		return x.Versions
	}
	return ""
}

func (x *MatrixRunConfigSources) GetPlatforms() string {
	if x != nil {
		return x.Platforms
	}
	return ""
}

func (x *MatrixRunConfigSources) GetConcurrency() string {
	if x != nil {
		return x.Concurrency
	}
	return ""
}

func (x *MatrixRunConfigSources) GetRetries() string {
	if x != nil {
		return x.Retries
	}
	return ""
}

func (x *MatrixRunConfigSources) GetInclude() string {
	if x != nil {
		return x.Include
	}
	return ""
}

func (x *MatrixRunConfigSources) GetExclude() string {
	if x != nil {
		return x.Exclude
	}
	return ""
}

// MatrixAttemptState is one recorded execution attempt of one combination
// (attempt 1 = original execution; 2+ = automatic retries).
type MatrixAttemptState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "success" | "failed" | "skipped"
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // redacted; empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixAttemptState) Reset() {
	*x = MatrixAttemptState{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixAttemptState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixAttemptState) ProtoMessage() {}

func (x *MatrixAttemptState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixAttemptState.ProtoReflect.Descriptor instead.
func (*MatrixAttemptState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{4}
}

func (x *MatrixAttemptState) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MatrixAttemptState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixAttemptState) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MatrixAttemptState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// MatrixCombinationState is one combination's outcome inside a run — the
// agent's matrix.RunCombination. For docker-matrix results (no run) the
// run-scoped fields (identity) are empty.
type MatrixCombinationState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // path-safe combination ID, e.g. "go1.26-linux-amd64"
	Identity         string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`   // run-scoped "<runID>/<combinationID>" (native runs only)
	Toolchain        string                 `protobuf:"bytes,3,opt,name=toolchain,proto3" json:"toolchain,omitempty"` // "go" | "rust"
	ToolchainVersion string                 `protobuf:"bytes,4,opt,name=toolchain_version,json=toolchainVersion,proto3" json:"toolchain_version,omitempty"`
	Os               string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	Variant          string                 `protobuf:"bytes,7,opt,name=variant,proto3" json:"variant,omitempty"`   // ARM variant ("v6"/"v7"); empty otherwise
	Platform         string                 `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"` // "os/arch[/variant]"
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`     // pending|running|success|failed|skipped
	DurationMs       int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Artifact         string                 `protobuf:"bytes,11,opt,name=artifact,proto3" json:"artifact,omitempty"` // binary path (native) or image reference (docker)
	// sha256 is the SHA-256 of the artifact's bytes as lowercase hex (native
	// builds), or the image's content digest (docker builds). Empty for
	// failed/incomplete combinations — only a verified artifact carries one.
	Sha256 string `protobuf:"bytes,12,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// size_bytes is the artifact's size on disk (0 for image references and
	// missing files — for images the digest is the identity).
	SizeBytes int64 `protobuf:"varint,13,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// started_at is when the current/last attempt began (unix ms; 0 = never).
	StartedAt     int64                 `protobuf:"varint,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error         string                `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`                                // redacted final error; empty on success
	CacheStatus   string                `protobuf:"bytes,16,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"` // compiler-cache classification: "cold"|"hit"|""
	Attempts      int32                 `protobuf:"varint,17,opt,name=attempts,proto3" json:"attempts,omitempty"`                         // attempt count; 1 when never retried
	AttemptLog    []*MatrixAttemptState `protobuf:"bytes,18,rep,name=attempt_log,json=attemptLog,proto3" json:"attempt_log,omitempty"`
	Metadata      map[string]string     `protobuf:"bytes,19,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // include-rule attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixCombinationState) Reset() {
	*x = MatrixCombinationState{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixCombinationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixCombinationState) ProtoMessage() {}

func (x *MatrixCombinationState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixCombinationState.ProtoReflect.Descriptor instead.
func (*MatrixCombinationState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{5}
}

func (x *MatrixCombinationState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatrixCombinationState) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *MatrixCombinationState) GetToolchain() string {
	if x != nil {
		return x.Toolchain
	}
	return ""
}

func (x *MatrixCombinationState) GetToolchainVersion() string {
	if x != nil {
		return x.ToolchainVersion
	}
	return ""
}

func (x *MatrixCombinationState) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MatrixCombinationState) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *MatrixCombinationState) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *MatrixCombinationState) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *MatrixCombinationState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixCombinationState) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MatrixCombinationState) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *MatrixCombinationState) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *MatrixCombinationState) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MatrixCombinationState) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *MatrixCombinationState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MatrixCombinationState) GetCacheStatus() string {
	if x != nil {
		return x.CacheStatus
	}
	return ""
}

func (x *MatrixCombinationState) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *MatrixCombinationState) GetAttemptLog() []*MatrixAttemptState {
	if x != nil {
		return x.AttemptLog
	}
	return nil
}

func (x *MatrixCombinationState) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MatrixCounters is the per-status combination count snapshot of a run. It is
// computed in one pass under the run's lock, so total == succeeded + failed +
// skipped + running + pending always holds.
type MatrixCounters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Succeeded     int32                  `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Skipped       int32                  `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Running       int32                  `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	Pending       int32                  `protobuf:"varint,6,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixCounters) Reset() {
	*x = MatrixCounters{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixCounters) ProtoMessage() {}

func (x *MatrixCounters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixCounters.ProtoReflect.Descriptor instead.
func (*MatrixCounters) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{6}
}

func (x *MatrixCounters) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MatrixCounters) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *MatrixCounters) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *MatrixCounters) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *MatrixCounters) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *MatrixCounters) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

// MatrixReleaseInfo is the release view of a terminal run: the summary of its
// release manifest (one manifest file per run, generated when a terminal run
// has successful artifacts). Present only when a manifest exists.
type MatrixReleaseInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // logical application version (versions.json vN)
	Tag               string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`        // "complete" (every combination succeeded) | "partial"
	Artifacts         int32                  `protobuf:"varint,4,opt,name=artifacts,proto3" json:"artifacts,omitempty"` // successful artifacts listed in the manifest
	TotalCombinations int32                  `protobuf:"varint,5,opt,name=total_combinations,json=totalCombinations,proto3" json:"total_combinations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatrixReleaseInfo) Reset() {
	*x = MatrixReleaseInfo{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixReleaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixReleaseInfo) ProtoMessage() {}

func (x *MatrixReleaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixReleaseInfo.ProtoReflect.Descriptor instead.
func (*MatrixReleaseInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{7}
}

func (x *MatrixReleaseInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MatrixReleaseInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MatrixReleaseInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixReleaseInfo) GetArtifacts() int32 {
	if x != nil {
		return x.Artifacts
	}
	return 0
}

func (x *MatrixReleaseInfo) GetTotalCombinations() int32 {
	if x != nil {
		return x.TotalCombinations
	}
	return 0
}

// MatrixRunState is the complete state of one Matrix Run — the same entity the
// agent persists in its local run history (matrix.Run). It is carried by
// terminal command results (matrix_status answers, matrix_build/resume/retry
// outcomes), by terminal lifecycle events, and by the MonitorEvent resync
// snapshot after a reconnect.
type MatrixRunState struct {
	state        protoimpl.MessageState    `protogen:"open.v1"`
	MatrixRunId  string                    `protobuf:"bytes,1,opt,name=matrix_run_id,json=matrixRunId,proto3" json:"matrix_run_id,omitempty"` // "mx_YYYYMMDD_xxxx"
	AppName      string                    `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ProjectDir   string                    `protobuf:"bytes,3,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	Status       string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // running|succeeded|partial|failed|interrupted
	Config       *MatrixRunConfig          `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	StartedAt    int64                     `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`    // unix ms
	FinishedAt   int64                     `protobuf:"varint,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // unix ms; 0 while running
	DurationMs   int64                     `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 0 while running
	Counters     *MatrixCounters           `protobuf:"bytes,9,opt,name=counters,proto3" json:"counters,omitempty"`
	Combinations []*MatrixCombinationState `protobuf:"bytes,10,rep,name=combinations,proto3" json:"combinations,omitempty"`
	ParentRunId  string                    `protobuf:"bytes,11,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"` // manual retry runs: the source run
	ResumeCount  int32                     `protobuf:"varint,12,opt,name=resume_count,json=resumeCount,proto3" json:"resume_count,omitempty"`  // how many times the run was resumed
	// active/lock_pid report live execution (the run's lock is held by a live
	// process). Populated in status answers and resync snapshots; a "running"
	// run with active=false is orphaned (crashed agent) and resumable.
	Active        bool               `protobuf:"varint,13,opt,name=active,proto3" json:"active,omitempty"`
	LockPid       int32              `protobuf:"varint,14,opt,name=lock_pid,json=lockPid,proto3" json:"lock_pid,omitempty"`
	Release       *MatrixReleaseInfo `protobuf:"bytes,15,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixRunState) Reset() {
	*x = MatrixRunState{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixRunState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRunState) ProtoMessage() {}

func (x *MatrixRunState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRunState.ProtoReflect.Descriptor instead.
func (*MatrixRunState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{8}
}

func (x *MatrixRunState) GetMatrixRunId() string {
	if x != nil {
		return x.MatrixRunId
	}
	return ""
}

func (x *MatrixRunState) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MatrixRunState) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *MatrixRunState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixRunState) GetConfig() *MatrixRunConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MatrixRunState) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *MatrixRunState) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *MatrixRunState) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MatrixRunState) GetCounters() *MatrixCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *MatrixRunState) GetCombinations() []*MatrixCombinationState {
	if x != nil {
		return x.Combinations
	}
	return nil
}

func (x *MatrixRunState) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *MatrixRunState) GetResumeCount() int32 {
	if x != nil {
		return x.ResumeCount
	}
	return 0
}

func (x *MatrixRunState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MatrixRunState) GetLockPid() int32 {
	if x != nil {
		return x.LockPid
	}
	return 0
}

func (x *MatrixRunState) GetRelease() *MatrixReleaseInfo {
	if x != nil {
		return x.Release
	}
	return nil
}

// MatrixRunSummary is one entry of a matrix_list answer (the remote form of
// `phelix matrix list`).
type MatrixRunSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatrixRunId   string                 `protobuf:"bytes,1,opt,name=matrix_run_id,json=matrixRunId,proto3" json:"matrix_run_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Counters      *MatrixCounters        `protobuf:"bytes,4,opt,name=counters,proto3" json:"counters,omitempty"`
	ParentRunId   string                 `protobuf:"bytes,5,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	ResumeCount   int32                  `protobuf:"varint,6,opt,name=resume_count,json=resumeCount,proto3" json:"resume_count,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`    // unix ms
	FinishedAt    int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // unix ms; 0 when not finished
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixRunSummary) Reset() {
	*x = MatrixRunSummary{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixRunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRunSummary) ProtoMessage() {}

func (x *MatrixRunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRunSummary.ProtoReflect.Descriptor instead.
func (*MatrixRunSummary) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{9}
}

func (x *MatrixRunSummary) GetMatrixRunId() string {
	if x != nil {
		return x.MatrixRunId
	}
	return ""
}

func (x *MatrixRunSummary) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MatrixRunSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixRunSummary) GetCounters() *MatrixCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *MatrixRunSummary) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *MatrixRunSummary) GetResumeCount() int32 {
	if x != nil {
		return x.ResumeCount
	}
	return 0
}

func (x *MatrixRunSummary) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *MatrixRunSummary) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *MatrixRunSummary) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// MatrixPlanPreview is the structured answer of a dry-run command
// (matrix_build / matrix_dockerize / matrix_resume with dry_run=true). It
// describes exactly what the command would execute — no run is created, no
// lock taken, no build started, no state mutated.
type MatrixPlanPreview struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Language string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// combinations lists the combination IDs of the effective plan, in plan
	// order (base Cartesian product → include → exclude).
	Combinations  []string `protobuf:"bytes,2,rep,name=combinations,proto3" json:"combinations,omitempty"`
	BaseCount     int32    `protobuf:"varint,3,opt,name=base_count,json=baseCount,proto3" json:"base_count,omitempty"`             // combinations from the Cartesian product
	IncludedCount int32    `protobuf:"varint,4,opt,name=included_count,json=includedCount,proto3" json:"included_count,omitempty"` // combinations added by include rules
	ExcludedCount int32    `protobuf:"varint,5,opt,name=excluded_count,json=excludedCount,proto3" json:"excluded_count,omitempty"` // combinations removed by exclude rules
	// Resume dry-run only (empty for build/dockerize previews):
	ResumeRunId string `protobuf:"bytes,6,opt,name=resume_run_id,json=resumeRunId,proto3" json:"resume_run_id,omitempty"` // the run the resume would continue
	RunTotal    int32  `protobuf:"varint,7,opt,name=run_total,json=runTotal,proto3" json:"run_total,omitempty"`           // the run's total combinations
	// execute_ids lists the subset a resume would execute (the run's pending
	// and orphaned-running combinations).
	ExecuteIds    []string `protobuf:"bytes,8,rep,name=execute_ids,json=executeIds,proto3" json:"execute_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixPlanPreview) Reset() {
	*x = MatrixPlanPreview{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixPlanPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixPlanPreview) ProtoMessage() {}

func (x *MatrixPlanPreview) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixPlanPreview.ProtoReflect.Descriptor instead.
func (*MatrixPlanPreview) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{10}
}

func (x *MatrixPlanPreview) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *MatrixPlanPreview) GetCombinations() []string {
	if x != nil {
		return x.Combinations
	}
	return nil
}

func (x *MatrixPlanPreview) GetBaseCount() int32 {
	if x != nil {
		return x.BaseCount
	}
	return 0
}

func (x *MatrixPlanPreview) GetIncludedCount() int32 {
	if x != nil {
		return x.IncludedCount
	}
	return 0
}

func (x *MatrixPlanPreview) GetExcludedCount() int32 {
	if x != nil {
		return x.ExcludedCount
	}
	return 0
}

func (x *MatrixPlanPreview) GetResumeRunId() string {
	if x != nil {
		return x.ResumeRunId
	}
	return ""
}

func (x *MatrixPlanPreview) GetRunTotal() int32 {
	if x != nil {
		return x.RunTotal
	}
	return 0
}

func (x *MatrixPlanPreview) GetExecuteIds() []string {
	if x != nil {
		return x.ExecuteIds
	}
	return nil
}

// MatrixDockerResult is the terminal outcome of a matrix_dockerize command.
// Docker matrix builds produce images, not binaries: there is no Matrix Run,
// no run history, no resume and no release manifest (identical to the local
// `phelix dockerize --matrix`). Successful images are recorded as a version
// (versions.json) with per-artifact digests.
type MatrixDockerResult struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	AppName         string                    `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Registry        string                    `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	Tag             string                    `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Version         int32                     `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // recorded application version; 0 when not recorded
	Pushed          bool                      `protobuf:"varint,5,opt,name=pushed,proto3" json:"pushed,omitempty"`
	PushPartial     bool                      `protobuf:"varint,6,opt,name=push_partial,json=pushPartial,proto3" json:"push_partial,omitempty"`
	MultiArchImages []string                  `protobuf:"bytes,7,rep,name=multi_arch_images,json=multiArchImages,proto3" json:"multi_arch_images,omitempty"`
	Counters        *MatrixCounters           `protobuf:"bytes,8,opt,name=counters,proto3" json:"counters,omitempty"`
	Combinations    []*MatrixCombinationState `protobuf:"bytes,9,rep,name=combinations,proto3" json:"combinations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatrixDockerResult) Reset() {
	*x = MatrixDockerResult{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixDockerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixDockerResult) ProtoMessage() {}

func (x *MatrixDockerResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixDockerResult.ProtoReflect.Descriptor instead.
func (*MatrixDockerResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{11}
}

func (x *MatrixDockerResult) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MatrixDockerResult) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *MatrixDockerResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MatrixDockerResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MatrixDockerResult) GetPushed() bool {
	if x != nil {
		return x.Pushed
	}
	return false
}

func (x *MatrixDockerResult) GetPushPartial() bool {
	if x != nil {
		return x.PushPartial
	}
	return false
}

func (x *MatrixDockerResult) GetMultiArchImages() []string {
	if x != nil {
		return x.MultiArchImages
	}
	return nil
}

func (x *MatrixDockerResult) GetCounters() *MatrixCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *MatrixDockerResult) GetCombinations() []*MatrixCombinationState {
	if x != nil {
		return x.Combinations
	}
	return nil
}

// MatrixEvent is one lifecycle event of a remote matrix execution, sent via
// ReportMatrixEvent. Events are best-effort (they may be dropped when the
// agent cannot reach the backend); durable state always travels in the
// terminal MonitorCommandResult and can be re-queried with matrix_status.
//
// Event types (event field):
//
//	matrix.started              run began executing (native mode)
//	matrix.resumed              a resume session began on an existing run
//	matrix.combination_started  one attempt of one combination began
//	matrix.combination_completed one combination reached a final outcome
//	matrix.completed            run reached a terminal status
//	                            (succeeded|partial|failed)
//	matrix.interrupted          run stopped early; resumable (status
//	                            "interrupted")
//
// Docker matrix builds use the same event types minus matrix.resumed and
// matrix.interrupted (there is no run to resume; mode="docker" and
// matrix_run_id are empty, and events correlate by request_id).
type MatrixEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServerId    string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequestId   string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`         // correlation with the originating command
	MatrixRunId string                 `protobuf:"bytes,3,opt,name=matrix_run_id,json=matrixRunId,proto3" json:"matrix_run_id,omitempty"` // native mode only; empty for docker builds
	AppName     string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Event       string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Timestamp   int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix ms
	// seq is the per-run (native) / per-request (docker) monotonic sequence
	// number, starting at 1. Strictly increasing within that scope; gaps mean
	// dropped events. Never comparable across runs or requests.
	Seq  int64  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Mode string `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"` // "native" | "docker"
	// status is the run status as of this event (run-level events only).
	Status  string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"` // human-readable detail
	// counters is the consistent per-status snapshot (run-level events only).
	Counters *MatrixCounters `protobuf:"bytes,11,opt,name=counters,proto3" json:"counters,omitempty"`
	// combination identifies the combination this event is about
	// (combination_started / combination_completed). For
	// combination_completed it carries the full final outcome (artifact,
	// sha256, size, attempts, attempt_log, error).
	Combination *MatrixCombinationState `protobuf:"bytes,12,opt,name=combination,proto3" json:"combination,omitempty"`
	// attempt is the attempt number that began (combination_started only);
	// values >= 2 are automatic retries.
	Attempt int32 `protobuf:"varint,13,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// error/error_code are set on terminal events of failed executions
	// (error is redacted; error_code is a phelix error code, e.g. BUILD_FAILED).
	Error     string `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,15,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// run carries the full MatrixRunState on matrix.started, matrix.resumed,
	// matrix.completed and matrix.interrupted. Empty for combination events —
	// the backend aggregates those from counters and per-combination updates,
	// or re-queries with matrix_status.
	Run *MatrixRunState `protobuf:"bytes,16,opt,name=run,proto3" json:"run,omitempty"`
	// metadata carries mode-specific details (docker matrix.started: registry,
	// tag, push flags).
	Metadata      map[string]string `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixEvent) Reset() {
	*x = MatrixEvent{}
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixEvent) ProtoMessage() {}

func (x *MatrixEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_matrix_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixEvent.ProtoReflect.Descriptor instead.
func (*MatrixEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_matrix_proto_rawDescGZIP(), []int{12}
}

func (x *MatrixEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MatrixEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MatrixEvent) GetMatrixRunId() string {
	if x != nil {
		return x.MatrixRunId
	}
	return ""
}

func (x *MatrixEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MatrixEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *MatrixEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MatrixEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MatrixEvent) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MatrixEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MatrixEvent) GetCounters() *MatrixCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *MatrixEvent) GetCombination() *MatrixCombinationState {
	if x != nil {
		return x.Combination
	}
	return nil
}

func (x *MatrixEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MatrixEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MatrixEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MatrixEvent) GetRun() *MatrixRunState {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *MatrixEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_internal_grpc_proto_matrix_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_matrix_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/matrix.proto\x12\x06phelix\"\xf8\x02\n" +
	"\rMatrixOptions\x12\x1f\n" +
	"\vgo_versions\x18\x01 \x03(\tR\n" +
	"goVersions\x12#\n" +
	"\rrust_versions\x18\x02 \x03(\tR\frustVersions\x12\x1c\n" +
	"\tplatforms\x18\x03 \x03(\tR\tplatforms\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12\x1d\n" +
	"\n" +
	"build_args\x18\x06 \x03(\tR\tbuildArgs\x12\x10\n" +
	"\x03tag\x18\a \x01(\tR\x03tag\x12\x1a\n" +
	"\bregistry\x18\b \x01(\tR\bregistry\x12\x12\n" +
	"\x04push\x18\t \x01(\bR\x04push\x12!\n" +
	"\fpush_partial\x18\n" +
	" \x01(\bR\vpushPartial\x12$\n" +
	"\x0emulti_arch_tag\x18\v \x01(\bR\fmultiArchTag\x12\x1d\n" +
	"\n" +
	"list_limit\x18\f \x01(\x05R\tlistLimit\"\x8a\x02\n" +
	"\n" +
	"MatrixRule\x12B\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v2\".phelix.MatrixRule.DimensionsEntryR\n" +
	"dimensions\x12<\n" +
	"\bmetadata\x18\x02 \x03(\v2 .phelix.MatrixRule.MetadataEntryR\bmetadata\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x02\n" +
	"\x0fMatrixRunConfig\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\tR\bversions\x12\x1c\n" +
	"\tplatforms\x18\x03 \x03(\tR\tplatforms\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\x12,\n" +
	"\ainclude\x18\x05 \x03(\v2\x12.phelix.MatrixRuleR\ainclude\x12,\n" +
	"\aexclude\x18\x06 \x03(\v2\x12.phelix.MatrixRuleR\aexclude\x12\x18\n" +
	"\aretries\x18\a \x01(\x05R\aretries\x12\x1d\n" +
	"\n" +
	"build_args\x18\b \x03(\tR\tbuildArgs\x128\n" +
	"\asources\x18\t \x01(\v2\x1e.phelix.MatrixRunConfigSourcesR\asources\"\xde\x01\n" +
	"\x16MatrixRunConfigSources\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1a\n" +
	"\bversions\x18\x02 \x01(\tR\bversions\x12\x1c\n" +
	"\tplatforms\x18\x03 \x01(\tR\tplatforms\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\tR\vconcurrency\x12\x18\n" +
	"\aretries\x18\x05 \x01(\tR\aretries\x12\x18\n" +
	"\ainclude\x18\x06 \x01(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\a \x01(\tR\aexclude\"{\n" +
	"\x12MatrixAttemptState\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xad\x05\n" +
	"\x16MatrixCombinationState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x1c\n" +
	"\ttoolchain\x18\x03 \x01(\tR\ttoolchain\x12+\n" +
	"\x11toolchain_version\x18\x04 \x01(\tR\x10toolchainVersion\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x18\n" +
	"\avariant\x18\a \x01(\tR\avariant\x12\x1a\n" +
	"\bplatform\x18\b \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12\x1a\n" +
	"\bartifact\x18\v \x01(\tR\bartifact\x12\x16\n" +
	"\x06sha256\x18\f \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\r \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"started_at\x18\x0e \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12!\n" +
	"\fcache_status\x18\x10 \x01(\tR\vcacheStatus\x12\x1a\n" +
	"\battempts\x18\x11 \x01(\x05R\battempts\x12;\n" +
	"\vattempt_log\x18\x12 \x03(\v2\x1a.phelix.MatrixAttemptStateR\n" +
	"attemptLog\x12H\n" +
	"\bmetadata\x18\x13 \x03(\v2,.phelix.MatrixCombinationState.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x0eMatrixCounters\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x18\n" +
	"\arunning\x18\x05 \x01(\x05R\arunning\x12\x18\n" +
	"\apending\x18\x06 \x01(\x05R\apending\"\xa4\x01\n" +
	"\x11MatrixReleaseInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tartifacts\x18\x04 \x01(\x05R\tartifacts\x12-\n" +
	"\x12total_combinations\x18\x05 \x01(\x05R\x11totalCombinations\"\xc1\x04\n" +
	"\x0eMatrixRunState\x12\"\n" +
	"\rmatrix_run_id\x18\x01 \x01(\tR\vmatrixRunId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1f\n" +
	"\vproject_dir\x18\x03 \x01(\tR\n" +
	"projectDir\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.phelix.MatrixRunConfigR\x06config\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\a \x01(\x03R\n" +
	"finishedAt\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x122\n" +
	"\bcounters\x18\t \x01(\v2\x16.phelix.MatrixCountersR\bcounters\x12B\n" +
	"\fcombinations\x18\n" +
	" \x03(\v2\x1e.phelix.MatrixCombinationStateR\fcombinations\x12\"\n" +
	"\rparent_run_id\x18\v \x01(\tR\vparentRunId\x12!\n" +
	"\fresume_count\x18\f \x01(\x05R\vresumeCount\x12\x16\n" +
	"\x06active\x18\r \x01(\bR\x06active\x12\x19\n" +
	"\block_pid\x18\x0e \x01(\x05R\alockPid\x123\n" +
	"\arelease\x18\x0f \x01(\v2\x19.phelix.MatrixReleaseInfoR\arelease\"\xc5\x02\n" +
	"\x10MatrixRunSummary\x12\"\n" +
	"\rmatrix_run_id\x18\x01 \x01(\tR\vmatrixRunId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x122\n" +
	"\bcounters\x18\x04 \x01(\v2\x16.phelix.MatrixCountersR\bcounters\x12\"\n" +
	"\rparent_run_id\x18\x05 \x01(\tR\vparentRunId\x12!\n" +
	"\fresume_count\x18\x06 \x01(\x05R\vresumeCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\"\xa2\x02\n" +
	"\x11MatrixPlanPreview\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\"\n" +
	"\fcombinations\x18\x02 \x03(\tR\fcombinations\x12\x1d\n" +
	"\n" +
	"base_count\x18\x03 \x01(\x05R\tbaseCount\x12%\n" +
	"\x0eincluded_count\x18\x04 \x01(\x05R\rincludedCount\x12%\n" +
	"\x0eexcluded_count\x18\x05 \x01(\x05R\rexcludedCount\x12\"\n" +
	"\rresume_run_id\x18\x06 \x01(\tR\vresumeRunId\x12\x1b\n" +
	"\trun_total\x18\a \x01(\x05R\brunTotal\x12\x1f\n" +
	"\vexecute_ids\x18\b \x03(\tR\n" +
	"executeIds\"\xd6\x02\n" +
	"\x12MatrixDockerResult\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\bregistry\x18\x02 \x01(\tR\bregistry\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x16\n" +
	"\x06pushed\x18\x05 \x01(\bR\x06pushed\x12!\n" +
	"\fpush_partial\x18\x06 \x01(\bR\vpushPartial\x12*\n" +
	"\x11multi_arch_images\x18\a \x03(\tR\x0fmultiArchImages\x122\n" +
	"\bcounters\x18\b \x01(\v2\x16.phelix.MatrixCountersR\bcounters\x12B\n" +
	"\fcombinations\x18\t \x03(\v2\x1e.phelix.MatrixCombinationStateR\fcombinations\"\xff\x04\n" +
	"\vMatrixEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\"\n" +
	"\rmatrix_run_id\x18\x03 \x01(\tR\vmatrixRunId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x122\n" +
	"\bcounters\x18\v \x01(\v2\x16.phelix.MatrixCountersR\bcounters\x12@\n" +
	"\vcombination\x18\f \x01(\v2\x1e.phelix.MatrixCombinationStateR\vcombination\x12\x18\n" +
	"\aattempt\x18\r \x01(\x05R\aattempt\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0f \x01(\tR\terrorCode\x12(\n" +
	"\x03run\x18\x10 \x01(\v2\x16.phelix.MatrixRunStateR\x03run\x12=\n" +
	"\bmetadata\x18\x11 \x03(\v2!.phelix.MatrixEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_matrix_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_matrix_proto_rawDescData []byte
)

func file_internal_grpc_proto_matrix_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_matrix_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_matrix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_matrix_proto_rawDesc), len(file_internal_grpc_proto_matrix_proto_rawDesc)))
	})
	return file_internal_grpc_proto_matrix_proto_rawDescData
}

var file_internal_grpc_proto_matrix_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_grpc_proto_matrix_proto_goTypes = []any{
	(*MatrixOptions)(nil),          // 0: phelix.MatrixOptions
	(*MatrixRule)(nil),             // 1: phelix.MatrixRule
	(*MatrixRunConfig)(nil),        // 2: phelix.MatrixRunConfig
	(*MatrixRunConfigSources)(nil), // 3: phelix.MatrixRunConfigSources
	(*MatrixAttemptState)(nil),     // 4: phelix.MatrixAttemptState
	(*MatrixCombinationState)(nil), // 5: phelix.MatrixCombinationState
	(*MatrixCounters)(nil),         // 6: phelix.MatrixCounters
	(*MatrixReleaseInfo)(nil),      // 7: phelix.MatrixReleaseInfo
	(*MatrixRunState)(nil),         // 8: phelix.MatrixRunState
	(*MatrixRunSummary)(nil),       // 9: phelix.MatrixRunSummary
	(*MatrixPlanPreview)(nil),      // 10: phelix.MatrixPlanPreview
	(*MatrixDockerResult)(nil),     // 11: phelix.MatrixDockerResult
	(*MatrixEvent)(nil),            // 12: phelix.MatrixEvent
	nil,                            // 13: phelix.MatrixRule.DimensionsEntry
	nil,                            // 14: phelix.MatrixRule.MetadataEntry
	nil,                            // 15: phelix.MatrixCombinationState.MetadataEntry
	nil,                            // 16: phelix.MatrixEvent.MetadataEntry
}
var file_internal_grpc_proto_matrix_proto_depIdxs = []int32{
	13, // 0: phelix.MatrixRule.dimensions:type_name -> phelix.MatrixRule.DimensionsEntry
	14, // 1: phelix.MatrixRule.metadata:type_name -> phelix.MatrixRule.MetadataEntry
	1,  // 2: phelix.MatrixRunConfig.include:type_name -> phelix.MatrixRule
	1,  // 3: phelix.MatrixRunConfig.exclude:type_name -> phelix.MatrixRule
	3,  // 4: phelix.MatrixRunConfig.sources:type_name -> phelix.MatrixRunConfigSources
	4,  // 5: phelix.MatrixCombinationState.attempt_log:type_name -> phelix.MatrixAttemptState
	15, // 6: phelix.MatrixCombinationState.metadata:type_name -> phelix.MatrixCombinationState.MetadataEntry
	2,  // 7: phelix.MatrixRunState.config:type_name -> phelix.MatrixRunConfig
	6,  // 8: phelix.MatrixRunState.counters:type_name -> phelix.MatrixCounters
	5,  // 9: phelix.MatrixRunState.combinations:type_name -> phelix.MatrixCombinationState
	7,  // 10: phelix.MatrixRunState.release:type_name -> phelix.MatrixReleaseInfo
	6,  // 11: phelix.MatrixRunSummary.counters:type_name -> phelix.MatrixCounters
	6,  // 12: phelix.MatrixDockerResult.counters:type_name -> phelix.MatrixCounters
	5,  // 13: phelix.MatrixDockerResult.combinations:type_name -> phelix.MatrixCombinationState
	6,  // 14: phelix.MatrixEvent.counters:type_name -> phelix.MatrixCounters
	5,  // 15: phelix.MatrixEvent.combination:type_name -> phelix.MatrixCombinationState
	8,  // 16: phelix.MatrixEvent.run:type_name -> phelix.MatrixRunState
	16, // 17: phelix.MatrixEvent.metadata:type_name -> phelix.MatrixEvent.MetadataEntry
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_matrix_proto_init() }
func file_internal_grpc_proto_matrix_proto_init() {
	if File_internal_grpc_proto_matrix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_matrix_proto_rawDesc), len(file_internal_grpc_proto_matrix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_matrix_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_matrix_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_matrix_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_matrix_proto = out.File
	file_internal_grpc_proto_matrix_proto_goTypes = nil
	file_internal_grpc_proto_matrix_proto_depIdxs = nil
}
