// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/monitoring.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogSource distinguishes application logs from the CLI's own daemon logs,
// matching the old "app_logs" vs "self_logs" WebSocket message types.
type LogSource int32

const (
	LogSource_LOG_SOURCE_UNSPECIFIED LogSource = 0
	LogSource_LOG_SOURCE_APPLICATION LogSource = 1
	LogSource_LOG_SOURCE_SELF        LogSource = 2
)

// Enum value maps for LogSource.
var (
	LogSource_name = map[int32]string{
		0: "LOG_SOURCE_UNSPECIFIED",
		1: "LOG_SOURCE_APPLICATION",
		2: "LOG_SOURCE_SELF",
	}
	LogSource_value = map[string]int32{
		"LOG_SOURCE_UNSPECIFIED": 0,
		"LOG_SOURCE_APPLICATION": 1,
		"LOG_SOURCE_SELF":        2,
	}
)

func (x LogSource) Enum() *LogSource {
	p := new(LogSource)
	*p = x
	return p
}

func (x LogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_monitoring_proto_enumTypes[0].Descriptor()
}

func (LogSource) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_monitoring_proto_enumTypes[0]
}

func (x LogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSource.Descriptor instead.
func (LogSource) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{0}
}

// ServerInfo mirrors server.Info. Sent once when the monitor stream is
// (re)established, exactly like the old "servers" WebSocket message.
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpV4          string                 `protobuf:"bytes,3,opt,name=ip_v4,json=ipV4,proto3" json:"ip_v4,omitempty"`
	IpV6          string                 `protobuf:"bytes,4,opt,name=ip_v6,json=ipV6,proto3" json:"ip_v6,omitempty"`
	OsType        string                 `protobuf:"bytes,5,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsFull        string                 `protobuf:"bytes,6,opt,name=os_full,json=osFull,proto3" json:"os_full,omitempty"`
	CpuInfo       string                 `protobuf:"bytes,7,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	NetworkIfaces []string               `protobuf:"bytes,8,rep,name=network_ifaces,json=networkIfaces,proto3" json:"network_ifaces,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,9,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	TotalCpuCores int32                  `protobuf:"varint,10,opt,name=total_cpu_cores,json=totalCpuCores,proto3" json:"total_cpu_cores,omitempty"`
	TotalStorage  int64                  `protobuf:"varint,11,opt,name=total_storage,json=totalStorage,proto3" json:"total_storage,omitempty"`
	Uptime        string                 `protobuf:"bytes,12,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LastReboot    int64                  `protobuf:"varint,13,opt,name=last_reboot,json=lastReboot,proto3" json:"last_reboot,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Region        string                 `protobuf:"bytes,16,opt,name=region,proto3" json:"region,omitempty"`
	Architecture  string                 `protobuf:"bytes,17,opt,name=architecture,proto3" json:"architecture,omitempty"`
	KernelVersion string                 `protobuf:"bytes,18,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	SwapTotal     int64                  `protobuf:"varint,19,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerInfo) GetIpV4() string {
	if x != nil {
		return x.IpV4
	}
	return ""
}

func (x *ServerInfo) GetIpV6() string {
	if x != nil {
		return x.IpV6
	}
	return ""
}

func (x *ServerInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *ServerInfo) GetOsFull() string {
	if x != nil {
		return x.OsFull
	}
	return ""
}

func (x *ServerInfo) GetCpuInfo() string {
	if x != nil {
		return x.CpuInfo
	}
	return ""
}

func (x *ServerInfo) GetNetworkIfaces() []string {
	if x != nil {
		return x.NetworkIfaces
	}
	return nil
}

func (x *ServerInfo) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *ServerInfo) GetTotalCpuCores() int32 {
	if x != nil {
		return x.TotalCpuCores
	}
	return 0
}

func (x *ServerInfo) GetTotalStorage() int64 {
	if x != nil {
		return x.TotalStorage
	}
	return 0
}

func (x *ServerInfo) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *ServerInfo) GetLastReboot() int64 {
	if x != nil {
		return x.LastReboot
	}
	return 0
}

func (x *ServerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ServerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ServerInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ServerInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *ServerInfo) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

// ServerMetrics mirrors server.Metrics. Sent on every monitoring tick
// (~2s), exactly like the old "server_metrics" WebSocket message.
type ServerMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UsedMemory       uint64                 `protobuf:"varint,2,opt,name=used_memory,json=usedMemory,proto3" json:"used_memory,omitempty"`
	FreeMemory       uint64                 `protobuf:"varint,3,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	MemoryPercent    float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	UsedStorage      uint64                 `protobuf:"varint,6,opt,name=used_storage,json=usedStorage,proto3" json:"used_storage,omitempty"`
	FreeStorage      uint64                 `protobuf:"varint,7,opt,name=free_storage,json=freeStorage,proto3" json:"free_storage,omitempty"`
	StoragePercent   float64                `protobuf:"fixed64,8,opt,name=storage_percent,json=storagePercent,proto3" json:"storage_percent,omitempty"`
	Timestamp        int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NetworkIn        uint64                 `protobuf:"varint,10,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`
	NetworkOut       uint64                 `protobuf:"varint,11,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`
	LoadAvg_1Min     float64                `protobuf:"fixed64,12,opt,name=load_avg_1min,json=loadAvg1min,proto3" json:"load_avg_1min,omitempty"`
	LoadAvg_5Min     float64                `protobuf:"fixed64,13,opt,name=load_avg_5min,json=loadAvg5min,proto3" json:"load_avg_5min,omitempty"`
	LoadAvg_15Min    float64                `protobuf:"fixed64,14,opt,name=load_avg_15min,json=loadAvg15min,proto3" json:"load_avg_15min,omitempty"`
	SwapUsed         uint64                 `protobuf:"varint,15,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree         uint64                 `protobuf:"varint,16,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	SwapPercent      float64                `protobuf:"fixed64,17,opt,name=swap_percent,json=swapPercent,proto3" json:"swap_percent,omitempty"`
	RunningProcesses uint32                 `protobuf:"varint,18,opt,name=running_processes,json=runningProcesses,proto3" json:"running_processes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerMetrics) Reset() {
	*x = ServerMetrics{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetrics) ProtoMessage() {}

func (x *ServerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetrics.ProtoReflect.Descriptor instead.
func (*ServerMetrics) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMetrics) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerMetrics) GetUsedMemory() uint64 {
	if x != nil {
		return x.UsedMemory
	}
	return 0
}

func (x *ServerMetrics) GetFreeMemory() uint64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *ServerMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ServerMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerMetrics) GetUsedStorage() uint64 {
	if x != nil {
		return x.UsedStorage
	}
	return 0
}

func (x *ServerMetrics) GetFreeStorage() uint64 {
	if x != nil {
		return x.FreeStorage
	}
	return 0
}

func (x *ServerMetrics) GetStoragePercent() float64 {
	if x != nil {
		return x.StoragePercent
	}
	return 0
}

func (x *ServerMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerMetrics) GetNetworkIn() uint64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *ServerMetrics) GetNetworkOut() uint64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

func (x *ServerMetrics) GetLoadAvg_1Min() float64 {
	if x != nil {
		return x.LoadAvg_1Min
	}
	return 0
}

func (x *ServerMetrics) GetLoadAvg_5Min() float64 {
	if x != nil {
		return x.LoadAvg_5Min
	}
	return 0
}

func (x *ServerMetrics) GetLoadAvg_15Min() float64 {
	if x != nil {
		return x.LoadAvg_15Min
	}
	return 0
}

func (x *ServerMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *ServerMetrics) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *ServerMetrics) GetSwapPercent() float64 {
	if x != nil {
		return x.SwapPercent
	}
	return 0
}

func (x *ServerMetrics) GetRunningProcesses() uint32 {
	if x != nil {
		return x.RunningProcesses
	}
	return 0
}

// AppResourceMetrics mirrors monitor.AppMetrics (per-app CPU/RAM usage).
// Sent on every monitoring tick, exactly like the old "metrics" WebSocket
// message.
type AppResourceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppResourceMetrics) Reset() {
	*x = AppResourceMetrics{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppResourceMetrics) ProtoMessage() {}

func (x *AppResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppResourceMetrics.ProtoReflect.Descriptor instead.
func (*AppResourceMetrics) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *AppResourceMetrics) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppResourceMetrics) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AppResourceMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AppResourceMetrics) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// ApplicationInfo mirrors monitor.AppDetails. Sent on every monitoring tick,
// exactly like the old "apps" WebSocket message.
type ApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	BuildStatus   string                 `protobuf:"bytes,7,opt,name=build_status,json=buildStatus,proto3" json:"build_status,omitempty"`
	Pid           int32                  `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	Uptime        string                 `protobuf:"bytes,9,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplicationInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ApplicationInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ApplicationInfo) GetBuildStatus() string {
	if x != nil {
		return x.BuildStatus
	}
	return ""
}

func (x *ApplicationInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ApplicationInfo) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *ApplicationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ApplicationInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// MonitorLogEntry mirrors logs.LogEntry. Sent on every monitoring tick for
// both application and self logs.
type MonitorLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Log           string                 `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	Date          int64                  `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Source        LogSource              `protobuf:"varint,7,opt,name=source,proto3,enum=phelix.LogSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorLogEntry) Reset() {
	*x = MonitorLogEntry{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorLogEntry) ProtoMessage() {}

func (x *MonitorLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorLogEntry.ProtoReflect.Descriptor instead.
func (*MonitorLogEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *MonitorLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonitorLogEntry) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MonitorLogEntry) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MonitorLogEntry) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *MonitorLogEntry) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *MonitorLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *MonitorLogEntry) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

// MonitorCommandRequest mirrors the old "command" WebSocket message payload
// (monitor.CommandPayload): a remote-control instruction from the backend,
// e.g. restart/stop/start a specific managed application.
type MonitorCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorCommandRequest) Reset() {
	*x = MonitorCommandRequest{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorCommandRequest) ProtoMessage() {}

func (x *MonitorCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorCommandRequest.ProtoReflect.Descriptor instead.
func (*MonitorCommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *MonitorCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MonitorCommandRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MonitorCommandRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// MonitorCommandResult mirrors the old "command_response" WebSocket message
// sent back to the backend after a command finishes executing.
type MonitorCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorCommandResult) Reset() {
	*x = MonitorCommandResult{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorCommandResult) ProtoMessage() {}

func (x *MonitorCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorCommandResult.ProtoReflect.Descriptor instead.
func (*MonitorCommandResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *MonitorCommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MonitorCommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MonitorCommandResult) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MonitorCommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MonitorCommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MonitorCommandResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MonitorEvent is a single message sent from the CLI monitor daemon to the
// backend over the long-lived MonitorStream. Exactly one payload is set per
// event, mirroring the "type"/"payload" envelope used by the old WebSocket
// protocol ("servers", "server_metrics", "metrics", "apps", "app_logs",
// "self_logs", "command_response", "pong").
//
// The oneof is intentionally extensible: new monitoring signals can be added
// as additional fields without breaking existing consumers.
type MonitorEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServerId  string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MonitorEvent_ServerInfo
	//	*MonitorEvent_ServerMetrics
	//	*MonitorEvent_AppMetrics
	//	*MonitorEvent_AppInfo
	//	*MonitorEvent_LogEntry
	//	*MonitorEvent_CommandResult
	//	*MonitorEvent_Pong
	Payload       isMonitorEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorEvent) Reset() {
	*x = MonitorEvent{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorEvent) ProtoMessage() {}

func (x *MonitorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorEvent.ProtoReflect.Descriptor instead.
func (*MonitorEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *MonitorEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MonitorEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MonitorEvent) GetPayload() isMonitorEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MonitorEvent) GetServerInfo() *ServerInfo {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_ServerInfo); ok {
			return x.ServerInfo
		}
	}
	return nil
}

func (x *MonitorEvent) GetServerMetrics() *ServerMetrics {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_ServerMetrics); ok {
			return x.ServerMetrics
		}
	}
	return nil
}

func (x *MonitorEvent) GetAppMetrics() *AppResourceMetrics {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_AppMetrics); ok {
			return x.AppMetrics
		}
	}
	return nil
}

func (x *MonitorEvent) GetAppInfo() *ApplicationInfo {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_AppInfo); ok {
			return x.AppInfo
		}
	}
	return nil
}

func (x *MonitorEvent) GetLogEntry() *MonitorLogEntry {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_LogEntry); ok {
			return x.LogEntry
		}
	}
	return nil
}

func (x *MonitorEvent) GetCommandResult() *MonitorCommandResult {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *MonitorEvent) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*MonitorEvent_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isMonitorEvent_Payload interface {
	isMonitorEvent_Payload()
}

type MonitorEvent_ServerInfo struct {
	ServerInfo *ServerInfo `protobuf:"bytes,10,opt,name=server_info,json=serverInfo,proto3,oneof"`
}

type MonitorEvent_ServerMetrics struct {
	ServerMetrics *ServerMetrics `protobuf:"bytes,11,opt,name=server_metrics,json=serverMetrics,proto3,oneof"`
}

type MonitorEvent_AppMetrics struct {
	AppMetrics *AppResourceMetrics `protobuf:"bytes,12,opt,name=app_metrics,json=appMetrics,proto3,oneof"`
}

type MonitorEvent_AppInfo struct {
	AppInfo *ApplicationInfo `protobuf:"bytes,13,opt,name=app_info,json=appInfo,proto3,oneof"`
}

type MonitorEvent_LogEntry struct {
	LogEntry *MonitorLogEntry `protobuf:"bytes,14,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

type MonitorEvent_CommandResult struct {
	CommandResult *MonitorCommandResult `protobuf:"bytes,15,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type MonitorEvent_Pong struct {
	Pong *Pong `protobuf:"bytes,16,opt,name=pong,proto3,oneof"`
}

func (*MonitorEvent_ServerInfo) isMonitorEvent_Payload() {}

func (*MonitorEvent_ServerMetrics) isMonitorEvent_Payload() {}

func (*MonitorEvent_AppMetrics) isMonitorEvent_Payload() {}

func (*MonitorEvent_AppInfo) isMonitorEvent_Payload() {}

func (*MonitorEvent_LogEntry) isMonitorEvent_Payload() {}

func (*MonitorEvent_CommandResult) isMonitorEvent_Payload() {}

func (*MonitorEvent_Pong) isMonitorEvent_Payload() {}

// MonitorControl is a single message sent from the backend to the CLI
// monitor daemon over the same long-lived MonitorStream. It mirrors the old
// "command" and "ping" WebSocket message types sent by the backend.
type MonitorControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MonitorControl_Command
	//	*MonitorControl_Ping
	Payload       isMonitorControl_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorControl) Reset() {
	*x = MonitorControl{}
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorControl) ProtoMessage() {}

func (x *MonitorControl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorControl.ProtoReflect.Descriptor instead.
func (*MonitorControl) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *MonitorControl) GetPayload() isMonitorControl_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MonitorControl) GetCommand() *MonitorCommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*MonitorControl_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *MonitorControl) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*MonitorControl_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isMonitorControl_Payload interface {
	isMonitorControl_Payload()
}

type MonitorControl_Command struct {
	Command *MonitorCommandRequest `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type MonitorControl_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*MonitorControl_Command) isMonitorControl_Payload() {}

func (*MonitorControl_Ping) isMonitorControl_Payload() {}

var File_internal_grpc_proto_monitoring_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_monitoring_proto_rawDesc = "" +
	"\n" +
	"$internal/grpc/proto/monitoring.proto\x12\x06phelix\x1a\x1einternal/grpc/proto/ping.proto\"\xb8\x04\n" +
	"\n" +
	"ServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x13\n" +
	"\x05ip_v4\x18\x03 \x01(\tR\x04ipV4\x12\x13\n" +
	"\x05ip_v6\x18\x04 \x01(\tR\x04ipV6\x12\x17\n" +
	"\aos_type\x18\x05 \x01(\tR\x06osType\x12\x17\n" +
	"\aos_full\x18\x06 \x01(\tR\x06osFull\x12\x19\n" +
	"\bcpu_info\x18\a \x01(\tR\acpuInfo\x12%\n" +
	"\x0enetwork_ifaces\x18\b \x03(\tR\rnetworkIfaces\x12!\n" +
	"\ftotal_memory\x18\t \x01(\x03R\vtotalMemory\x12&\n" +
	"\x0ftotal_cpu_cores\x18\n" +
	" \x01(\x05R\rtotalCpuCores\x12#\n" +
	"\rtotal_storage\x18\v \x01(\x03R\ftotalStorage\x12\x16\n" +
	"\x06uptime\x18\f \x01(\tR\x06uptime\x12\x1f\n" +
	"\vlast_reboot\x18\r \x01(\x03R\n" +
	"lastReboot\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06region\x18\x10 \x01(\tR\x06region\x12\"\n" +
	"\farchitecture\x18\x11 \x01(\tR\farchitecture\x12%\n" +
	"\x0ekernel_version\x18\x12 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x13 \x01(\x03R\tswapTotal\"\x86\x05\n" +
	"\rServerMetrics\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vused_memory\x18\x02 \x01(\x04R\n" +
	"usedMemory\x12\x1f\n" +
	"\vfree_memory\x18\x03 \x01(\x04R\n" +
	"freeMemory\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x12!\n" +
	"\fused_storage\x18\x06 \x01(\x04R\vusedStorage\x12!\n" +
	"\ffree_storage\x18\a \x01(\x04R\vfreeStorage\x12'\n" +
	"\x0fstorage_percent\x18\b \x01(\x01R\x0estoragePercent\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"network_in\x18\n" +
	" \x01(\x04R\tnetworkIn\x12\x1f\n" +
	"\vnetwork_out\x18\v \x01(\x04R\n" +
	"networkOut\x12\"\n" +
	"\rload_avg_1min\x18\f \x01(\x01R\vloadAvg1min\x12\"\n" +
	"\rload_avg_5min\x18\r \x01(\x01R\vloadAvg5min\x12$\n" +
	"\x0eload_avg_15min\x18\x0e \x01(\x01R\floadAvg15min\x12\x1b\n" +
	"\tswap_used\x18\x0f \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\x10 \x01(\x04R\bswapFree\x12!\n" +
	"\fswap_percent\x18\x11 \x01(\x01R\vswapPercent\x12+\n" +
	"\x11running_processes\x18\x12 \x01(\rR\x10runningProcesses\"\x88\x01\n" +
	"\x12AppResourceMetrics\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x04R\vmemoryUsage\"\xa5\x02\n" +
	"\x0fApplicationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12!\n" +
	"\fbuild_status\x18\a \x01(\tR\vbuildStatus\x12\x10\n" +
	"\x03pid\x18\b \x01(\x05R\x03pid\x12\x16\n" +
	"\x06uptime\x18\t \x01(\tR\x06uptime\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xbc\x01\n" +
	"\x0fMonitorLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x10\n" +
	"\x03log\x18\x04 \x01(\tR\x03log\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x03R\x04date\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\x12)\n" +
	"\x06source\x18\a \x01(\x0e2\x11.phelix.LogSourceR\x06source\"e\n" +
	"\x15MonitorCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\"\xb6\x01\n" +
	"\x14MonitorCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xe3\x03\n" +
	"\fMonitorEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x125\n" +
	"\vserver_info\x18\n" +
	" \x01(\v2\x12.phelix.ServerInfoH\x00R\n" +
	"serverInfo\x12>\n" +
	"\x0eserver_metrics\x18\v \x01(\v2\x15.phelix.ServerMetricsH\x00R\rserverMetrics\x12=\n" +
	"\vapp_metrics\x18\f \x01(\v2\x1a.phelix.AppResourceMetricsH\x00R\n" +
	"appMetrics\x124\n" +
	"\bapp_info\x18\r \x01(\v2\x17.phelix.ApplicationInfoH\x00R\aappInfo\x126\n" +
	"\tlog_entry\x18\x0e \x01(\v2\x17.phelix.MonitorLogEntryH\x00R\blogEntry\x12E\n" +
	"\x0ecommand_result\x18\x0f \x01(\v2\x1c.phelix.MonitorCommandResultH\x00R\rcommandResult\x12\"\n" +
	"\x04pong\x18\x10 \x01(\v2\f.phelix.PongH\x00R\x04pongB\t\n" +
	"\apayload\"z\n" +
	"\x0eMonitorControl\x129\n" +
	"\acommand\x18\x01 \x01(\v2\x1d.phelix.MonitorCommandRequestH\x00R\acommand\x12\"\n" +
	"\x04ping\x18\x02 \x01(\v2\f.phelix.PingH\x00R\x04pingB\t\n" +
	"\apayload*X\n" +
	"\tLogSource\x12\x1a\n" +
	"\x16LOG_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LOG_SOURCE_APPLICATION\x10\x01\x12\x13\n" +
	"\x0fLOG_SOURCE_SELF\x10\x02B4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_monitoring_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_monitoring_proto_rawDescData []byte
)

func file_internal_grpc_proto_monitoring_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_monitoring_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_monitoring_proto_rawDesc), len(file_internal_grpc_proto_monitoring_proto_rawDesc)))
	})
	return file_internal_grpc_proto_monitoring_proto_rawDescData
}

var file_internal_grpc_proto_monitoring_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_grpc_proto_monitoring_proto_goTypes = []any{
	(LogSource)(0),                // 0: phelix.LogSource
	(*ServerInfo)(nil),            // 1: phelix.ServerInfo
	(*ServerMetrics)(nil),         // 2: phelix.ServerMetrics
	(*AppResourceMetrics)(nil),    // 3: phelix.AppResourceMetrics
	(*ApplicationInfo)(nil),       // 4: phelix.ApplicationInfo
	(*MonitorLogEntry)(nil),       // 5: phelix.MonitorLogEntry
	(*MonitorCommandRequest)(nil), // 6: phelix.MonitorCommandRequest
	(*MonitorCommandResult)(nil),  // 7: phelix.MonitorCommandResult
	(*MonitorEvent)(nil),          // 8: phelix.MonitorEvent
	(*MonitorControl)(nil),        // 9: phelix.MonitorControl
	(*Pong)(nil),                  // 10: phelix.Pong
	(*Ping)(nil),                  // 11: phelix.Ping
}
var file_internal_grpc_proto_monitoring_proto_depIdxs = []int32{
	0,  // 0: phelix.MonitorLogEntry.source:type_name -> phelix.LogSource
	1,  // 1: phelix.MonitorEvent.server_info:type_name -> phelix.ServerInfo
	2,  // 2: phelix.MonitorEvent.server_metrics:type_name -> phelix.ServerMetrics
	3,  // 3: phelix.MonitorEvent.app_metrics:type_name -> phelix.AppResourceMetrics
	4,  // 4: phelix.MonitorEvent.app_info:type_name -> phelix.ApplicationInfo
	5,  // 5: phelix.MonitorEvent.log_entry:type_name -> phelix.MonitorLogEntry
	7,  // 6: phelix.MonitorEvent.command_result:type_name -> phelix.MonitorCommandResult
	10, // 7: phelix.MonitorEvent.pong:type_name -> phelix.Pong
	6,  // 8: phelix.MonitorControl.command:type_name -> phelix.MonitorCommandRequest
	11, // 9: phelix.MonitorControl.ping:type_name -> phelix.Ping
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_monitoring_proto_init() }
func file_internal_grpc_proto_monitoring_proto_init() {
	if File_internal_grpc_proto_monitoring_proto != nil {
		return
	}
	file_internal_grpc_proto_ping_proto_init()
	file_internal_grpc_proto_monitoring_proto_msgTypes[7].OneofWrappers = []any{
		(*MonitorEvent_ServerInfo)(nil),
		(*MonitorEvent_ServerMetrics)(nil),
		(*MonitorEvent_AppMetrics)(nil),
		(*MonitorEvent_AppInfo)(nil),
		(*MonitorEvent_LogEntry)(nil),
		(*MonitorEvent_CommandResult)(nil),
		(*MonitorEvent_Pong)(nil),
	}
	file_internal_grpc_proto_monitoring_proto_msgTypes[8].OneofWrappers = []any{
		(*MonitorControl_Command)(nil),
		(*MonitorControl_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_monitoring_proto_rawDesc), len(file_internal_grpc_proto_monitoring_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_monitoring_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_monitoring_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_monitoring_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_monitoring_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_monitoring_proto = out.File
	file_internal_grpc_proto_monitoring_proto_goTypes = nil
	file_internal_grpc_proto_monitoring_proto_depIdxs = nil
}
