// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/phelix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_grpc_proto_phelix_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_phelix_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/phelix.proto\x12\x06phelix\x1a internal/grpc/proto/events.proto\x1a\"internal/grpc/proto/metadata.proto\x1a\"internal/grpc/proto/envelope.proto\x1a internal/grpc/proto/health.proto2\x92\x04\n" +
	"\rPhelixService\x12>\n" +
	"\vReportEvent\x12\x18.phelix.ApplicationEvent\x1a\x15.phelix.EventResponse\x12=\n" +
	"\fSyncMetadata\x12\x13.phelix.CLIMetadata\x1a\x18.phelix.MetadataResponse\x12>\n" +
	"\fStreamEvents\x12\x18.phelix.ApplicationEvent\x1a\x10.phelix.EventAck(\x010\x01\x12A\n" +
	"\vAgentStream\x12\x16.phelix.ClientToServer\x1a\x16.phelix.ServerToClient(\x010\x01\x12O\n" +
	"\x0fHealthSetConfig\x12\x1e.phelix.HealthSetConfigRequest\x1a\x1c.phelix.HealthConfigResponse\x12S\n" +
	"\x11HealthAddEndpoint\x12 .phelix.HealthAddEndpointRequest\x1a\x1c.phelix.HealthConfigResponse\x12Y\n" +
	"\x14HealthRemoveEndpoint\x12#.phelix.HealthRemoveEndpointRequest\x1a\x1c.phelix.HealthConfigResponseB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var file_internal_grpc_proto_phelix_proto_goTypes = []any{
	(*ApplicationEvent)(nil),            // 0: phelix.ApplicationEvent
	(*CLIMetadata)(nil),                 // 1: phelix.CLIMetadata
	(*ClientToServer)(nil),              // 2: phelix.ClientToServer
	(*HealthSetConfigRequest)(nil),      // 3: phelix.HealthSetConfigRequest
	(*HealthAddEndpointRequest)(nil),    // 4: phelix.HealthAddEndpointRequest
	(*HealthRemoveEndpointRequest)(nil), // 5: phelix.HealthRemoveEndpointRequest
	(*EventResponse)(nil),               // 6: phelix.EventResponse
	(*MetadataResponse)(nil),            // 7: phelix.MetadataResponse
	(*EventAck)(nil),                    // 8: phelix.EventAck
	(*ServerToClient)(nil),              // 9: phelix.ServerToClient
	(*HealthConfigResponse)(nil),        // 10: phelix.HealthConfigResponse
}
var file_internal_grpc_proto_phelix_proto_depIdxs = []int32{
	0,  // 0: phelix.PhelixService.ReportEvent:input_type -> phelix.ApplicationEvent
	1,  // 1: phelix.PhelixService.SyncMetadata:input_type -> phelix.CLIMetadata
	0,  // 2: phelix.PhelixService.StreamEvents:input_type -> phelix.ApplicationEvent
	2,  // 3: phelix.PhelixService.AgentStream:input_type -> phelix.ClientToServer
	3,  // 4: phelix.PhelixService.HealthSetConfig:input_type -> phelix.HealthSetConfigRequest
	4,  // 5: phelix.PhelixService.HealthAddEndpoint:input_type -> phelix.HealthAddEndpointRequest
	5,  // 6: phelix.PhelixService.HealthRemoveEndpoint:input_type -> phelix.HealthRemoveEndpointRequest
	6,  // 7: phelix.PhelixService.ReportEvent:output_type -> phelix.EventResponse
	7,  // 8: phelix.PhelixService.SyncMetadata:output_type -> phelix.MetadataResponse
	8,  // 9: phelix.PhelixService.StreamEvents:output_type -> phelix.EventAck
	9,  // 10: phelix.PhelixService.AgentStream:output_type -> phelix.ServerToClient
	10, // 11: phelix.PhelixService.HealthSetConfig:output_type -> phelix.HealthConfigResponse
	10, // 12: phelix.PhelixService.HealthAddEndpoint:output_type -> phelix.HealthConfigResponse
	10, // 13: phelix.PhelixService.HealthRemoveEndpoint:output_type -> phelix.HealthConfigResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_phelix_proto_init() }
func file_internal_grpc_proto_phelix_proto_init() {
	if File_internal_grpc_proto_phelix_proto != nil {
		return
	}
	file_internal_grpc_proto_events_proto_init()
	file_internal_grpc_proto_metadata_proto_init()
	file_internal_grpc_proto_envelope_proto_init()
	file_internal_grpc_proto_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_phelix_proto_rawDesc), len(file_internal_grpc_proto_phelix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_phelix_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_phelix_proto_depIdxs,
	}.Build()
	File_internal_grpc_proto_phelix_proto = out.File
	file_internal_grpc_proto_phelix_proto_goTypes = nil
	file_internal_grpc_proto_phelix_proto_depIdxs = nil
}
