// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/grpc/proto/phelix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentLogoutRequest identifies the agent logging out. agent_id is the
// persistent Phelix runtime identity, so the backend updates the existing
// record instead of creating a new one.
type AgentLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "logout" or "auth_expired"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentLogoutRequest) Reset() {
	*x = AgentLogoutRequest{}
	mi := &file_internal_grpc_proto_phelix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLogoutRequest) ProtoMessage() {}

func (x *AgentLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_phelix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLogoutRequest.ProtoReflect.Descriptor instead.
func (*AgentLogoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_phelix_proto_rawDescGZIP(), []int{0}
}

func (x *AgentLogoutRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentLogoutRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_grpc_proto_phelix_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_phelix_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/phelix.proto\x12\x06phelix\x1a internal/grpc/proto/events.proto\x1a\"internal/grpc/proto/rollback.proto\x1a\"internal/grpc/proto/metadata.proto\x1a\"internal/grpc/proto/envelope.proto\x1a internal/grpc/proto/health.proto\x1a$internal/grpc/proto/monitoring.proto\x1a$internal/grpc/proto/deployment.proto\"G\n" +
	"\x12AgentLogoutRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xe8\a\n" +
	"\rPhelixService\x12>\n" +
	"\vReportEvent\x12\x18.phelix.ApplicationEvent\x1a\x15.phelix.EventResponse\x12=\n" +
	"\fSyncMetadata\x12\x13.phelix.CLIMetadata\x1a\x18.phelix.MetadataResponse\x12>\n" +
	"\fStreamEvents\x12\x18.phelix.ApplicationEvent\x1a\x10.phelix.EventAck(\x010\x01\x12A\n" +
	"\vAgentStream\x12\x16.phelix.ClientToServer\x1a\x16.phelix.ServerToClient(\x010\x01\x12O\n" +
	"\x0fHealthSetConfig\x12\x1e.phelix.HealthSetConfigRequest\x1a\x1c.phelix.HealthConfigResponse\x12S\n" +
	"\x11HealthAddEndpoint\x12 .phelix.HealthAddEndpointRequest\x1a\x1c.phelix.HealthConfigResponse\x12Y\n" +
	"\x14HealthRemoveEndpoint\x12#.phelix.HealthRemoveEndpointRequest\x1a\x1c.phelix.HealthConfigResponse\x12[\n" +
	"\x12ReportHealthResult\x12!.phelix.ReportHealthResultRequest\x1a\".phelix.ReportHealthResultResponse\x12X\n" +
	"\x11ReportAutoRestart\x12 .phelix.ReportAutoRestartRequest\x1a!.phelix.ReportAutoRestartResponse\x12L\n" +
	"\x13ReportRollbackEvent\x12\x1e.phelix.RollbackLifecycleEvent\x1a\x15.phelix.EventResponse\x12G\n" +
	"\x15ReportDeploymentEvent\x12\x17.phelix.DeploymentEvent\x1a\x15.phelix.EventResponse\x12A\n" +
	"\rMonitorStream\x12\x14.phelix.MonitorEvent\x1a\x16.phelix.MonitorControl(\x010\x01\x12C\n" +
	"\vAgentLogout\x12\x1a.phelix.AgentLogoutRequest\x1a\x18.phelix.MetadataResponseB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_phelix_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_phelix_proto_rawDescData []byte
)

func file_internal_grpc_proto_phelix_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_phelix_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_phelix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_phelix_proto_rawDesc), len(file_internal_grpc_proto_phelix_proto_rawDesc)))
	})
	return file_internal_grpc_proto_phelix_proto_rawDescData
}

var file_internal_grpc_proto_phelix_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_grpc_proto_phelix_proto_goTypes = []any{
	(*AgentLogoutRequest)(nil),          // 0: phelix.AgentLogoutRequest
	(*ApplicationEvent)(nil),            // 1: phelix.ApplicationEvent
	(*CLIMetadata)(nil),                 // 2: phelix.CLIMetadata
	(*ClientToServer)(nil),              // 3: phelix.ClientToServer
	(*HealthSetConfigRequest)(nil),      // 4: phelix.HealthSetConfigRequest
	(*HealthAddEndpointRequest)(nil),    // 5: phelix.HealthAddEndpointRequest
	(*HealthRemoveEndpointRequest)(nil), // 6: phelix.HealthRemoveEndpointRequest
	(*ReportHealthResultRequest)(nil),   // 7: phelix.ReportHealthResultRequest
	(*ReportAutoRestartRequest)(nil),    // 8: phelix.ReportAutoRestartRequest
	(*RollbackLifecycleEvent)(nil),      // 9: phelix.RollbackLifecycleEvent
	(*DeploymentEvent)(nil),             // 10: phelix.DeploymentEvent
	(*MonitorEvent)(nil),                // 11: phelix.MonitorEvent
	(*EventResponse)(nil),               // 12: phelix.EventResponse
	(*MetadataResponse)(nil),            // 13: phelix.MetadataResponse
	(*EventAck)(nil),                    // 14: phelix.EventAck
	(*ServerToClient)(nil),              // 15: phelix.ServerToClient
	(*HealthConfigResponse)(nil),        // 16: phelix.HealthConfigResponse
	(*ReportHealthResultResponse)(nil),  // 17: phelix.ReportHealthResultResponse
	(*ReportAutoRestartResponse)(nil),   // 18: phelix.ReportAutoRestartResponse
	(*MonitorControl)(nil),              // 19: phelix.MonitorControl
}
var file_internal_grpc_proto_phelix_proto_depIdxs = []int32{
	1,  // 0: phelix.PhelixService.ReportEvent:input_type -> phelix.ApplicationEvent
	2,  // 1: phelix.PhelixService.SyncMetadata:input_type -> phelix.CLIMetadata
	1,  // 2: phelix.PhelixService.StreamEvents:input_type -> phelix.ApplicationEvent
	3,  // 3: phelix.PhelixService.AgentStream:input_type -> phelix.ClientToServer
	4,  // 4: phelix.PhelixService.HealthSetConfig:input_type -> phelix.HealthSetConfigRequest
	5,  // 5: phelix.PhelixService.HealthAddEndpoint:input_type -> phelix.HealthAddEndpointRequest
	6,  // 6: phelix.PhelixService.HealthRemoveEndpoint:input_type -> phelix.HealthRemoveEndpointRequest
	7,  // 7: phelix.PhelixService.ReportHealthResult:input_type -> phelix.ReportHealthResultRequest
	8,  // 8: phelix.PhelixService.ReportAutoRestart:input_type -> phelix.ReportAutoRestartRequest
	9,  // 9: phelix.PhelixService.ReportRollbackEvent:input_type -> phelix.RollbackLifecycleEvent
	10, // 10: phelix.PhelixService.ReportDeploymentEvent:input_type -> phelix.DeploymentEvent
	11, // 11: phelix.PhelixService.MonitorStream:input_type -> phelix.MonitorEvent
	0,  // 12: phelix.PhelixService.AgentLogout:input_type -> phelix.AgentLogoutRequest
	12, // 13: phelix.PhelixService.ReportEvent:output_type -> phelix.EventResponse
	13, // 14: phelix.PhelixService.SyncMetadata:output_type -> phelix.MetadataResponse
	14, // 15: phelix.PhelixService.StreamEvents:output_type -> phelix.EventAck
	15, // 16: phelix.PhelixService.AgentStream:output_type -> phelix.ServerToClient
	16, // 17: phelix.PhelixService.HealthSetConfig:output_type -> phelix.HealthConfigResponse
	16, // 18: phelix.PhelixService.HealthAddEndpoint:output_type -> phelix.HealthConfigResponse
	16, // 19: phelix.PhelixService.HealthRemoveEndpoint:output_type -> phelix.HealthConfigResponse
	17, // 20: phelix.PhelixService.ReportHealthResult:output_type -> phelix.ReportHealthResultResponse
	18, // 21: phelix.PhelixService.ReportAutoRestart:output_type -> phelix.ReportAutoRestartResponse
	12, // 22: phelix.PhelixService.ReportRollbackEvent:output_type -> phelix.EventResponse
	12, // 23: phelix.PhelixService.ReportDeploymentEvent:output_type -> phelix.EventResponse
	19, // 24: phelix.PhelixService.MonitorStream:output_type -> phelix.MonitorControl
	13, // 25: phelix.PhelixService.AgentLogout:output_type -> phelix.MetadataResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_phelix_proto_init() }
func file_internal_grpc_proto_phelix_proto_init() {
	if File_internal_grpc_proto_phelix_proto != nil {
		return
	}
	file_internal_grpc_proto_events_proto_init()
	file_internal_grpc_proto_rollback_proto_init()
	file_internal_grpc_proto_metadata_proto_init()
	file_internal_grpc_proto_envelope_proto_init()
	file_internal_grpc_proto_health_proto_init()
	file_internal_grpc_proto_monitoring_proto_init()
	file_internal_grpc_proto_deployment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_phelix_proto_rawDesc), len(file_internal_grpc_proto_phelix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_phelix_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_phelix_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_phelix_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_phelix_proto = out.File
	file_internal_grpc_proto_phelix_proto_goTypes = nil
	file_internal_grpc_proto_phelix_proto_depIdxs = nil
}
