// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/grpc/proto/phelix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhelixService_ReportEvent_FullMethodName  = "/phelix.PhelixService/ReportEvent"
	PhelixService_SyncMetadata_FullMethodName = "/phelix.PhelixService/SyncMetadata"
	PhelixService_StreamEvents_FullMethodName = "/phelix.PhelixService/StreamEvents"
	PhelixService_AgentStream_FullMethodName  = "/phelix.PhelixService/AgentStream"
)

// PhelixServiceClient is the client API for PhelixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PhelixService is the main service for CLI-to-backend communication.
type PhelixServiceClient interface {
	// ReportEvent sends an application lifecycle event to the backend.
	ReportEvent(ctx context.Context, in *ApplicationEvent, opts ...grpc.CallOption) (*EventResponse, error)
	// SyncMetadata streams CLI metadata to the backend (unary, called periodically).
	SyncMetadata(ctx context.Context, in *CLIMetadata, opts ...grpc.CallOption) (*MetadataResponse, error)
	// StreamEvents opens a bidirectional stream for continuous event reporting.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplicationEvent, EventAck], error)
	// AgentStream is the bidirectional stream for backend-to-CLI commands.
	// The backend sends health commands, remote executions, and other requests.
	// The CLI processes them locally and returns results through the same stream.
	// This works through NAT/firewalls because the CLI initiates the connection.
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToServer, ServerToClient], error)
}

type phelixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhelixServiceClient(cc grpc.ClientConnInterface) PhelixServiceClient {
	return &phelixServiceClient{cc}
}

func (c *phelixServiceClient) ReportEvent(ctx context.Context, in *ApplicationEvent, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, PhelixService_ReportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phelixServiceClient) SyncMetadata(ctx context.Context, in *CLIMetadata, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, PhelixService_SyncMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phelixServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ApplicationEvent, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PhelixService_ServiceDesc.Streams[0], PhelixService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplicationEvent, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhelixService_StreamEventsClient = grpc.BidiStreamingClient[ApplicationEvent, EventAck]

func (c *phelixServiceClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToServer, ServerToClient], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PhelixService_ServiceDesc.Streams[1], PhelixService_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientToServer, ServerToClient]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhelixService_AgentStreamClient = grpc.BidiStreamingClient[ClientToServer, ServerToClient]

// PhelixServiceServer is the server API for PhelixService service.
// All implementations must embed UnimplementedPhelixServiceServer
// for forward compatibility.
//
// PhelixService is the main service for CLI-to-backend communication.
type PhelixServiceServer interface {
	// ReportEvent sends an application lifecycle event to the backend.
	ReportEvent(context.Context, *ApplicationEvent) (*EventResponse, error)
	// SyncMetadata streams CLI metadata to the backend (unary, called periodically).
	SyncMetadata(context.Context, *CLIMetadata) (*MetadataResponse, error)
	// StreamEvents opens a bidirectional stream for continuous event reporting.
	StreamEvents(grpc.BidiStreamingServer[ApplicationEvent, EventAck]) error
	// AgentStream is the bidirectional stream for backend-to-CLI commands.
	// The backend sends health commands, remote executions, and other requests.
	// The CLI processes them locally and returns results through the same stream.
	// This works through NAT/firewalls because the CLI initiates the connection.
	AgentStream(grpc.BidiStreamingServer[ClientToServer, ServerToClient]) error
	mustEmbedUnimplementedPhelixServiceServer()
}

// UnimplementedPhelixServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhelixServiceServer struct{}

func (UnimplementedPhelixServiceServer) ReportEvent(context.Context, *ApplicationEvent) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedPhelixServiceServer) SyncMetadata(context.Context, *CLIMetadata) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMetadata not implemented")
}
func (UnimplementedPhelixServiceServer) StreamEvents(grpc.BidiStreamingServer[ApplicationEvent, EventAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedPhelixServiceServer) AgentStream(grpc.BidiStreamingServer[ClientToServer, ServerToClient]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedPhelixServiceServer) mustEmbedUnimplementedPhelixServiceServer() {}
func (UnimplementedPhelixServiceServer) testEmbeddedByValue()                       {}

// UnsafePhelixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhelixServiceServer will
// result in compilation errors.
type UnsafePhelixServiceServer interface {
	mustEmbedUnimplementedPhelixServiceServer()
}

func RegisterPhelixServiceServer(s grpc.ServiceRegistrar, srv PhelixServiceServer) {
	// If the following call panics, it indicates UnimplementedPhelixServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhelixService_ServiceDesc, srv)
}

func _PhelixService_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhelixServiceServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhelixService_ReportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhelixServiceServer).ReportEvent(ctx, req.(*ApplicationEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhelixService_SyncMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLIMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhelixServiceServer).SyncMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhelixService_SyncMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhelixServiceServer).SyncMetadata(ctx, req.(*CLIMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhelixService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhelixServiceServer).StreamEvents(&grpc.GenericServerStream[ApplicationEvent, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhelixService_StreamEventsServer = grpc.BidiStreamingServer[ApplicationEvent, EventAck]

func _PhelixService_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhelixServiceServer).AgentStream(&grpc.GenericServerStream[ClientToServer, ServerToClient]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PhelixService_AgentStreamServer = grpc.BidiStreamingServer[ClientToServer, ServerToClient]

// PhelixService_ServiceDesc is the grpc.ServiceDesc for PhelixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhelixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phelix.PhelixService",
	HandlerType: (*PhelixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportEvent",
			Handler:    _PhelixService_ReportEvent_Handler,
		},
		{
			MethodName: "SyncMetadata",
			Handler:    _PhelixService_SyncMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _PhelixService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AgentStream",
			Handler:       _PhelixService_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/phelix.proto",
}
