// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/ping.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ping is a keepalive ping from backend.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_ping_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong is a keepalive response from CLI.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_ping_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CancelRequest tells the CLI to cancel an ongoing operation.
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_ping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_ping_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_internal_grpc_proto_ping_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_ping_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/grpc/proto/ping.proto\x12\x06phelix\"4\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"4\n" +
	"\x04Pong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestIdB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_ping_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_ping_proto_rawDescData []byte
)

func file_internal_grpc_proto_ping_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_ping_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_ping_proto_rawDesc), len(file_internal_grpc_proto_ping_proto_rawDesc)))
	})
	return file_internal_grpc_proto_ping_proto_rawDescData
}

var file_internal_grpc_proto_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_proto_ping_proto_goTypes = []any{
	(*Ping)(nil),          // 0: phelix.Ping
	(*Pong)(nil),          // 1: phelix.Pong
	(*CancelRequest)(nil), // 2: phelix.CancelRequest
}
var file_internal_grpc_proto_ping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_ping_proto_init() }
func file_internal_grpc_proto_ping_proto_init() {
	if File_internal_grpc_proto_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_ping_proto_rawDesc), len(file_internal_grpc_proto_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_ping_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_ping_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_ping_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_ping_proto = out.File
	file_internal_grpc_proto_ping_proto_goTypes = nil
	file_internal_grpc_proto_ping_proto_depIdxs = nil
}
