// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/rollback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RollbackLifecycleEvent reports a single step in the rollback execution
// lifecycle. The backend receives a stream of these events to reconstruct
// the full rollback timeline, display real-time progress, generate an audit
// trail, and diagnose failures.
type RollbackLifecycleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	ServerId      string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CliAppId      string `protobuf:"bytes,2,opt,name=cli_app_id,json=cliAppId,proto3" json:"cli_app_id,omitempty"`
	ResolvedAppId string `protobuf:"bytes,3,opt,name=resolved_app_id,json=resolvedAppId,proto3" json:"resolved_app_id,omitempty"`
	AppName       string `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Rollback configuration
	DeploymentMode   string `protobuf:"bytes,5,opt,name=deployment_mode,json=deploymentMode,proto3" json:"deployment_mode,omitempty"`
	RollbackStrategy string `protobuf:"bytes,6,opt,name=rollback_strategy,json=rollbackStrategy,proto3" json:"rollback_strategy,omitempty"`
	// Versioning
	CurrentVersion string `protobuf:"bytes,7,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	TargetVersion  string `protobuf:"bytes,8,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	TargetTag      string `protobuf:"bytes,9,opt,name=target_tag,json=targetTag,proto3" json:"target_tag,omitempty"`
	// Execution state
	CurrentStep string `protobuf:"bytes,10,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Success     bool   `protobuf:"varint,11,opt,name=success,proto3" json:"success,omitempty"`
	Message     string `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	Error       string `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	// Timestamps and timing
	Timestamp  int64 `protobuf:"varint,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DurationMs int64 `protobuf:"varint,15,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Process context
	Pid int32 `protobuf:"varint,16,opt,name=pid,proto3" json:"pid,omitempty"`
	// Auth identity
	UserId       string `protobuf:"bytes,17,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken string `protobuf:"bytes,18,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Version list (populated on --list events)
	Versions []*RollbackVersionEntry `protobuf:"bytes,19,rep,name=versions,proto3" json:"versions,omitempty"`
	// Arbitrary key-value metadata for future extensibility.
	Metadata map[string]string `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Structured phelix error code for failed terminal events ("failed",
	// "verify_failed", "verify_cancelled"), taken from internal/errors/codes.go
	// (e.g. ROLLBACK_FAILED, ROLLBACK_VERIFY_FAILED, ROLLBACK_TARGET_NOT_FOUND,
	// DEPLOY_LOCKED). Empty on success and on non-terminal steps. The free-form
	// `error` field carries the human-readable message; this field is the
	// machine-readable classification and must never be inferred from `error`.
	ErrorCode string `protobuf:"bytes,21,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Operator-supplied rollback reason, already validated by the CLI: trimmed,
	// internal whitespace collapsed, at most 500 characters. Empty = no reason
	// was supplied (absent and explicitly-empty are both "no reason" by the
	// time they reach the wire — the CLI rejects an explicit empty reason).
	// Canonical representation; supersedes the legacy metadata key
	// "rollback_reason".
	Reason string `protobuf:"bytes,22,opt,name=reason,proto3" json:"reason,omitempty"`
	// Post-rollback stability verification (--verify). verify_requested=false
	// means verification was not requested; fields 24-26 are then unused and
	// must be treated as unset regardless of their wire values.
	VerifyRequested bool `protobuf:"varint,23,opt,name=verify_requested,json=verifyRequested,proto3" json:"verify_requested,omitempty"`
	// Requested observation window in milliseconds (e.g. 30s → 30000). The
	// window is the whole observation period, not one probe.
	VerifyDurationMs int64 `protobuf:"varint,24,opt,name=verify_duration_ms,json=verifyDurationMs,proto3" json:"verify_duration_ms,omitempty"`
	// Outcome, set once verification concludes: "passed" | "failed" |
	// "cancelled". Empty while the rollback is still executing. A rollback is
	// fully successful only when success=true AND verify_status is empty or
	// "passed" — ROLLBACK_VERIFY_FAILED is reported via error_code on the
	// terminal verification event, never via success=false on `complete`.
	VerifyStatus string `protobuf:"bytes,25,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`
	// Failure/cancellation detail; empty when passed or not requested.
	VerifyError string `protobuf:"bytes,26,opt,name=verify_error,json=verifyError,proto3" json:"verify_error,omitempty"`
	// How the rollback target was chosen: "explicit" (--to flag),
	// "interactive" (picker selection), or "previous" (no target given — the
	// CLI resolved current-1). Empty on non-execution events (list, preview,
	// history). The backend must not infer this from target_version.
	TargetSource string `protobuf:"bytes,27,opt,name=target_source,json=targetSource,proto3" json:"target_source,omitempty"`
	// True for dry-run preview events. A preview event is a read-only report:
	// the CLI emits it from the dry-run path, which never mutates process,
	// proxy, deployment, version, symlink or audit state.
	DryRun bool `protobuf:"varint,28,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Structured rollback preview, set only when dry_run=true. Mirrors the
	// CLI's RollbackPlan (internal/deploy/rollback_plan.go) minus local
	// filesystem paths, which the backend has no use for.
	Preview *RollbackPreview `protobuf:"bytes,29,opt,name=preview,proto3" json:"preview,omitempty"`
	// Structured rollback history records, set only on "history" events. Each
	// entry mirrors one line of the per-app rollback_history.jsonl; the mode is
	// the strategy actually used for that rollback, not the app's current mode.
	History []*RollbackHistoryEntry `protobuf:"bytes,30,rep,name=history,proto3" json:"history,omitempty"`
	// Rollback origin: "manual" (operator-invoked) or "automatic"
	// (post-failed-deploy recovery). Empty means "manual" (written by agents
	// before this field existed). The backend must persist this so history can
	// distinguish operator rollbacks from recoveries.
	Source string `protobuf:"bytes,31,opt,name=source,proto3" json:"source,omitempty"`
	// Backend command correlation id. Typed field for new consumers; metadata
	// key "request_id" remains a compatibility fallback for older integrations.
	RequestId     string `protobuf:"bytes,32,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackLifecycleEvent) Reset() {
	*x = RollbackLifecycleEvent{}
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackLifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackLifecycleEvent) ProtoMessage() {}

func (x *RollbackLifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackLifecycleEvent.ProtoReflect.Descriptor instead.
func (*RollbackLifecycleEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rollback_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackLifecycleEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetCliAppId() string {
	if x != nil {
		return x.CliAppId
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetResolvedAppId() string {
	if x != nil {
		return x.ResolvedAppId
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetDeploymentMode() string {
	if x != nil {
		return x.DeploymentMode
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetRollbackStrategy() string {
	if x != nil {
		return x.RollbackStrategy
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetTargetTag() string {
	if x != nil {
		return x.TargetTag
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackLifecycleEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RollbackLifecycleEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RollbackLifecycleEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RollbackLifecycleEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetVersions() []*RollbackVersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *RollbackLifecycleEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RollbackLifecycleEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetVerifyRequested() bool {
	if x != nil {
		return x.VerifyRequested
	}
	return false
}

func (x *RollbackLifecycleEvent) GetVerifyDurationMs() int64 {
	if x != nil {
		return x.VerifyDurationMs
	}
	return 0
}

func (x *RollbackLifecycleEvent) GetVerifyStatus() string {
	if x != nil {
		return x.VerifyStatus
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetVerifyError() string {
	if x != nil {
		return x.VerifyError
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetTargetSource() string {
	if x != nil {
		return x.TargetSource
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RollbackLifecycleEvent) GetPreview() *RollbackPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

func (x *RollbackLifecycleEvent) GetHistory() []*RollbackHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RollbackLifecycleEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RollbackLifecycleEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// RollbackPreview is the structured dry-run output. All fields are read-only
// observations of the app's current deployment state.
type RollbackPreview struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppName        string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // 0 when unknown
	CurrentTag     string                 `protobuf:"bytes,3,opt,name=current_tag,json=currentTag,proto3" json:"current_tag,omitempty"`              // empty = no tag
	CurrentCommit  string                 `protobuf:"bytes,4,opt,name=current_commit,json=currentCommit,proto3" json:"current_commit,omitempty"`
	CurrentSize    int64                  `protobuf:"varint,5,opt,name=current_size,json=currentSize,proto3" json:"current_size,omitempty"` // bytes; 0 when unknown
	TargetVersion  int32                  `protobuf:"varint,6,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	TargetTag      string                 `protobuf:"bytes,7,opt,name=target_tag,json=targetTag,proto3" json:"target_tag,omitempty"`
	TargetCommit   string                 `protobuf:"bytes,8,opt,name=target_commit,json=targetCommit,proto3" json:"target_commit,omitempty"`
	TargetBuiltAt  int64                  `protobuf:"varint,9,opt,name=target_built_at,json=targetBuiltAt,proto3" json:"target_built_at,omitempty"` // unix millis; 0 = unknown
	TargetSize     int64                  `protobuf:"varint,10,opt,name=target_size,json=targetSize,proto3" json:"target_size,omitempty"`           // bytes
	// "classic" | "blue-green" | "rolling" — the strategy the rollback would use.
	Strategy             string `protobuf:"bytes,11,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Replicas             int32  `protobuf:"varint,12,opt,name=replicas,proto3" json:"replicas,omitempty"`                          // rolling only
	PublicPort           int32  `protobuf:"varint,13,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`    // proxy public port; 0 = n/a
	CurrentSlot          string `protobuf:"bytes,14,opt,name=current_slot,json=currentSlot,proto3" json:"current_slot,omitempty"`  // blue-green only; empty = n/a
	TargetSlot           string `protobuf:"bytes,15,opt,name=target_slot,json=targetSlot,proto3" json:"target_slot,omitempty"`     // blue-green only
	CurrentPort          int32  `protobuf:"varint,16,opt,name=current_port,json=currentPort,proto3" json:"current_port,omitempty"` // current instance internal port; 0 = n/a
	HealthCheck          string `protobuf:"bytes,17,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`  // human-readable tier summary
	Downtime             bool   `protobuf:"varint,18,opt,name=downtime,proto3" json:"downtime,omitempty"`                          // true for classic stop→start
	EnvSnapshotAvailable bool   `protobuf:"varint,19,opt,name=env_snapshot_available,json=envSnapshotAvailable,proto3" json:"env_snapshot_available,omitempty"`
	EnvSummary           string `protobuf:"bytes,20,opt,name=env_summary,json=envSummary,proto3" json:"env_summary,omitempty"`
	// Ordered plan steps the CLI would execute, and warnings about the plan.
	Steps         []string `protobuf:"bytes,21,rep,name=steps,proto3" json:"steps,omitempty"`
	Warnings      []string `protobuf:"bytes,22,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPreview) Reset() {
	*x = RollbackPreview{}
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPreview) ProtoMessage() {}

func (x *RollbackPreview) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPreview.ProtoReflect.Descriptor instead.
func (*RollbackPreview) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rollback_proto_rawDescGZIP(), []int{1}
}

func (x *RollbackPreview) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RollbackPreview) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *RollbackPreview) GetCurrentTag() string {
	if x != nil {
		return x.CurrentTag
	}
	return ""
}

func (x *RollbackPreview) GetCurrentCommit() string {
	if x != nil {
		return x.CurrentCommit
	}
	return ""
}

func (x *RollbackPreview) GetCurrentSize() int64 {
	if x != nil {
		return x.CurrentSize
	}
	return 0
}

func (x *RollbackPreview) GetTargetVersion() int32 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *RollbackPreview) GetTargetTag() string {
	if x != nil {
		return x.TargetTag
	}
	return ""
}

func (x *RollbackPreview) GetTargetCommit() string {
	if x != nil {
		return x.TargetCommit
	}
	return ""
}

func (x *RollbackPreview) GetTargetBuiltAt() int64 {
	if x != nil {
		return x.TargetBuiltAt
	}
	return 0
}

func (x *RollbackPreview) GetTargetSize() int64 {
	if x != nil {
		return x.TargetSize
	}
	return 0
}

func (x *RollbackPreview) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RollbackPreview) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *RollbackPreview) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *RollbackPreview) GetCurrentSlot() string {
	if x != nil {
		return x.CurrentSlot
	}
	return ""
}

func (x *RollbackPreview) GetTargetSlot() string {
	if x != nil {
		return x.TargetSlot
	}
	return ""
}

func (x *RollbackPreview) GetCurrentPort() int32 {
	if x != nil {
		return x.CurrentPort
	}
	return 0
}

func (x *RollbackPreview) GetHealthCheck() string {
	if x != nil {
		return x.HealthCheck
	}
	return ""
}

func (x *RollbackPreview) GetDowntime() bool {
	if x != nil {
		return x.Downtime
	}
	return false
}

func (x *RollbackPreview) GetEnvSnapshotAvailable() bool {
	if x != nil {
		return x.EnvSnapshotAvailable
	}
	return false
}

func (x *RollbackPreview) GetEnvSummary() string {
	if x != nil {
		return x.EnvSummary
	}
	return ""
}

func (x *RollbackPreview) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RollbackPreview) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// RollbackHistoryEntry mirrors one record of the agent's structured rollback
// history (rollback_history.jsonl). Timestamps are unix millis.
type RollbackHistoryEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Time        int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	FromVersion string                 `protobuf:"bytes,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"` // "vN" (the failed/deployed version automatic rollbacks recover from)
	ToVersion   string                 `protobuf:"bytes,3,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`       // "vN"
	Status      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                              // "success" | "failed" — EXECUTION outcome only
	Mode        string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`                                  // "classic" | "blue-green" | "rolling" — what actually happened
	Reason      string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                              // validated operator reason; empty = none
	Source      string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`                              // "manual" | "automatic"
	Error       string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                                // execution failure detail; empty on success
	// Verification sub-record, matching the semantics of fields 23-26 above:
	// empty verify_status = not requested; "passed" | "failed" | "cancelled".
	VerifyStatus   string `protobuf:"bytes,9,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`
	VerifyDuration string `protobuf:"bytes,10,opt,name=verify_duration,json=verifyDuration,proto3" json:"verify_duration,omitempty"` // Go duration string, e.g. "30s", "2m30s"
	VerifyError    string `protobuf:"bytes,11,opt,name=verify_error,json=verifyError,proto3" json:"verify_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackHistoryEntry) Reset() {
	*x = RollbackHistoryEntry{}
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackHistoryEntry) ProtoMessage() {}

func (x *RollbackHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackHistoryEntry.ProtoReflect.Descriptor instead.
func (*RollbackHistoryEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rollback_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackHistoryEntry) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RollbackHistoryEntry) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *RollbackHistoryEntry) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

func (x *RollbackHistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RollbackHistoryEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RollbackHistoryEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RollbackHistoryEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RollbackHistoryEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RollbackHistoryEntry) GetVerifyStatus() string {
	if x != nil {
		return x.VerifyStatus
	}
	return ""
}

func (x *RollbackHistoryEntry) GetVerifyDuration() string {
	if x != nil {
		return x.VerifyDuration
	}
	return ""
}

func (x *RollbackHistoryEntry) GetVerifyError() string {
	if x != nil {
		return x.VerifyError
	}
	return ""
}

// RollbackVersionEntry describes one retained version in the --list output.
type RollbackVersionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Tag            string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	GitCommit      string                 `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	BuildTimestamp int64                  `protobuf:"varint,4,opt,name=build_timestamp,json=buildTimestamp,proto3" json:"build_timestamp,omitempty"`
	BinarySize     int64                  `protobuf:"varint,5,opt,name=binary_size,json=binarySize,proto3" json:"binary_size,omitempty"`
	Current        bool                   `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	PruneSoon      bool                   `protobuf:"varint,7,opt,name=prune_soon,json=pruneSoon,proto3" json:"prune_soon,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackVersionEntry) Reset() {
	*x = RollbackVersionEntry{}
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackVersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionEntry) ProtoMessage() {}

func (x *RollbackVersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rollback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionEntry.ProtoReflect.Descriptor instead.
func (*RollbackVersionEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rollback_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackVersionEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackVersionEntry) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RollbackVersionEntry) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *RollbackVersionEntry) GetBuildTimestamp() int64 {
	if x != nil {
		return x.BuildTimestamp
	}
	return 0
}

func (x *RollbackVersionEntry) GetBinarySize() int64 {
	if x != nil {
		return x.BinarySize
	}
	return 0
}

func (x *RollbackVersionEntry) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *RollbackVersionEntry) GetPruneSoon() bool {
	if x != nil {
		return x.PruneSoon
	}
	return false
}

var File_internal_grpc_proto_rollback_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_rollback_proto_rawDesc = "" +
	"\n" +
	"\"internal/grpc/proto/rollback.proto\x12\x06phelix\"\xd0\t\n" +
	"\x16RollbackLifecycleEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\n" +
	"cli_app_id\x18\x02 \x01(\tR\bcliAppId\x12&\n" +
	"\x0fresolved_app_id\x18\x03 \x01(\tR\rresolvedAppId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12'\n" +
	"\x0fdeployment_mode\x18\x05 \x01(\tR\x0edeploymentMode\x12+\n" +
	"\x11rollback_strategy\x18\x06 \x01(\tR\x10rollbackStrategy\x12'\n" +
	"\x0fcurrent_version\x18\a \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0etarget_version\x18\b \x01(\tR\rtargetVersion\x12\x1d\n" +
	"\n" +
	"target_tag\x18\t \x01(\tR\ttargetTag\x12!\n" +
	"\fcurrent_step\x18\n" +
	" \x01(\tR\vcurrentStep\x12\x18\n" +
	"\asuccess\x18\v \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x0e \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vduration_ms\x18\x0f \x01(\x03R\n" +
	"durationMs\x12\x10\n" +
	"\x03pid\x18\x10 \x01(\x05R\x03pid\x12\x17\n" +
	"\auser_id\x18\x11 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x12 \x01(\tR\fsessionToken\x128\n" +
	"\bversions\x18\x13 \x03(\v2\x1c.phelix.RollbackVersionEntryR\bversions\x12H\n" +
	"\bmetadata\x18\x14 \x03(\v2,.phelix.RollbackLifecycleEvent.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"error_code\x18\x15 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06reason\x18\x16 \x01(\tR\x06reason\x12)\n" +
	"\x10verify_requested\x18\x17 \x01(\bR\x0fverifyRequested\x12,\n" +
	"\x12verify_duration_ms\x18\x18 \x01(\x03R\x10verifyDurationMs\x12#\n" +
	"\rverify_status\x18\x19 \x01(\tR\fverifyStatus\x12!\n" +
	"\fverify_error\x18\x1a \x01(\tR\vverifyError\x12#\n" +
	"\rtarget_source\x18\x1b \x01(\tR\ftargetSource\x12\x17\n" +
	"\adry_run\x18\x1c \x01(\bR\x06dryRun\x121\n" +
	"\apreview\x18\x1d \x01(\v2\x17.phelix.RollbackPreviewR\apreview\x126\n" +
	"\ahistory\x18\x1e \x03(\v2\x1c.phelix.RollbackHistoryEntryR\ahistory\x12\x16\n" +
	"\x06source\x18\x1f \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18  \x01(\tR\trequestId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x05\n" +
	"\x0fRollbackPreview\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x05R\x0ecurrentVersion\x12\x1f\n" +
	"\vcurrent_tag\x18\x03 \x01(\tR\n" +
	"currentTag\x12%\n" +
	"\x0ecurrent_commit\x18\x04 \x01(\tR\rcurrentCommit\x12!\n" +
	"\fcurrent_size\x18\x05 \x01(\x03R\vcurrentSize\x12%\n" +
	"\x0etarget_version\x18\x06 \x01(\x05R\rtargetVersion\x12\x1d\n" +
	"\n" +
	"target_tag\x18\a \x01(\tR\ttargetTag\x12#\n" +
	"\rtarget_commit\x18\b \x01(\tR\ftargetCommit\x12&\n" +
	"\x0ftarget_built_at\x18\t \x01(\x03R\rtargetBuiltAt\x12\x1f\n" +
	"\vtarget_size\x18\n" +
	" \x01(\x03R\n" +
	"targetSize\x12\x1a\n" +
	"\bstrategy\x18\v \x01(\tR\bstrategy\x12\x1a\n" +
	"\breplicas\x18\f \x01(\x05R\breplicas\x12\x1f\n" +
	"\vpublic_port\x18\r \x01(\x05R\n" +
	"publicPort\x12!\n" +
	"\fcurrent_slot\x18\x0e \x01(\tR\vcurrentSlot\x12\x1f\n" +
	"\vtarget_slot\x18\x0f \x01(\tR\n" +
	"targetSlot\x12!\n" +
	"\fcurrent_port\x18\x10 \x01(\x05R\vcurrentPort\x12!\n" +
	"\fhealth_check\x18\x11 \x01(\tR\vhealthCheck\x12\x1a\n" +
	"\bdowntime\x18\x12 \x01(\bR\bdowntime\x124\n" +
	"\x16env_snapshot_available\x18\x13 \x01(\bR\x14envSnapshotAvailable\x12\x1f\n" +
	"\venv_summary\x18\x14 \x01(\tR\n" +
	"envSummary\x12\x14\n" +
	"\x05steps\x18\x15 \x03(\tR\x05steps\x12\x1a\n" +
	"\bwarnings\x18\x16 \x03(\tR\bwarnings\"\xcf\x02\n" +
	"\x14RollbackHistoryEntry\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x03 \x01(\tR\ttoVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12#\n" +
	"\rverify_status\x18\t \x01(\tR\fverifyStatus\x12'\n" +
	"\x0fverify_duration\x18\n" +
	" \x01(\tR\x0everifyDuration\x12!\n" +
	"\fverify_error\x18\v \x01(\tR\vverifyError\"\xe4\x01\n" +
	"\x14RollbackVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x03 \x01(\tR\tgitCommit\x12'\n" +
	"\x0fbuild_timestamp\x18\x04 \x01(\x03R\x0ebuildTimestamp\x12\x1f\n" +
	"\vbinary_size\x18\x05 \x01(\x03R\n" +
	"binarySize\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\bR\acurrent\x12\x1d\n" +
	"\n" +
	"prune_soon\x18\a \x01(\bR\tpruneSoonB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_rollback_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_rollback_proto_rawDescData []byte
)

func file_internal_grpc_proto_rollback_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_rollback_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_rollback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_rollback_proto_rawDesc), len(file_internal_grpc_proto_rollback_proto_rawDesc)))
	})
	return file_internal_grpc_proto_rollback_proto_rawDescData
}

var file_internal_grpc_proto_rollback_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_grpc_proto_rollback_proto_goTypes = []any{
	(*RollbackLifecycleEvent)(nil), // 0: phelix.RollbackLifecycleEvent
	(*RollbackPreview)(nil),        // 1: phelix.RollbackPreview
	(*RollbackHistoryEntry)(nil),   // 2: phelix.RollbackHistoryEntry
	(*RollbackVersionEntry)(nil),   // 3: phelix.RollbackVersionEntry
	nil,                            // 4: phelix.RollbackLifecycleEvent.MetadataEntry
}
var file_internal_grpc_proto_rollback_proto_depIdxs = []int32{
	3, // 0: phelix.RollbackLifecycleEvent.versions:type_name -> phelix.RollbackVersionEntry
	4, // 1: phelix.RollbackLifecycleEvent.metadata:type_name -> phelix.RollbackLifecycleEvent.MetadataEntry
	1, // 2: phelix.RollbackLifecycleEvent.preview:type_name -> phelix.RollbackPreview
	2, // 3: phelix.RollbackLifecycleEvent.history:type_name -> phelix.RollbackHistoryEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_rollback_proto_init() }
func file_internal_grpc_proto_rollback_proto_init() {
	if File_internal_grpc_proto_rollback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_rollback_proto_rawDesc), len(file_internal_grpc_proto_rollback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_rollback_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_rollback_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_rollback_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_rollback_proto = out.File
	file_internal_grpc_proto_rollback_proto_goTypes = nil
	file_internal_grpc_proto_rollback_proto_depIdxs = nil
}
