// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/proto/webhook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebhookOptions carries the options of a webhook_* command. Every field is
// command-scoped: enabled belongs to webhook_enable/webhook_disable, branch
// to webhook_set_branch, secret_env to webhook_set_secret_env, and limit
// bounds webhook_history / webhook_deliveries answers. A field set on a
// command it does not belong to is rejected with INVALID_ARGUMENT rather
// than ignored.
type WebhookOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target state of webhook_enable (true) / webhook_disable (false). The
	// command type already names the direction; this field is optional
	// confirmation and must agree with it when set.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Bare branch name (e.g. "main", never "refs/heads/main") for
	// webhook_set_branch. Validated on the agent by the same rules as the
	// phelix.yaml webhook.branch key.
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// NAME of the environment variable holding the HMAC shared secret (e.g.
	// "PHELIX_WEBHOOK_SECRET") for webhook_set_secret_env. Validated as an
	// environment-variable name. The secret value itself never appears on the
	// wire in any message.
	SecretEnv string `protobuf:"bytes,3,opt,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"`
	// Maximum number of records to return for webhook_history /
	// webhook_deliveries. 0 = the agent default (20); the agent caps it at
	// 100. Ignored by webhook_status (active jobs are few by construction).
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookOptions) Reset() {
	*x = WebhookOptions{}
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookOptions) ProtoMessage() {}

func (x *WebhookOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookOptions.ProtoReflect.Descriptor instead.
func (*WebhookOptions) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WebhookOptions) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WebhookOptions) GetSecretEnv() string {
	if x != nil {
		return x.SecretEnv
	}
	return ""
}

func (x *WebhookOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// WebhookJob is one durable webhook deployment job, as stored by the agent
// (the same records `phelix webhook status`/`history` read). Only fields of
// the existing job model are exposed — no secrets, no request bodies, no
// worktree paths. Timestamps are unix milliseconds.
type WebhookJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                // wh_… agent-side job identifier
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"` // provider delivery identifier (replay key)
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit        string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"` // exact pushed commit that was deployed
	Provider      string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Stage         string                 `protobuf:"bytes,9,opt,name=stage,proto3" json:"stage,omitempty"`
	AcceptedAt    int64                  `protobuf:"varint,10,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Version       int32                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`                              // Phelix version deployed (or restored, when rolled back); 0 = none
	ErrorCode     string                 `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`          // machine-readable (e.g. GIT_SYNC_FAILED, WEBHOOK_JOB_INTERRUPTED)
	ErrorMessage  string                 `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // sanitized human summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookJob) Reset() {
	*x = WebhookJob{}
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookJob) ProtoMessage() {}

func (x *WebhookJob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookJob.ProtoReflect.Descriptor instead.
func (*WebhookJob) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *WebhookJob) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *WebhookJob) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WebhookJob) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *WebhookJob) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WebhookJob) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *WebhookJob) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookJob) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *WebhookJob) GetAcceptedAt() int64 {
	if x != nil {
		return x.AcceptedAt
	}
	return 0
}

func (x *WebhookJob) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *WebhookJob) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *WebhookJob) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WebhookJob) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *WebhookJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// WebhookConfigState is the app's webhook configuration as the agent reads
// it from the app's phelix.yaml — the same source of truth local webhook
// execution uses. Mutating commands return the resulting state so the
// backend can reconcile without a follow-up query.
type WebhookConfigState struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Branch  string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// Environment-variable NAME only. The HMAC secret value is never
	// transmitted; it stays in the agent host's environment.
	SecretEnv string `protobuf:"bytes,3,opt,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty"`
	// Whether the agent process currently sees the secret_env variable set:
	// "configured" | "missing" | "" (no secret_env configured). Reported for
	// operator guidance only — the webhook server process owns the
	// authoritative check at its startup.
	SecretEnvStatus string `protobuf:"bytes,4,opt,name=secret_env_status,json=secretEnvStatus,proto3" json:"secret_env_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebhookConfigState) Reset() {
	*x = WebhookConfigState{}
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookConfigState) ProtoMessage() {}

func (x *WebhookConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookConfigState.ProtoReflect.Descriptor instead.
func (*WebhookConfigState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookConfigState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WebhookConfigState) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WebhookConfigState) GetSecretEnv() string {
	if x != nil {
		return x.SecretEnv
	}
	return ""
}

func (x *WebhookConfigState) GetSecretEnvStatus() string {
	if x != nil {
		return x.SecretEnvStatus
	}
	return ""
}

// WebhookDelivery is one accepted webhook delivery from the agent's dedup
// ledger — the operational view of replay protection. Metadata only: no
// request bodies, no signatures, no headers.
type WebhookDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Commit        string                 `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookDelivery) Reset() {
	*x = WebhookDelivery{}
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDelivery) ProtoMessage() {}

func (x *WebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDelivery.ProtoReflect.Descriptor instead.
func (*WebhookDelivery) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *WebhookDelivery) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *WebhookDelivery) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WebhookDelivery) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *WebhookDelivery) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookDelivery) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

var File_internal_grpc_proto_webhook_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_webhook_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/webhook.proto\x12\x06phelix\"w\n" +
	"\x0eWebhookOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"secret_env\x18\x03 \x01(\tR\tsecretEnv\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xaf\x03\n" +
	"\n" +
	"WebhookJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05stage\x18\t \x01(\tR\x05stage\x12\x1f\n" +
	"\vaccepted_at\x18\n" +
	" \x01(\x03R\n" +
	"acceptedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\f \x01(\x03R\n" +
	"finishedAt\x12\x18\n" +
	"\aversion\x18\r \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\"\x91\x01\n" +
	"\x12WebhookConfigState\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"secret_env\x18\x03 \x01(\tR\tsecretEnv\x12*\n" +
	"\x11secret_env_status\x18\x04 \x01(\tR\x0fsecretEnvStatus\"\xba\x01\n" +
	"\x0fWebhookDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x16\n" +
	"\x06commit\x18\x04 \x01(\tR\x06commit\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAtB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_webhook_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_webhook_proto_rawDescData []byte
)

func file_internal_grpc_proto_webhook_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_webhook_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_webhook_proto_rawDesc), len(file_internal_grpc_proto_webhook_proto_rawDesc)))
	})
	return file_internal_grpc_proto_webhook_proto_rawDescData
}

var file_internal_grpc_proto_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_proto_webhook_proto_goTypes = []any{
	(*WebhookOptions)(nil),     // 0: phelix.WebhookOptions
	(*WebhookJob)(nil),         // 1: phelix.WebhookJob
	(*WebhookConfigState)(nil), // 2: phelix.WebhookConfigState
	(*WebhookDelivery)(nil),    // 3: phelix.WebhookDelivery
}
var file_internal_grpc_proto_webhook_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_webhook_proto_init() }
func file_internal_grpc_proto_webhook_proto_init() {
	if File_internal_grpc_proto_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_webhook_proto_rawDesc), len(file_internal_grpc_proto_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_grpc_proto_webhook_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_webhook_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_webhook_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_webhook_proto = out.File
	file_internal_grpc_proto_webhook_proto_goTypes = nil
	file_internal_grpc_proto_webhook_proto_depIdxs = nil
}
