// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CLIMetadata represents continuous metadata about the CLI installation.
type CLIMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken     string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	CliVersion       string                 `protobuf:"bytes,4,opt,name=cli_version,json=cliVersion,proto3" json:"cli_version,omitempty"`
	BuildVersion     string                 `protobuf:"bytes,5,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	GitCommit        string                 `protobuf:"bytes,6,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	BuildTime        string                 `protobuf:"bytes,7,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CurrentState     string                 `protobuf:"bytes,9,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	MonitorStatus    string                 `protobuf:"bytes,10,opt,name=monitor_status,json=monitorStatus,proto3" json:"monitor_status,omitempty"`
	TotalManagedApps int32                  `protobuf:"varint,11,opt,name=total_managed_apps,json=totalManagedApps,proto3" json:"total_managed_apps,omitempty"`
	RunningApps      int32                  `protobuf:"varint,12,opt,name=running_apps,json=runningApps,proto3" json:"running_apps,omitempty"`
	Timestamp        int64                  `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CLIMetadata) Reset() {
	*x = CLIMetadata{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIMetadata) ProtoMessage() {}

func (x *CLIMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIMetadata.ProtoReflect.Descriptor instead.
func (*CLIMetadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CLIMetadata) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CLIMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CLIMetadata) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CLIMetadata) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *CLIMetadata) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *CLIMetadata) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *CLIMetadata) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *CLIMetadata) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *CLIMetadata) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *CLIMetadata) GetMonitorStatus() string {
	if x != nil {
		return x.MonitorStatus
	}
	return ""
}

func (x *CLIMetadata) GetTotalManagedApps() int32 {
	if x != nil {
		return x.TotalManagedApps
	}
	return 0
}

func (x *CLIMetadata) GetRunningApps() int32 {
	if x != nil {
		return x.RunningApps
	}
	return 0
}

func (x *CLIMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MetadataResponse is the backend's response to metadata sync.
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\x06phelix\"\xce\x03\n" +
	"\vCLIMetadata\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1f\n" +
	"\vcli_version\x18\x04 \x01(\tR\n" +
	"cliVersion\x12#\n" +
	"\rbuild_version\x18\x05 \x01(\tR\fbuildVersion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x06 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_time\x18\a \x01(\tR\tbuildTime\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rcurrent_state\x18\t \x01(\tR\fcurrentState\x12%\n" +
	"\x0emonitor_status\x18\n" +
	" \x01(\tR\rmonitorStatus\x12,\n" +
	"\x12total_managed_apps\x18\v \x01(\x05R\x10totalManagedApps\x12!\n" +
	"\frunning_apps\x18\f \x01(\x05R\vrunningApps\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x03R\ttimestamp\"H\n" +
	"\x10MetadataResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB4Z2github.com/abdorrahmani/phelix/internal/grpc/protob\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_proto_goTypes = []any{
	(*CLIMetadata)(nil),      // 0: phelix.CLIMetadata
	(*MetadataResponse)(nil), // 1: phelix.MetadataResponse
}
var file_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
