package docker

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateCompose_AppOnly(t *testing.T) {
	cfg := ComposeConfig{
		AppName:   "myapp",
		ImageName: "myapp:v1.2.3",
		AppPort:   8080,
	}

	result := GenerateCompose(cfg)

	// Should contain the app service
	if !strings.Contains(result, "myapp:") {
		t.Error("compose should contain the app service")
	}
	if !strings.Contains(result, "image: myapp:v1.2.3") {
		t.Error("compose should reference the correct image")
	}
	if !strings.Contains(result, "8080:8080") {
		t.Error("compose should map the app port")
	}
	// Should have no depends_on when no sidecars
	if strings.Contains(result, "depends_on") {
		t.Error("compose should not have depends_on with no sidecars")
	}
}

func TestGenerateCompose_WithSidecars(t *testing.T) {
	cfg := ComposeConfig{
		AppName:   "myapp",
		ImageName: "myapp:latest",
		AppPort:   3000,
		DependsOn: []string{"redis", "postgres"},
	}

	result := GenerateCompose(cfg)

	// Should contain depends_on
	if !strings.Contains(result, "depends_on:") {
		t.Error("compose should contain depends_on")
	}
	if !strings.Contains(result, "- redis") {
		t.Error("compose should depend on redis")
	}
	if !strings.Contains(result, "- postgres") {
		t.Error("compose should depend on postgres")
	}

	// Should contain sidecar services
	if !strings.Contains(result, "redis:") {
		t.Error("compose should define redis service")
	}
	if !strings.Contains(result, "postgres:") {
		t.Error("compose should define postgres service")
	}

	// Should contain port mappings for sidecars
	if !strings.Contains(result, "6379:6379") {
		t.Error("compose should map redis port")
	}
	if !strings.Contains(result, "5432:5432") {
		t.Error("compose should map postgres port")
	}
}

func TestGenerateCompose_UnknownSidecarIgnored(t *testing.T) {
	cfg := ComposeConfig{
		AppName:   "myapp",
		ImageName: "myapp:latest",
		AppPort:   8080,
		DependsOn: []string{"unknown-service"},
	}

	result := GenerateCompose(cfg)

	// Unknown sidecar should be silently ignored
	if strings.Contains(result, "unknown-service:") {
		t.Error("unknown sidecar should not appear in compose output")
	}
}

func TestGenerateCompose_IncludesHeader(t *testing.T) {
	cfg := ComposeConfig{
		AppName:   "myapp",
		ImageName: "myapp:latest",
		AppPort:   8080,
	}

	result := GenerateCompose(cfg)

	if !strings.Contains(result, "Generated by phelix dockerize") {
		t.Error("compose should include generation header")
	}
	if !strings.Contains(result, "Phelix does NOT manage") {
		t.Error("compose should include lifecycle disclaimer")
	}
}

func TestWriteComposeFile(t *testing.T) {
	dir := t.TempDir()
	cfg := ComposeConfig{
		AppName:   "myapp",
		ImageName: "myapp:v1.0",
		AppPort:   8080,
		DependsOn: []string{"redis"},
	}

	if err := WriteComposeFile(dir, cfg); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatal(err)
	}

	content := string(data)
	if !strings.Contains(content, "myapp:") {
		t.Error("written compose file should contain the app service")
	}
	if !strings.Contains(content, "redis:") {
		t.Error("written compose file should contain redis service")
	}
}

func TestHasExistingCompose(t *testing.T) {
	dir := t.TempDir()

	if HasExistingCompose(dir) {
		t.Error("should not find docker-compose.yml in empty directory")
	}

	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte("version: '3'\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if !HasExistingCompose(dir) {
		t.Error("should find docker-compose.yml after creating one")
	}
}
