package docker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SidecarConfig defines a recognized sidecar service for docker-compose generation.
type SidecarConfig struct {
	Name    string
	Image   string
	Port    int
	Volumes []string
	Env     map[string]string
}

// KnownSidecars maps dependency names to their default configurations.
var KnownSidecars = map[string]SidecarConfig{
	"redis": {
		Name:  "redis",
		Image: "redis:7-alpine",
		Port:  6379,
	},
	"postgres": {
		Name:  "postgres",
		Image: "postgres:16-alpine",
		Port:  5432,
		Env: map[string]string{
			"POSTGRES_DB":       "app",
			"POSTGRES_USER":     "postgres",
			"POSTGRES_PASSWORD": "postgres",
		},
	},
	"mysql": {
		Name:  "mysql",
		Image: "mysql:8",
		Port:  3306,
		Env: map[string]string{
			"MYSQL_ROOT_PASSWORD": "root",
			"MYSQL_DATABASE":      "app",
		},
	},
	"mongodb": {
		Name:  "mongodb",
		Image: "mongo:7",
		Port:  27017,
	},
	"rabbitmq": {
		Name:  "rabbitmq",
		Image: "rabbitmq:3-management",
		Port:  5672,
	},
}

// ComposeConfig holds parameters for docker-compose.yml generation.
type ComposeConfig struct {
	AppName   string
	ImageName string   // e.g. "myapp:v1.2.3"
	AppPort   int      // The port the app listens on (inside the container)
	DependsOn []string // Sidecar names (redis, postgres, etc.)
}

// GenerateCompose produces a docker-compose.yml string for the app and
// requested sidecar services. This is generation-only — Phelix does not
// manage the lifecycle of these services.
func GenerateCompose(cfg ComposeConfig) string {
	var b strings.Builder

	b.WriteString("# Generated by phelix dockerize --with-compose\n")
	b.WriteString("# NOTE: Phelix does NOT manage the lifecycle (start/stop/health) of\n")
	b.WriteString("# services defined here. Use 'docker compose up -d' directly.\n\n")
	b.WriteString("version: '3.8'\n\n")
	b.WriteString("services:\n")

	// Collect valid sidecar configs
	var sidecars []SidecarConfig
	for _, dep := range cfg.DependsOn {
		if sc, ok := KnownSidecars[dep]; ok {
			sidecars = append(sidecars, sc)
		}
	}

	// App service block
	b.WriteString(fmt.Sprintf("  %s:\n", cfg.AppName))
	b.WriteString(fmt.Sprintf("    image: %s\n", cfg.ImageName))
	b.WriteString("    build:\n")
	b.WriteString("      context: .\n")
	b.WriteString("    ports:\n")
	b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", cfg.AppPort, cfg.AppPort))
	b.WriteString("    restart: unless-stopped\n")

	if len(sidecars) > 0 {
		b.WriteString("    depends_on:\n")
		for _, sc := range sidecars {
			b.WriteString(fmt.Sprintf("      - %s\n", sc.Name))
		}
	}

	// Sidecar service blocks
	for _, sc := range sidecars {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("  %s:\n", sc.Name))
		b.WriteString(fmt.Sprintf("    image: %s\n", sc.Image))
		b.WriteString("    ports:\n")
		b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", sc.Port, sc.Port))
		if len(sc.Env) > 0 {
			b.WriteString("    environment:\n")
			for k, v := range sc.Env {
				b.WriteString(fmt.Sprintf("      %s: \"%s\"\n", k, v))
			}
		}
		b.WriteString("    restart: unless-stopped\n")
	}

	return b.String()
}

// WriteComposeFile writes the generated docker-compose.yml to projectRoot.
func WriteComposeFile(projectRoot string, cfg ComposeConfig) error {
	content := GenerateCompose(cfg)
	return os.WriteFile(filepath.Join(projectRoot, "docker-compose.yml"), []byte(content), 0o644)
}

// HasExistingCompose reports whether a docker-compose.yml already exists.
func HasExistingCompose(projectRoot string) bool {
	_, err := os.Stat(filepath.Join(projectRoot, "docker-compose.yml"))
	return err == nil
}
